Description of voxpts
Home > marsbar > @maroi_pointlist > voxpts.m
voxpts
PURPOSE
voxpts method - returns 3xN ijk matrix in voxels
SYNOPSIS
function [pts, vals] = voxpts(o, sp)
DESCRIPTION
 voxpts method - returns 3xN ijk matrix in voxels
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
voxpts voxpts method - voxels within a box in given space
maroi_matrix maroi_matrix method - converts maroi_image to maroi_matrix
maroi_matrix maroi_matrix - class constructor
voxpts voxpts method - returns 3xN ijk matrix in voxels
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
voxpts voxpts method - returns 3xN ijk matrix in voxels
maroi_matrix method to convert shape objects to maroi_matrix objects
voxpts voxpts method - voxels within a sphere in given space
mars_space mars_space - class constructor for space defining object
This function is called by:
c_o_m c_o_m method - calculates unweighted centre of mass
realpts realpts method - returns 3xN XYZ matrix in mm
volume volume method - returns volume of ROI in mm
voxpts voxpts method - returns 3xN ijk matrix in voxels
maroi_matrix method to convert shape objects to maroi_matrix objects
SOURCE CODE
function [pts, vals] = voxpts(o, sp)
% voxpts method - returns 3xN ijk matrix in voxels
%
% $Id$
if nargin < 2
  error('Need space for voxpts call')
end
sp = mars_space(sp);
% to maroi_matrix object
mo = maroi_matrix(o);
% and return values
[pts, vals] = voxpts(mo, sp);