Description of pr_spm_svd
Home > marsbar > @mardo_5 > private > pr_spm_svd.m
pr_spm_svd
PURPOSE
computationally efficient SVD (that can handle sparse arguments)
SYNOPSIS
function [U,S,V] = pr_spm_svd(X,U,T)
DESCRIPTION
 computationally efficient SVD (that can handle sparse arguments)
 FORMAT [U,S,V] = pr_spm_svd(X,u,t);
 X    - {m x n} matrix
 u    - threshold for normalized eigenvalues (default = 1e-6)
 t    - threshold for raw eigenvalues        (default = 0)
 U    - {m x p} singular vectors
 V    - {m x p} singular variates
 S    - {p x p} singular values
___________________________________________________________________________
 Copyright (C) 2005 Wellcome Department of Imaging Neuroscience
CROSS-REFERENCE INFORMATION
This function calls:
pr_spm_en Euclidean normalization
This function is called by:
pr_estimate Estimation of a General Linear Model
pr_spm_reml REML estimation of covariance components from Cov{y}
pr_estimate Estimation of a General Linear Model
SOURCE CODE
function [U,S,V] = pr_spm_svd(X,U,T)
% computationally efficient SVD (that can handle sparse arguments)
% FORMAT [U,S,V] = pr_spm_svd(X,u,t);
% X    - {m x n} matrix
% u    - threshold for normalized eigenvalues (default = 1e-6)
% t    - threshold for raw eigenvalues        (default = 0)
%
% U    - {m x p} singular vectors
% V    - {m x p} singular variates
% S    - {p x p} singular values
%___________________________________________________________________________
% Copyright (C) 2005 Wellcome Department of Imaging Neuroscience
% Karl Friston
% $Id: spm_svd.m 112 2005-05-04 18:20:52Z john $
% default thresholds
%---------------------------------------------------------------------------
if nargin < 2
    U = 1e-6;
end
if nargin < 3
    T = 0;
end
% deal with sparse matrices
%---------------------------------------------------------------------------
[M N] = size(X);
p     = find(any(X,2));
q     = find(any(X,1));
X     = X(p,q);
% SVD
%---------------------------------------------------------------------------
[i j s] = find(X);
[m n]   = size(X);
if any(i - j)
    % off-leading diagonal elements - full SVD
    %-------------------------------------------------------------------
    X     = full(X);
    if m > n
        [v S v] = svd(spm_atranspa(X),0);
        S       = sparse(S);
        s       = diag(S);
        j       = find(s*length(s)/sum(s) >= U & s >= T);
        v       = v(:,j);
        u       = pr_spm_en(X*v);
        S       = sqrt(S(j,j));
    elseif m < n
        [u S u] = svd(spm_atranspa(X'),0);
        S       = sparse(S);
        s       = diag(S);
        j       = find(s*length(s)/sum(s) >= U & s >= T);
        u       = u(:,j);
        v       = pr_spm_en(X'*u);
        S       = sqrt(S(j,j));
    else
        [u S v] = svd(X,0);
        S       = sparse(S);
        s       = diag(S).^2;
          j       = find(s*length(s)/sum(s) >= U & s >= T);
        v       = v(:,j);
        u       = u(:,j);
        S       = S(j,j);
    end
else
    S     = sparse(1:n,1:n,s,m,n);
    u     = speye(m,n);
    v     = speye(m,n);
    [i j] = sort(-s);
    S     = S(j,j);
    v     = v(:,j);
    u     = u(:,j);
    s     = diag(S).^2;
     j     = find(s*length(s)/sum(s) >= U & s >= T);
    v     = v(:,j);
    u     = u(:,j);
    S     = S(j,j);
end
% replace in full matrices
%---------------------------------------------------------------------------
j      = length(j);
U      = sparse(M,j);
V      = sparse(N,j);
if j
    U(p,:) = u;
    V(q,:) = v;
end