Description of mars_space
Home > marsbar > @mars_space > mars_space.m
mars_space
PURPOSE
mars_space - class constructor for space defining object
SYNOPSIS
function [o, others] = mars_space(params, params2)
DESCRIPTION
 mars_space - class constructor for space defining object
 FORMAT [o, others] = mars_space(params, params2)
 Inputs [defaults]
 params  - either
           a structure, containing fields to construct the object
           an spm vol struct (see spm_vol)
           a string, giving and image name (see spm_vol)
           a matrix (for which, only the dimensions are used)
           a 3x1 or 1x3 dimension vector
 params2   in the latter 2 cases, might contain a 4x4 transformation matrix
           [eye(4)]
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
mars_struct multifunction function for manipulating structures
This function is called by:
getdata getdata method - fetches time series data for ROI from images
my_classdata my_classdata method - sets/gets class data
voxpts voxpts method - voxels within a box in given space
maroi_matrix maroi_matrix - class constructor
native_space native_space method - returns native space of object
rebase rebase method - returns data from maroi_matrix in new space
native_space native_space method - returns native space of object
voxpts voxpts method - returns 3xN ijk matrix in voxels
voxpts voxpts method - voxels within a sphere in given space
mars_build_roi builds ROIs via the SPM GUI
mars_display_roi utility routines for display of ROIs in graphic window
mars_options options utility routines
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function [o, others] = mars_space(params, params2)
% mars_space - class constructor for space defining object
% FORMAT [o, others] = mars_space(params, params2)
% Inputs [defaults]
% params  - either
%           a structure, containing fields to construct the object
%           an spm vol struct (see spm_vol)
%           a string, giving and image name (see spm_vol)
%           a matrix (for which, only the dimensions are used)
%           a 3x1 or 1x3 dimension vector
% params2   in the latter 2 cases, might contain a 4x4 transformation matrix
%           [eye(4)]
%
% $Id$
myclass = 'mars_space';
defstruct = struct('dim', [1 1 1],...
           'mat', eye(4));
if nargin < 1
  params = [];
end
if nargin < 2
  params2 = [];
end
if isa(params, myclass)
  o = params;
  return
end
% check inputs
if ~isstruct(params)
  % Matlab 7 does not like assigment of struct to non empty var
  inp1 = params;
  clear params;
  if ischar(inp1) % maybe it is an image filename
    params = spm_vol(inp1);
    params.dim = params.dim(1:3);
  elseif prod(size(inp1)) == 3
    % could be the dimensions of a space
    params.dim = inp1(:)';
    if ~isempty(params2), params.mat = params2; end
  else
    % lets hope it's a useful matrix, but with a mat parameter, quoi
    if isempty(params2)
      error(['Need to pass a ''mat'' definition with a'...
         ' matrix'])
    end
    params.mat = params2;
    m = inp1;
    sz = size(m);
    params.dim = [1 1 1];
    params.dim(1:length(sz)) = sz;
  end
end
% fill with defaults, parse into fields for this object, children
[pparams, others] = mars_struct('ffillsplit', defstruct, params);
o  = class(pparams, myclass);
return