Description of as_summary_only
Home > marsbar > @marsy > as_summary_only.m
as_summary_only
PURPOSE
returns object with region data removed
SYNOPSIS
function out_o = as_summary_only(o)
DESCRIPTION
 returns object with region data removed
 Useful to save memory
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
is_summarized returns 1 if object contains calculated summary data
resummarize recalculate summary data if possible
y_struct get/set method for y_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
SOURCE CODE
function out_o = as_summary_only(o)
% returns object with region data removed
%
% Useful to save memory
if ~is_summarized(o)
    out_o = resummarize(o);
else
    out_o = o;
end
st = y_struct(o);
if ~isfield(st, 'regions')
    return
end
for rno = 1:length(st.regions)
    st.regions{rno} = mars_struct('strip', st.regions{rno}, ...
        {'Y', 'weights','vXYZ'});
end
out_o = y_struct(out_o, st);
return