Description of block_rows
Home > marsbar > @marsy > block_rows.m
block_rows
PURPOSE
gets/sets cell array of rows for each (subject/session) block
SYNOPSIS
function r = block_rows(Y, rows)
DESCRIPTION
 gets/sets cell array of rows for each (subject/session) block
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
n_time_points get number of time_points in design
n_time_points get number of time_points
y_struct get/set method for y_struct field
This function is called by:
event_fitted_fir method to compute fitted event time courses using FIR
residuals method returns residuals from model
ui_ft_design_data method plots FT of design and data to graphics window
apply_filter applies filter in design to data
fill fills missing entries from SPM FMRI design matrix
fill fills missing entries from SPM FMRI design matrix
apply_filter applies filter in design to data
fill fills missing entries from SPM FMRI design matrix
get_marsy gets data in ROIs from images
n_blocks method returns number of subjects/sessions in data
summary_block_means return raw means over blocks in summary data
ui_plot method plots data in various formats
mars_image_scaling get image scaling data for images, maybe via SPM design
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function r = block_rows(Y, rows)
% gets/sets cell array of rows for each (subject/session) block
%
% $Id$
ys = y_struct(Y);
n  = n_time_points(Y);
if nargin < 2  % get
  if ~isfield(ys, 'block_rows')
    r = {[1:n]'};
  else
    r = ys.block_rows;
  end
else           % set
  if ~iscell(rows)
    error('Need cell array of matrices for blocks');
  end
  for i = 1:prod(size(rows))
    rows{i} = rows{i}(:);
    if any(rows{i} < 1 | rows{i} > n)
      error(sprintf('Row %d: values out of range', i));
    end
  end
  ys.block_rows = rows;
  r = y_struct(Y, ys);
end