Description of can_summarize
Home > marsbar > @marsy > can_summarize.m
can_summarize
PURPOSE
returns 1 if object contains enough information to be summarized
SYNOPSIS
function tf = can_summarize(o)
DESCRIPTION
 returns 1 if object contains enough information to be summarized
 or is already summarized
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
is_summarized returns 1 if object contains calculated summary data
n_regions get number of regions
region_size method to get size of specified region data
sumfunc method to get or set sumfunc
This function is called by:
join joins marsy objects into one object
summary method returns cell array of strings describing marsy object
SOURCE CODE
function tf = can_summarize(o)
% returns 1 if object contains enough information to be summarized
% or is already summarized
%
% $Id$
tf = 1;
if is_summarized(o), return, end
for i = 1:n_regions(o);
  r_samp = region_size(o, i, 2);
  if r_samp > 1 % at least one region needs summarizing
    % check for summary function
    s = sumfunc(o);
    tf = ~isempty(s) & ~strcmp(s, 'unknown');
    break
  end
end