Description of eq
Home > marsbar > @marsy > eq.m
eq
PURPOSE
method overrides == operator
SYNOPSIS
function tf = eq(Y1, Y2)
DESCRIPTION
 method overrides == operator
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
is_summarized returns 1 if object contains calculated summary data
region_data method gets or sets data for region(s) as cell array
summary_data method to get summary data, maybe set sumfunc
summary_size method returns number of time points x number of regions
This function is called by:
ne method overrides ~= operator
SOURCE CODE
function tf = eq(Y1, Y2)
% method overrides == operator
%
% $Id$
tf = 0;
if ~isa(Y1, 'marsy') | ~isa(Y2, 'marsy'), return, end
if ~all(summary_size(Y1) == summary_size(Y2)), return, end
if is_summarized(Y1) ~= is_summarized(Y2), return, end
if is_summarized(Y1)
  y1 = summary_data(Y1);
  y2 = summary_data(Y2);
else
  y1 = region_data(Y1);
  y1 = [y1{:}];
  y2 = region_data(Y2);
  y2 = [y2{:}];
end
tf = all(all(y1 == y2));