Description of is_summary_only
Home > marsbar > @marsy > is_summary_only.m
is_summary_only
PURPOSE
method returns 1 if object only contains summary data
SYNOPSIS
function tf = is_summary_only(o)
DESCRIPTION
 method returns 1 if object only contains summary data
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
region_data method gets or sets data for region(s) as cell array
y_struct get/set method for y_struct field
This function is called by:
SOURCE CODE
function tf = is_summary_only(o)
% method returns 1 if object only contains summary data
%
% $Id$
tf = 0;
st = y_struct(o);
if isfield(st, 'Y')
  if ~isfield(st, 'regions')
    tf = 1;
  else
    Y = region_data(o);
    Y = [Y{:}];
    tf = size(Y, 2) == size(st.Y, 2);
  end
end