Description of is_summarized
Home > marsbar > @marsy > is_summarized.m
is_summarized
PURPOSE
returns 1 if object contains calculated summary data
SYNOPSIS
function tf = is_summarized(o)
DESCRIPTION
 returns 1 if object contains calculated summary data
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
y_struct get/set method for y_struct field
This function is called by:
residuals method returns residuals from model
as_summary_only returns object with region data removed
can_summarize returns 1 if object contains enough information to be summarized
eq method overrides == operator
join joins marsy objects into one object
summary method returns cell array of strings describing marsy object
SOURCE CODE
function tf = is_summarized(o)
% returns 1 if object contains calculated summary data
%
% $Id$
st = y_struct(o);
tf = isfield(st, 'Y') & isfield(st, 'Yvar');