Description of join
Home > marsbar > @marsy > join.m
join
PURPOSE
joins marsy objects into one object
SYNOPSIS
function o = join(varargin)
DESCRIPTION
 joins marsy objects into one object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
n_time_points get number of time_points in design
can_summarize returns 1 if object contains enough information to be summarized
is_summarized returns 1 if object contains calculated summary data
n_time_points get number of time_points
region gets / sets data for region or regions
resummarize recalculate summary data if possible
sumfunc method to get or set sumfunc
summary_data method to get summary data, maybe set sumfunc
y_struct get/set method for y_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function o = join(varargin)
% joins marsy objects into one object
%
% $Id$
% assemble all input object into a cell array
% (deals with arrays of objects)
o_c_a = {};
ctr = 0;
n_n = [];
for v = 1:nargin
  o_arr = varargin{v};
  for i = 1:prod(size(o_arr))
    ctr = ctr + 1;
    % Check number of time points
    n = n_time_points(o_arr(i));
    if isempty(n_n), n_n = n;
    else
      if n ~= n_n
    error(sprintf(...
        'Regions %d and %d have different numbers of time points',...
        ctr, ctr-1));
      end
    end
    o_c_a{ctr} = o_arr(i);
  end
end
o = o_c_a{1};
want_sum_f = 1;
sum_func = sumfunc(o);
regions = {};
Y = [];
Yvar = [];
for i = 1:ctr
  o_a = o_c_a{i};
  if want_sum_f
    % if summary function differs from other
    % objects, abort collecting summary data
    if ~strcmp(sum_func,sumfunc(o_a)) | ...
      ~can_summarize(o_a)
      want_sum_f = 0;
    else
      if ~is_summarized(o_a)
    o_a = resummarize(o_a);
      end
      [t1 t2] = summary_data(o_a);
      Y =    [Y t1];
      Yvar = [Yvar t2];
    end
  end
  regions = [regions region(o_a)];
end
st = y_struct(o);
if want_sum_f
  st.Y = Y;
  st.Yvar = Yvar;
  st.sumfunc = sum_func;
else
  st = mars_struct('strip', st, {'Y','Yvar','sumfunc'});
end
st.regions = regions;
o = y_struct(o, st);