Description of n_blocks
Home > marsbar > @marsy > n_blocks.m
n_blocks
PURPOSE
method returns number of subjects/sessions in data
SYNOPSIS
function n = n_blocks(Y)
DESCRIPTION
 method returns number of subjects/sessions in data
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
block_rows returns cell array of rows for each (subject/session) block
block_rows returns cell array of rows for each (subject/session) block
block_rows gets/sets cell array of rows for each (subject/session) block
This function is called by:
ui_plot method plots data in various formats
SOURCE CODE
function n = n_blocks(Y)
% method returns number of subjects/sessions in data
%
% $Id$
n = length(block_rows(Y));