Description of n_regions
Home > marsbar > @marsy > n_regions.m
n_regions
PURPOSE
get number of regions
SYNOPSIS
function n = n_regions(o)
DESCRIPTION
 get number of regions
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
summary_size method returns number of time points x number of regions
This function is called by:
mars_spm_graph Graphical display of adjusted data
pr_estimate Estimation of a General Linear Model
pr_estimate Estimation of a General Linear Model
mars_spm_graph Graphical display of adjusted data
can_summarize returns 1 if object contains enough information to be summarized
region gets / sets data for region or regions
region_size method to get size of specified region data
summary method returns cell array of strings describing marsy object
xyz gets XYZ coordinates for region
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function n = n_regions(o)
% get number of regions
%
% $Id$
n = summary_size(o, 2);