Description of ne
Home > marsbar > @marsy > ne.m
ne
PURPOSE
method overrides ~= operator
SYNOPSIS
function tf = ne(Y1, Y2)
DESCRIPTION
 method overrides ~= operator
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
eq overloaded eq function
eq overloaded eq method for mars_space objects
eq method overrides == operator
This function is called by:
pr_spm_get_ons returns onset times for events
SOURCE CODE
function tf = ne(Y1, Y2)
% method overrides ~= operator
%
% $Id$
tf = ~eq(Y1, Y2);