Description of region_data
Home > marsbar > @marsy > region_data.m
region_data
PURPOSE
method gets or sets data for region(s) as cell array
SYNOPSIS
function res = region_data(varargin)
DESCRIPTION
 method gets or sets data for region(s) as cell array
 FORMAT res = region_data(o, r_nos) (get) OR
 FORMAT res = region_data(o, r_nos, new_data) (set)
 See region_field for details
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
region_field method gets or sets data for region field
This function is called by:
apply_filter applies filter in design to data
pr_estimate Estimation of a General Linear Model
pr_estimate Estimation of a General Linear Model
apply_filter applies filter in design to data
eq method overrides == operator
is_summary_only method returns 1 if object only contains summary data
summary_data method to get summary data, maybe set sumfunc
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function res = region_data(varargin)
% method gets or sets data for region(s) as cell array
% FORMAT res = region_data(o, r_nos) (get) OR
% FORMAT res = region_data(o, r_nos, new_data) (set)
%
% See region_field for details
%
% $Id$
res = region_field('Y', varargin{:});