Description of region_field
Home > marsbar > @marsy > region_field.m
region_field
PURPOSE
method gets or sets data for region field
SYNOPSIS
function res = region_field(fieldname, o, r_nos, new_data)
DESCRIPTION
 method gets or sets data for region field
 FORMAT res = region_field(fieldname, o, r_nos) (get) OR
 FORMAT res = region_field(fieldname, o, r_nos, new_data) (set)
 Inputs
 fieldname      - name of field to get / set
 o              - marsy object
 r_nos          - region number
                  or array of region numbers
                  or empty - giving all regions
 new_data       - cell array, containing new data to set
 Returns
 (get call)
 res             - cell array of region field values OR
 (set call)
 res             - object with new field data set
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
region gets / sets data for region or regions
This function is called by:
region_data method gets or sets data for region(s) as cell array
region_descrip method gets or sets descrip for region(s) as cell array
region_info method gets or sets info for region(s) as cell array
region_weights method gets or sets weights for region(s) as cell array
SOURCE CODE
function res = region_field(fieldname, o, r_nos, new_data)
% method gets or sets data for region field
% FORMAT res = region_field(fieldname, o, r_nos) (get) OR
% FORMAT res = region_field(fieldname, o, r_nos, new_data) (set)
%
% Inputs
% fieldname      - name of field to get / set
% o              - marsy object
% r_nos          - region number
%                  or array of region numbers
%                  or empty - giving all regions
% new_data       - cell array, containing new data to set
%
% Returns
% (get call)
% res             - cell array of region field values OR
% (set call)
% res             - object with new field data set
%
% $Id$
if nargin < 2
  error('Need fieldname');
end
if nargin < 3
  r_nos = [];
end
if nargin < 4 % get call
  [rs r_nos] = region(o, r_nos);
  for i = 1:length(r_nos)
    res{i} = getfield(rs{i}, fieldname);
  end
else          % set call
  res = region(o, r_nos, new_data, fieldname);
end