Description of resummarize
Home > marsbar > @marsy > resummarize.m
resummarize
PURPOSE
recalculate summary data if possible
SYNOPSIS
function o = resummarize(o)
DESCRIPTION
 recalculate summary data if possible
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
sumfunc method to get or set sumfunc
summary_data method to get summary data, maybe set sumfunc
This function is called by:
residuals method returns residuals from model
as_summary_only returns object with region data removed
join joins marsy objects into one object
marsy Class constructor for marsy: the MarsBaR data object
region gets / sets data for region or regions
SOURCE CODE
function o = resummarize(o)
% recalculate summary data if possible
%
% $Id$
s_f = sumfunc(o);
if ~isempty(s_f) & ~strcmp(s_f, 'unknown')
  [t1 t2 o] = summary_data(o, s_f);
end