Description of split
Home > marsbar > @marsy > split.m
split
PURPOSE
method splits regions in object into separate objects
SYNOPSIS
function o_arr = split(o)
DESCRIPTION
 method splits regions in object into separate objects
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
region gets / sets data for region or regions
y_struct get/set method for y_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function o_arr = split(o)
% method splits regions in object into separate objects
%
% $Id$
r = region(o);
st = y_struct(o);
is_s = isfield(st, 'Y') & isfield(st, 'Yvar');
if is_s
  Y = st.Y;
  Yvar = st.Yvar;
else
  % remove any rogue Y or Yvar fields
  st = mars_struct('strip', st, {'Y','Yvar'});
end
for i = 1:length(r)
  r_st = st;
  r_st.regions = r(i);
  if is_s
    r_st.Y    = Y(:, i);
    r_st.Yvar = Yvar(:, i);
  end
  o_arr(i) = y_struct(o, r_st);
end