Description of sumfunc
Home > marsbar > @marsy > sumfunc.m
sumfunc
PURPOSE
method to get or set sumfunc
SYNOPSIS
function o = sumfunc(o, sumfunc)
DESCRIPTION
 method to get or set sumfunc
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
sumfunc method to get or set sumfunc
y_struct get/set method for y_struct field
This function is called by:
get_marsy gets data in ROIs from images
can_summarize returns 1 if object contains enough information to be summarized
join joins marsy objects into one object
pr_sum_func creates summary stats for region data
region gets / sets data for region or regions
resummarize recalculate summary data if possible
sumfunc method to get or set sumfunc
summary method returns cell array of strings describing marsy object
summary_data method to get summary data, maybe set sumfunc
ui_plot method plots data in various formats
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function o = sumfunc(o, sumfunc)
% method to get or set sumfunc
%
% $Id$
if nargin < 2
  % get
  st = y_struct(o);
  if isfield(st, 'sumfunc')
    o = st.sumfunc;
  else
    o = '';
  end
else
  % set
  o.y_struct.sumfunc = sumfunc;
end