Description of summary_descrip
Home > marsbar > @marsy > summary_descrip.m
summary_descrip
PURPOSE
get/set method for summary data description
SYNOPSIS
function res = summary_descrip(o, descrip)
DESCRIPTION
 get/set method for summary data description
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
descrip method gets cell string description of design
isfield method to overload isfield for mardo objects
descrip name - returns / sets name value for object
y_struct get/set method for y_struct field
This function is called by:
residuals method returns residuals from model
summary method returns cell array of strings describing marsy object
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function res = summary_descrip(o, descrip)
% get/set method for summary data description
%
% $Id$
st = y_struct(o);
if nargin < 2 % get
  res = '';
  if isfield(st, 'descrip')
    res = st.descrip;
  end
else % set
  st.descrip = descrip;
  o = y_struct(o, st);
  res = o;
end