Description of summary_block_means
Home > marsbar > @marsy > summary_block_means.m
summary_block_means
PURPOSE
return raw means over blocks in summary data
SYNOPSIS
function mus = summary_block_means(Y)
DESCRIPTION
 return raw means over blocks in summary data
 Input
 Y        - marsy object
 mus      - means over block.  Returns B x N matrix
            where B is number of blocks, and N is number
            of ROIs
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
block_rows returns cell array of rows for each (subject/session) block
block_rows returns cell array of rows for each (subject/session) block
block_rows gets/sets cell array of rows for each (subject/session) block
summary_data method to get summary data, maybe set sumfunc
This function is called by:
block_means method returns means for blocks in design
SOURCE CODE
function mus = summary_block_means(Y)
% return raw means over blocks in summary data
%
% Input
% Y        - marsy object
%
% mus      - means over block.  Returns B x N matrix
%            where B is number of blocks, and N is number
%            of ROIs
%
% $Id$
y = summary_data(Y);
r = block_rows(Y);
B = length(r);
N = size(y, 2);
mus = zeros(B, N);
for b = 1:B
  mus(b, :) = mean(y(r{b},:),1);
end