Description of summary_size
Home > marsbar > @marsy > summary_size.m
summary_size
PURPOSE
method returns number of time points x number of regions
SYNOPSIS
function [m,n] = summary_size(o, dim)
DESCRIPTION
 method returns number of time points x number of regions
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
This function is called by:
eq method overrides == operator
n_regions get number of regions
n_time_points get number of time_points
summary_data method to get summary data, maybe set sumfunc
ui_plot method plots data in various formats
SOURCE CODE
function [m,n] = summary_size(o, dim)
% method returns number of time points x number of regions
%
% $Id$
st = o.y_struct;
sz = [0 0];
if isfield(st, 'Y')
  sz = size(st.Y);
elseif isfield(st, 'regions')
  if iscell(st.regions)
    if isfield(st.regions{1}, 'Y')
      sz(1) = size(st.regions{1}.Y, 1);
    end
  end
  sz(2) = length(st.regions);
end
if nargin < 2
  if nargout > 1
    m = sz(1); n = sz(2);
  else
    m = sz;
  end
else
  if dim > 2
    m = (m+n > 0)
  else
    m = sz(dim);
  end
end