Description of verbose
Home > marsbar > @marsy > verbose.m
verbose
PURPOSE
get/set method for verbose field
SYNOPSIS
function res = verbose(obj, data)
DESCRIPTION
 get/set method for verbose field
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
data method to get or set data object
This function is called by:
add_contrasts method to add contrast definitions to design
cd_images method for changing path to image files in design
mardo mardo - class constructor for MarsBaR design object
autocorr method to set autocorrelation types for design
estimate estimate method - estimates GLM for SPM2 model
event_x_fir method to return FIR design matrix columns for session
fill fills missing entries from SPM FMRI design matrix
save_spm method to save design as SPM format design structure
autocorr method to set autocorrelation types for design
estimate estimate method - estimates GLM for SPM2 model
fill fills missing entries from SPM FMRI design matrix
event_onsets method gets (estimated) onsets and durations for event/session
event_x_fir method to return FIR design matrix columns for session
save_spm method to save design as SPM format design structure
summary_data method to get summary data, maybe set sumfunc
SOURCE CODE
function res = verbose(obj, data)
% get/set method for verbose field
%
% $Id$
if nargin > 1
  obj.verbose = data;
  res = obj;
else
  res = obj.verbose;
end