Description of y_struct
Home > marsbar > @marsy > y_struct.m
y_struct
PURPOSE
get/set method for y_struct field
SYNOPSIS
function res = y_struct(obj, Struct)
DESCRIPTION
 get/set method for y_struct field
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
savestruct saves data in def_struct as variables in .mat file
savestruct saves data in def_struct into .mat file with variable name SPM
as_summary_only returns object with region data removed
block_rows gets/sets cell array of rows for each (subject/session) block
is_summarized returns 1 if object contains calculated summary data
is_summary_only method returns 1 if object only contains summary data
is_valid method returns 1 if object contains valid data
join joins marsy objects into one object
region gets / sets data for region or regions
region_size method to get size of specified region data
savestruct saves data in y_struct as variables in .mat file
split method splits regions in object into separate objects
sumfunc method to get or set sumfunc
summary_data method to get summary data, maybe set sumfunc
summary_descrip get/set method for summary data description
summary_info get/set method for summary data info
xyz gets XYZ coordinates for region
SOURCE CODE
function res = y_struct(obj, Struct)
% get/set method for y_struct field
%
% $Id$
if nargin > 1
  obj.y_struct = Struct;
  res = obj;
else
  res = obj.y_struct;
end