Description of mars_veropts
Home > marsbar > spm5 > mars_veropts.m
mars_veropts
PURPOSE
returns SPM version specific parameters
SYNOPSIS
function varargout = mars_veropts(arg, varargin)
DESCRIPTION
 returns SPM version specific parameters
 FORMAT varargout = mars_veropts(arg, varargin)
 This is the SPM 5 version
 $Id: mars_veropts.m 350 2004-08-12 06:52:18Z matthewbrett $
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
mardo_5 class constructor for SPM5 MarsBaR design object
This function is called by:
fill fills missing entries from SPM FMRI design matrix
pr_spm_ui MarsBaR: setting up the general linear model for independent data
fill fills missing entries from SPM FMRI design matrix
fill fills missing entries from SPM FMRI design matrix
pr_spm_ui MarsBaR: setting up the general linear model for independent data
mars_build_roi builds ROIs via the SPM GUI
mars_display_roi utility routines for display of ROIs in graphic window
mars_image_scaling get image scaling data for images, maybe via SPM design
mars_img2rois creates ROIs from cluster image or image containing ROIs defined by unique nos
mars_options options utility routines
mars_orthviews Display Orthogonal Views of a Normalized Image
mars_utils collection of useful utility functions for MarsBaR etc
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function varargout = mars_veropts(arg, varargin)
% returns SPM version specific parameters
% FORMAT varargout = mars_veropts(arg, varargin)
%
% This is the SPM 5 version
%
% $Id: mars_veropts.m 350 2004-08-12 06:52:18Z matthewbrett $
if nargin < 1
  varargout = {};
  return
end
switch lower(arg)
 case 'defaults'
  global defaults
  if isempty(defaults)
      try
        % SPM8 likes to return the defaults
        defaults = spm('defaults','FMRI');
      catch
        % SPM5 does not
        spm_defaults;
        spm('defaults','FMRI');
      end
  end
  varargout = {defaults};
 case 'default_design'
  varargout = {mardo_5};
 case 'template_ext' % extension for template images
  varargout = {'.nii'};
 case 'get_img_ext' % default image extension for spm_get
  varargout = {'image'};
 case 'pref_img_out_ext' % preferred extension for writing images
  varargout = {'.nii'};
 case 'des_conf'     % filter for configured, not estimated SPM designs
  varargout = {'SPM.mat'};
 case 'flip_option'
  varargout = {spm_flip_analyze_images};
 case 'design_filter_spec'
  varargout = {{...
    'SPM.mat','SPM.mat; 5,2 (all)/99 (estimated: SPM.mat)';...
    'SPMcfg.mat','99 with imgs: SPMcfg.mat';...
    'SPM_fMRIDesMtx.mat','99,FMRI,no imgs: SPM*fMRI*'}};
 otherwise
  error(['You asked for ' arg ', which is strange']);
end