function figNum = initfigvol(V,Num,nbcoupe)
% initialize figure for volume
%
% $Id$
  
     minimum=1; % 0 all fonction (even buggi one) 1 just the robustest 

%screenSize = get(0,'ScreenSize')  -> 1 1 1024 768

	oldFigNumber=watchon;
figNum =figure( ...
               'Name','affichage maison', ...
               'Units','Pixel', ...
               'Position',[100 20 800 700], ...
               'NumberTitle','off');
colordef(figNum,'black');
colormap(gray);

h0=figNum;
hdl.figNum = figNum;

max_axes = [612 512];mmm=max_axes/2; dec = 15;
hdl.axe(1) = axes('unit','pixel','Position',[29  80  mmm(1) mmm(2)]);
hdl.axe(2) = axes('unit','pixel','Position',...
		  [29+mmm(1)+dec  80  mmm(1) mmm(2)]);
hdl.axe(3) = axes('unit','pixel','Position',...
		  [29  80+mmm(2)+dec  mmm(1) mmm(2)]);
hdl.axe(4) = axes('unit','pixel','Position',...
		  [29+mmm(1)+dec  80+mmm(2)+dec  mmm(1) mmm(2)]);


%   [left bottom width height]

%====================================
nz = nbcoupe;%size(V,3);
str = ['/' num2str(nz)];

   hdl.space.txtcoupe = uicontrol( ...
	'Units','normalized', ...
	'ListboxTop',1, ...
	'Position',[0.91 0.94 0.06 0.03], ...
	'HorizontalAlignment','left',...
	'Style','text', ...
	'string', str,...
	'HorizontalAlignment', 'center',...
	'Tag','StaticText2');
    
   hdl.space.txt_editcoupe = uicontrol( ...
	'Units','normalized', ...
	'ListboxTop',1, ...
	'Position',[0.85 0.94 0.06 0.03], ...
	'HorizontalAlignment','left',...
	'Style','edit', ...
	'HorizontalAlignment', 'center',...
	'Tag','StaticText2', ...
        'Callback','affichevol(1,''go2coupe'')');


%====================================
 % The PLUS  Moins buttons start stop
hdl.space.plus=    uicontrol( ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.85 0.89 0.04 0.04], ...
        'String','+', ...
        'Interruptible','on', ...
        'Callback','affichevol(1,''Plus'');');

hdl.space.moins=    uicontrol( ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.91 0.89 0.04 0.04], ...
        'String','-', ...
        'Callback','affichevol(1,''Moins'')');

hdl.space.syn_coupe ...
	= uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.97 0.89 0.03 0.03], ...
        'TooltipString','synchronize the slice for all view',...
	'Style','checkbox');

hdl.space.start = uicontrol( ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.85 0.85 0.04 0.035], ...
        'BackgroundColor',[1 1 1],...
        'String','start',...
        'CallBack','affichevol(1,''start'')');
     
hdl.space.stop = uicontrol( ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.85 0.85 0.04 0.035], ...
        'BackgroundColor',[1 1 1],...
        'String','stop',...
	'visible','off',...
        'CallBack','hdl = get(gcf,''UserData'');set(hdl.space.start,''UserData'',0)');          

    hdl.space.pause = uicontrol( ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[0.9 0.85 0.05 0.035], ...
        'BackgroundColor',[1 1 1],...
        'String','0');
     
    
   hdl.space.txt_nbvol = uicontrol( ...
	'Units','normalized', ...
	'ListboxTop',1, ...
	'Position',[0.91 0.6 0.061 0.03], ...
	'HorizontalAlignment','left',...
	'Style','text', ...
	'string', str,...
	'HorizontalAlignment', 'center',...
	'Tag','StaticText2');
    
   hdl.space.txt_edit_nbvol = uicontrol( ...
	'Units','normalized', ...
	'ListboxTop',1, ...
	'Position',[0.85 0.6 0.061 0.04], ...
	'HorizontalAlignment','left',...
	'Style','edit', ...
	'HorizontalAlignment', 'center',...
	'Tag','StaticText2', ...
        'Callback','affichevol(1,''go2nbvol'')');

    hdl.space.time_slider = uicontrol(...             
   'Units','normalized', ...       
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[0.91 0.59 0.09 0.03], ...
	'Style','slider', ...
        'Tag','time_slider', ...
        'Callback','affichevol(1,''time_slider'');');

%orientation buton
hdl.space.orient = uicontrol('Parent',h0, ...
			'Units','normalized', ...
			'Callback','affichevol(1,''orient'')', ...
			'Interruptible','off', ...
			'ListboxTop',0, ...
			'Position',[0.85 0.80 0.08 0.03], ...
			'String',{'axial','sagittal','coronal',}, ...
			'Style','popupmenu', ...
			'Tag','exam', ...
			'Value',1);

hdl.space.space = uicontrol('Parent',h0, ...
			'Units','normalized', ...
			'Callback','affichevol(1,''change_space'')', ...
			'Interruptible','off', ...
			'ListboxTop',0, ...
			'Position',[0.93 0.80 0.08 0.03], ...
			'String',{'Box','Space','New'}, ...
			'Style','popupmenu', ...
			'Tag','exam', ...
			'Value',1);

hdl.space.axes  = uicontrol('Parent',h0, ...
			'Units','normalized', ...
			'Callback','affichevol(11,''change_axis'')', ...
			'Interruptible','off', ...
			'ListboxTop',0, ...
			'Position',[0.89 0.75 0.08 0.03], ...
			'String',{'1','2','3','4'}, ...
			'Style','popupmenu', ...
			'Tag','exam', ...
			'Value',1);


%===================================
%The ROI buton

hdl.Roi.disp = uicontrol( ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[0.91 0.70 0.09 0.04], ...
        'BackgroundColor',[1 1 1],...
        'String','',...
        'CallBack','affichevol(0,''nothing'')');
%        'CallBack','affichevol(4,''find_clus'')');

hdl.Roi.txt  = uicontrol( ...
	'Parent',figNum, ...
	'Units','normalized', ...
        'Position',[0.85 0.70 0.05 0.04], ...
	'HorizontalAlignment','left',...
	'Style','text', ...
        'String','Roi',...
	'Tag','StaticText2');


hdl.Roi.draw ...
	= uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.85 0.65 0.03 0.03], ...
	'Style','checkbox', ...
	'Callback','affichevol(3,''ROI_draw'')');

hdl.Roi.draw_txt  = uicontrol('Parent',figNum, ...
	'Units','normalized', ...
        'Position',[0.90 0.65 0.08 0.03], ...
	'HorizontalAlignment','left',...
	'Style','text', ...
        'String','ROI draw',...
	'Tag','StaticText2');

%===================================

 %######################################################################
 % The Tpos handel buttons
 %######################################################################

%===================================
%Tpos handel

    hdl.tpos_hdl.Series_disp = uicontrol( ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[0.70 0.96 0.09 0.03], ...
        'BackgroundColor',[1 1 1],...
        'String','1',...
        'CallBack','affichevol(0,''nothing'')');

    hdl.tpos_hdl.Series_disp_txt  = uicontrol('Parent',figNum, ...
	'Units','normalized', ...
	'HorizontalAlignment','left',...
        'Position',[0.65 0.96 0.03 0.03], ...
	'Style','text', ...
        'String','disp',...
	'Tag','StaticText2');
    
   hdl.tpos_hdl.Series_in = uicontrol( ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[0.59 0.96 0.05 0.03], ...
        'BackgroundColor',[1 1 1],...
        'String','1');
    
 hdl.tpos_hdl.Series_in_txt  = uicontrol('Parent',figNum, ...
	'Units','normalized', ...
        'Position',[0.55 0.96 0.03 0.03], ...
	'HorizontalAlignment','left',...
	'Style','text', ...
        'String','in',...
	'Tag','StaticText2');


%===================================
%Tpos calculated

    hdl.tpos_hdl.result ...
	 = uicontrol('Parent',figNum, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','affichevol(4,''changeRes'')', ...
	'Position',[0.44 0.905 0.35 0.04], ...
	'String',' ', ...
	'Style','popupmenu', ...
	'Tag','ListCon', ...
	'HorizontalAlignment','left',...
	'Value',1);

    hdl.tpos_hdl.listCon ...
	 = uicontrol('Parent',figNum, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','', ...
	'Position',[0.05 0.95 0.45 0.05], ...
	'String',' ', ...
	'Style','popupmenu', ...
	'Tag','ListCon', ...
	'HorizontalAlignment','left',...
	'Value',1);

    hdl.tpos_hdl.prob_txt  = uicontrol( ...
	'Style','text', ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.05 0.915 0.03 0.02], ...
        'String','P',...
	'Tag','EditText1');

    hdl.tpos_hdl.u_Seuil = uicontrol( ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[0.09 0.91 0.12 0.03], ...
        'BackgroundColor',[1 1 1],...
        'String','0.001',...
        'CallBack','');


    hdl.tpos_hdl.corected = uicontrol( ...
        'Style','checkbox', ...
        'Units','normalized', ...
        'Position',[0.225 0.91 0.03 0.03], ...
	'value', 0,...
	'Tag','Check_corrected');

    hdl.tpos_hdl.k_Seuil = uicontrol( ...
        'Style','edit', ...
        'Units','normalized', ...
        'Position',[0.27 0.91 0.03 0.03], ...
        'BackgroundColor',[1 1 1],...
        'String','0',...
        'CallBack','');
     
hdl.tpos_hdl.update=    uicontrol( ...
        'Style','push', ...
        'Units','normalized', ...
        'position',[0.32 0.91 0.08 0.03], ...
        'string','update', ...
        'call','affichevol(4,''SPM2Tpos'')');
     
 

%====================================
%the Data volume list
 
hdl.vol_list	 = uicontrol('Parent',figNum, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','affichevol(get(gcbo,''value''))', ...
	'Position',[0.55 0.01 0.9 0.04], ...
	'String',' ', ...
	'Style','popupmenu', ...
	'Tag','ListCon', ...
	'HorizontalAlignment','left',...
	'Value',1);

          
%====================================
% The CLOSE button
    
hdl.view.close =   uicontrol( ...
        'Style','push', ...
        'Units','normalized', ...
        'position',[0.92 0 0.08 0.08], ...
        'string','Close', ...
        'call','affichevol(1,''fermer'')');
     

%====================================
%the COLOR slice bar
    
hdl.color.slide_max = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','affichevol(1,''slide'')', ...
	'ListboxTop',0, ...
	'Position',[0.1 0.06 0.3 0.02], ...
	'Style','slider', ...
	'Tag','Slider1');

hdl.color.slide_mean = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','affichevol(1,''slide_mean'')', ...
	'ListboxTop',0, ...
	'Position',[0.1 0.035 0.3 0.02], ...
	'Style','slider', ...
	'Tag','Slider2');
	
hdl.color.slide_min = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','affichevol(1,''slide'')', ...
	'ListboxTop',0, ...
	'Position',[0.1 0.01 0.3 0.02], ...
	'Style','slider', ...
	'Tag','Slider2');


hdl.color.edit_min = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[0.03 0.03 0.05 0.03], ...
	'Style','text', ...
	'Tag','EditText1');

hdl.color.edit_max = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[0.43 0.03 0.05 0.03], ...
	'Style','text', ...
	'Tag','EditText2');

hdl.color.col_ini = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.75 0.7], ...
	'Callback','affichevol(1,''colorlim_init'')', ...
	'ListboxTop',0, ...
	'Position',[0.5 0.01 0.04 0.03], ...
	'TooltipString','auto color map (from the min/max of the slice)',...
	'String','ini', ...
	'Tag','Pushbutton1');


    %====================================
%%%%%%%%%%%    UIMENU      %%%%%%%%%%%%%%%%%%%%%%%%    
    
    menuh1 = uimenu(gcf,'label','psss');
    uimenu(menuh1,'label','Voyons','callback', 'affichevol(1,''Voyons'')');

    menuh2 = uimenu(gcf,'label','Segm');
    
    uimenu(menuh2,'label','Seg','callback','affichevol(2,''Seg'')');
    uimenu(menuh2,'label','Bw2Pos','callback','affichevol(2,''Bw2Pos'')');
    uimenu(menuh2,'label','Bw2Cont','callback','affichevol(2,''Bw2Cont'')');
    uimenu(menuh2,'label','Hist','callback','affichevol(2,''Hist'')');
    uimenu(menuh2,'label','LoadBw','callback','affichevol(2,''LoadBw'')');
    uimenu(menuh2,'label','LoadMask','callback','affichevol(2,''LoadMask'')');
    uimenu(menuh2,'label','SaveBw','callback','affichevol(2,''SaveBw'')');
    uimenu(menuh2,'label','CleanCont&Bw','callback','affichevol(2,''CleanCont&Bw'')');
    	menuh22 = uimenu(menuh2,'label','ttt');
      uimenu(menuh22,'label','Segone','callback','affichevol(2,''Segone'')');
    	uimenu(menuh22,'label','choose','callback','affichevol(2,''choose'')');
    	uimenu(menuh22,'label','rempli','callback','affichevol(2,''rempli'')');
      uimenu(menuh22,'label','CleanCoupe','callback','affichevol(2,''CleanCoupeBw'')');
      uimenu(menuh22,'label','CloseBw','callback','affichevol(2,''CloseBw'')');



    menuh3 = uimenu(gcf,'label','ROI');

    uimenu(menuh3,'label','point by point','callback','affichevol(3,''ChoisiPos'')');
    uimenu(menuh3,'label','clean the selection','callback','affichevol(3,''clean_SelectPos'')');
 uimenu(menuh3,'label','load ROI','callback','affichevol(3,''loadPos'')');
 uimenu(menuh3,'label','build ROI','callback','affichevol(3,''buildROI'')');
 uimenu(menuh3,'label','Save ROI','callback','affichevol(3,''SavePos'')');
%uimenu(menuh3,'label','ROI->mask','callback','affichevol(3,''ROItomask'')');
 uimenu(menuh3,'label','clear ROI','callback','affichevol(3,''CleanPos'')');
 
    uimenu(menuh3,'label','clear all ROI','callback','affichevol(3,''CleanAllPos'')');
 
    visu    = uimenu(menuh3,'label','color or size','callback','affichevol(1,''visu_Pos'')');
 
    uimenu(visu,'label',' size','callback','affichevol(3,''visu_Pos_size'')');
    uimenu(visu,'label','color ','callback','affichevol(3,''visu_Pos_color'')');
    uimenu(visu,'label','legende ','callback','affichevol(3,''visu_Pos_legende'')');



    menuh4 = uimenu(gcf,'label','Tpos');
%    uimenu(menuh4,'label','load Contrast','callback','affichevol(4,''loadCon'')');
    uimenu(menuh4,'label','load Contrast','callback','affichevol(4,''loadRes'')');
    uimenu(menuh4,'label','Cluster ini','callback','affichevol(4,''Cluster_ini'')');
    uimenu(menuh4,'label','Commun T','callback','affichevol(4,''inter_T'')'); 
    uimenu(menuh4,'label','Tpos2Pos','callback','affichevol(4,''Tpos2Pos'')');
    uimenu(menuh4,'label','load Tpos','callback','affichevol(4,''LoadTpos'')');
    uimenu(menuh4,'label','save Tpos','callback','affichevol(4,''SaveTpos'')');
    uimenu(menuh4,'label','ClearTpos','callback','affichevol(4,''ClearTpos'')');

    uimenu(menuh4,'label','hide','callback','affichevol(11,''hide_Tpos'')');
%    uimenu(menuh4,'label','Seuil','callback','affichevol(4,''Seuil'')','enable','off');
   
    menuh5 = uimenu(gcf,'label','Decours');
    
    uimenu(menuh5,'label','init','callback','affichevol(5,''init'')');
    uimenu(menuh5,'label','Hide tmp','callback','affichevol(11,''hide_tempo'')');
    uimenu(menuh5,'label','start : cine','callback','affichevol(5,''cinema'')');

    menuh6 = uimenu(gcf,'label','graph');
    uimenu(menuh6,'label','zoom','callback', 'zoom');


    color_m = uimenu(menuh6,'label','color');
    uimenu(menuh6,'label','pixval','callback', 'pixval');
    uimenu(menuh6,'label','diff','callback','affichevol(1,''diff'')');
%    uimenu(menuh6,'label','axeson','callback','set(gca,''visible'',''on'')');
    uimenu(menuh6,'label','grill','callback','affichevol(1,''grille'')');

    uimenu(menuh6,'label','Print','callback','affichevol(1,''print'')');

    

maps = str2mat('gray','hsv','hot','pink','cool','bone','jet','copper','flag','prism');
colormenuh = uimenu(color_m,'label','colormaps');
colormenuh2 = uimenu(color_m,'label','color_actions');

    uimenu(color_m,'label','AutoLim','callback','affichevol(1,''Autolim'')');
    uimenu(color_m,'label','colorbar','callback','affichevol(1,''colorbar'')');


for k = 1:size(maps,1);
   uimenu(colormenuh,'label',maps(k,:),'callback',['colormap(' maps(k,:) ');']);
end

uimenu(colormenuh,'label','rand', 'callback','colormap(rand(lengthofmap,3))');


uimenu(colormenuh2,'label','firs_end', 'callback','map = colormap; map(1,:)=map(end,:); colormap(map)');
uimenu(colormenuh2,'label','inverse','callback','colormap(flipud(colormap))');
uimenu(colormenuh2,'label','permute','callback','c = colormap; colormap(c(:,[2 3 1]))');

uimenu(colormenuh2,'label','brighten','callback','brighten(.25)');
uimenu(colormenuh2,'label','darken','callback','brighten(-.25)');

uimenu(colormenuh2,'label','fliplr','callback','colormap(fliplr(colormap))');

uimenu(colormenuh2,'label','spin','callback','spinmap');
uimenu(colormenuh2,'label','remember','callback','affichevol(1,''remember'')');

uimenu(colormenuh2,'label','restore', ...
   'callback','affichevol(1,''restore'')');


%uimenu(colormenuh,'label','done','Callback',...
%       'delete(colormenuh);clear stackofmaps lengthofmap maps colormenuh k');

    
%menu_orient = uimenu(gcf,'label','orient');
%      uimenu(menu_orient,'label','axial','callback', 'affichevol(1,''orient_axial'')');
%      uimenu(menu_orient,'label','coronal','callback', 'affichevol(1,''orient_coronal'')');
%      uimenu(menu_orient,'label','sagittal','callback', 'affichevol(1,''orient_sagittal'')');


%uimenu(menu_orient,'label','new dim','callback', ...
%       'affichevol(1,''new_dim_space'')');

%uimenu(menu_orient,'label','print info','callback', ...
%       'affichevol(1,''print_orient_info'')');


menu_view = uimenu(gcf,'label','view');
  uimenu(menu_view,'label','1views','Callback','affichevol(1,''singleV'')');
  uimenu(menu_view,'label','4views','Callback','affichevol(1,''multiV4'')');
  uimenu(menu_view,'label','check_reg','Callback','affichevol(1,''check_reg'')');
  uimenu(menu_view,'label','splatch','Callback','affichevol(1,''splatch'')');
  uimenu(menu_view,'label','project','Callback','affichevol(1,''project'')');

menu_load = uimenu(gcf,'label','load');
  uimenu(menu_load,'label','charge','Callback','affichevol(['''' ] )');
  uimenu(menu_load,'label','free_surf','Callback','affichevol(1,''load_free_s'')');

set(hdl.space.txt_nbvol,'visible','off');
set(hdl.space.txt_edit_nbvol,'visible','off');
set(hdl.space.time_slider,'visible','off');


hdl.view.mode=1;
hdl.view.max = max_axes;
hdl.view.max_ini = max_axes;

if minimum

    set(menuh1,'visible','off');
    set(menuh2,'visible','off');
    set(menuh4,'visible','off');
    set(menuh5,'visible','off');

    mmm = findobj('label','diff');    set(mmm,'visible','off')
    mmm = findobj('label','grill');    set(mmm,'visible','off')

    mmm = findobj('label','project');    set(mmm,'visible','off')
    mmm = findobj('label','splatch');    set(mmm,'visible','off')
    mmm = findobj('label','free_surf');    set(mmm,'visible','off')

    set(hdl.space.axes,'visible','off')

   name = fieldnames(hdl.tpos_hdl);
   for kk=1:length(name)
      set(getfield(hdl.tpos_hdl,name{kk}),'visible','off');
   end
   hdl.view.max_ini = [612 612];
   hdl.view.max     = [612 612];

end


%====================================
%initialisation image
 
for na = 1:length(hdl.axe)

  axes(hdl.axe(na))
   
  hdla.Im =imagesc(V(:,:,1),'EraseMode','none');
  %hdla.Im=0;
  set(gca,'ydir','normal','xdir','reverse')

  hdla.Num  = Num;
  hdla.Tpos = 0 ; 
  hdla.Bw   = 0 ;  hdla.Cont=0;
  hdla.BigT = 0;  hdla.grill = 0;
    
  hold on
  hdla.Clus = plot(0,0,'or','MarkerSize',4,'eraseMode','none');

  maxPos = 28;
  Mark = ['or';'og';'ob';'om';...
           'xr';'xg';'xb';'xm';...
	   'vr';'vg';'vb';'vm';...
	   '^r';'^g';'^b';'^m';...
	   '<r';'<g';'<b';'<m';...
	   '>r';'>g';'>b';'>m';...
	   'hr';'hg';'hb';'hm'];
 
  for k =1:maxPos
    MPoshdl(k) = plot(-1,-1,Mark(k,:),'erasemode','none','markersize',4);
  end

  hdla.MPoshdl = MPoshdl;

  hdla.cur_pos = get(gca,'Position');
  set(gca,'UserData',hdla);

end

axes(hdl.axe(1))   
for na = 2:length(hdl.axe)
  set(hdl.axe(na),'Position',[1 1 1 1],'visible','off')
end


if minimum

   dec = 50;
   for na = 1:length(hdl.axe)
     hddl = get(hdl.axe(na),'UserData');
     a_pos = hddl.cur_pos;
     if na==3 , a_pos(2) = a_pos(2) + dec; end
     if na==4 , a_pos(2) = a_pos(2) + dec; end
     hddl.cur_pos = a_pos;

     set(hdl.axe(na),'UserData',hddl)
   end
end

watchoff(oldFigNumber);
figure(figNum);
set(figNum,'Visible','on','tag','affichevol','UserData',hdl);