

%%%%%%%%%%   UIMENU    %%%%%%%%%%%%
h0 = hdl.figNum;

menu2 = findobj(h0,'label','graph')
% = uimenu(h0,'Label','graph');
%uimenu(menu2,'Label','zoom','Callback','zoom');
uimenu(menu2,'Label','y log scale','Callback','set(gca,''yscale'',''log'')' );
%uimenu(menu2,'label','Print','Callback','plotmoy(''print'')');

%menu3 = uimenu(h0,'label','charge');
%uimenu(menu3,'label','Big','Callback','plotmoy(''chargeBig'')');
%uimenu(menu3,'label','Big2d','Callback','plotmoy(''chargeBig2d'')');

menu3 = uimenu(h0,'label','Exam');
uimenu(menu3,'label','series global','Callback','plotmoy(''global_series'')');
uimenu(menu3,'label','series Paradigm','Callback','plotmoy(''paradigm'')');
uimenu(menu3,'label','series time','Callback','plotmoy(''time_series'')');
uimenu(menu3,'label','size','Callback','plotmoy(''size_series'')');

menu3 = uimenu(h0,'label','Result');
uimenu(menu3,'label','model','Callback','plotmoy(''see_model'')');
uimenu(menu3,'label','vol hist','Callback','plotmoy(''see_vol_hist'')');
uimenu(menu3,'label','res glob','Callback','plotmoy(''see_global'')');
uimenu(menu3,'label','see onset','Callback','plotmoy(''see_onset'')');


%%%%%%%%%%   axes    %%%%%%%%%%%%


%hdl_p.frame = uicontrol('Parent',h0, ...
%	'Units','normalized', ...
%	'BackgroundColor',[0.45 0.45 0.45], ...
%	'Interruptible','off', ...
%	'ListboxTop',0, ...
%   'Position',[0.01 0.0 0.60 0.13], ...
%	'Style','frame', ...
%	'Tag','FrameEdit');
%   [left bottom width height]

%%%%%%%%%%   UICONTROL   Liste  CHARGE  %%%%%%%%%%%%

hdl_p.exam = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotmoy(''set_exam'')', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.02 0.07 0.082 0.025], ...
	'String',{'nop'}, ...
	'Style','popupmenu', ...
	'Tag','exam', ...
	'Value',1);

%Methode
hdl_p.serie = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotmoy(''set_serie'')', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.02 0.035 0.082 0.025], ...
	'String',{'nop'}, ...
	'Style','popupmenu', ...
	'Tag','MethodPop', ...
	'Value',1);

hdl_p.result = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotmoy(''set_result'')', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.02 0.001 0.082 0.025], ...
	'String',{'nop'}, ...
	'Style','popupmenu', ...
	'Tag','MethodPop', ...
	'Value',1);


 hdl_p.data_type = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotmoy(''gui_change_data_type'')', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.11 0.07 0.082 0.025], ...
	'String',{'mean','raw','beta'}, ...
	'Style','popupmenu', ...
	'Tag','plotmoy_show_type', ...
	'Value',1);

%Methode
hdl_p.roi_list = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotmoy(''roi_list'')', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.11 0.035 0.082 0.025], ...
	'String','1', ...
	'Style','popupmenu', ...
	'Tag','MethodPop', ...
	'Value',1);
 
hdl_p.tempo = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotmoy(''set_tempo'')', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.2 0.07 0.082 0.025], ...
	'String',{'Tempo','MoyCond','spectre'}, ...
	'Style','popupmenu', ...
	'Tag','MethodPop', ...
	'Value',1);

hdl_p.scale = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotmoy(''scale'')', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.2 0.035 0.082 0.025], ...
	'String',{'Absol','mean scale','mean shift'}, ...
	'Style','popupmenu', ...
	'Tag','MethodPop', ...
	'Value',1);

%%%%%%%% uicontrol EDIT bouton %%%%%%%%%%%%%

hdl_p.dim1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','plotmoy(''verifedit'')', ...
	'HorizontalAlignment','right', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.3 0.065 0.09 0.03], ...
	'String','1:10', ...
	'Style','edit', ...
	'Tag','space');

hdl_p.slider = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','plotmoy(''slide'')', ...
	'ListboxTop',0, ...
	'Position',[0.3 0.035 0.11 0.025], ...
	'Style','slider', ...
	'Tag','Slider1');


hdl_p.checkhold = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.42 0.07 0.02 0.025], ...
	'Style','checkbox', ...
        'TooltipString','hold on',...	  
	'Tag','Checkhold');

hdl_p.col = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.42 0.035 0.02 0.025], ...
	'Style','checkbox', ...
        'TooltipString','change color',...			  
	'Tag','Checkbox2');


%%%Start stop pause reset
hdl_p.cine = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotmoy(''cine'')', ...
	'ListboxTop',0, ...
	'Position',[0.3 0.001 0.045 0.025], ...
        'TooltipString','Start cine loop',...
	'String','Start', ...
	'Tag','apply');

hdl_p.undo = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotmoy(''undo'')', ...
	'ListboxTop',0, ...
	'Position',[0.35 0.001 0.04 0.025], ...
	'String','undo', ...
	'Tag','stop');

hdl_p.editPause = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.4  0.001 0.04 0.025], ...
        'TooltipString','time pause for cine loop',...
	'String','0', ...
	'Style','edit', ...
   'Tag','editPause');


hdl_p.info = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1],...
	'ListboxTop',1, ...
	'HorizontalAlignment','left',...
	'Position',[0.63 0.001 0.3 0.1], ...
	'String',{'info'}, ...
	'Style','listbox', ...
	'Tag','info');

hdl_p.applyfilter = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Callback','plotmoy(''initFilter'')', ...
	'Position',[0.55 0.065 0.02 0.025], ...
	'Style','checkbox', ...
        'TooltipString','Apply temporal filter',...	  
	'Tag','applyfilter');


hdl_p.HP = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','plotmoy(''initFilter'')', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.5 0.065 0.05 0.025], ...
	'String','64', ...
	'Style','edit', ...
        'TooltipString','High pass filter',...	  
	'Tag','space');
 
hdl_p.LP = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','plotmoy(''initFilter'')', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[0.57 0.065 0.05 0.025], ...
	'String','4', ...
	'Style','edit', ...
        'TooltipString','Low pass filter',...	  
	'Tag','space');






