Description of mars_blob2roi
Home > marsbar > mars_blob2roi.m
mars_blob2roi
PURPOSE
saves ROI for cluster in xSPM structure, containing point pt
SYNOPSIS
function mars_blob2roi(xSPM, pt)
DESCRIPTION
 saves ROI for cluster in xSPM structure, containing point pt
 FORMAT mars_blob2roi(xSPM, pt)
 Input
 xSPM         - SPM results structure with needed fields
                  title
                  XYZ   - voxel coordinates of activated points
                  Z     - statistic values for activated points
                  M     - 4x4 matrix from voxels to mm
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
maroi_pointlist maroi_pointlist - class constructor
marsbar Startup, callback and utility routine for Marsbar
This function is called by:
mars_blob_ui Displays SPM results, and ROI menu in SPM input window
mars_blob_ui Displays SPM results, and ROI menu in SPM input window
mars_blob_ui Displays SPM results, and ROI menu in SPM input window
SOURCE CODE
function mars_blob2roi(xSPM, pt)
% saves ROI for cluster in xSPM structure, containing point pt
% FORMAT mars_blob2roi(xSPM, pt)
%
% Input
% xSPM         - SPM results structure with needed fields
%                  title
%                  XYZ   - voxel coordinates of activated points
%                  Z     - statistic values for activated points
%                  M     - 4x4 matrix from voxels to mm
%
% $Id$
if nargin < 1
  error('Need SPM structure');
end
if nargin < 2
  error('Need point to identify cluster');
end
vx_i = spm_XYZreg('findxyz', pt, xSPM.XYZmm);
if isempty(vx_i)
  msgbox('No activated voxel at this location');
  return
end
Clusters = spm_clusters(xSPM.XYZ);
cXYZ = xSPM.XYZmm(:, Clusters==Clusters(vx_i));
if isempty(cXYZ), return, end
d = sprintf('%s cluster at [%0.1f %0.1f %0.1f]', xSPM.title, pt);
l = sprintf('%s_%0.0f_%0.0f_%0.0f', xSPM.title, pt);
o = maroi_pointlist(struct('XYZ',cXYZ, 'mat', xSPM.M, ...
               'label', l, 'descrip', d));
marsbar('saveroi', o);