Description of mars_get_option
Home > marsbar > mars_get_option.m
mars_get_option
PURPOSE
Get option subfield as named by ``varargin``.
SYNOPSIS
function optval = mars_get_option(varargin)
DESCRIPTION
 Get option subfield as named by ``varargin``.
 FORMAT optval = mars_get_option(varargin)
 Tries to get base default if option is not set.  Returns empty matrix if
 there is no information for this option (for example, if the option fields
 were mis-spelled).
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
mars_options options utility routines
mars_struct multifunction function for manipulating structures
This function is called by:
mardo mardo - class constructor for MarsBaR design object
mars_arm_call services callbacks from marmoire object set functions
SOURCE CODE
function optval = mars_get_option(varargin)
% Get option subfield as named by ``varargin``.
%
% FORMAT optval = mars_get_option(varargin)
%
% Tries to get base default if option is not set.  Returns empty matrix if
% there is no information for this option (for example, if the option fields
% were mis-spelled).
mars = mars_struct('getifthere', spm('getglobal','MARS'), 'OPTIONS');
if isempty(mars)
  mars = mars_options('basedefaults');
end
optval = mars_struct('getifthere', mars, varargin{:});