Description of marsbar
Home > marsbar > marsbar.m
marsbar
PURPOSE
Startup, callback and utility routine for Marsbar
SYNOPSIS
function varargout=marsbar(varargin)
DESCRIPTION
 Startup, callback and utility routine for Marsbar
 MarsBaR: Marseille Boite a Regions d'interet
          Marseille Region of Interest Toolbox
 MarsBaR (the collection of files listed by contents.m) is copyright under
 the GNU general public license.  Please see mars_licence.man for details.
 Marsbar written and copyright claimed by
 Jean-Luc Anton, Matthew Brett, Jean-Baptiste Poline, Romain Valabregue
 Portions of the code rely heavily on (or are copied from) SPM
 (http://www.fil.ion.ucl.ac.uk/spm), which is also released under the GNU
 public licence.  Many thanks the SPM authors: (John Ashburner, Karl Friston,
 Andrew Holmes et al, and of course our own Jean-Baptiste).
 This software is MarsBaRWare. It is written in the hope that it is
 helpful; if you find it so, please let us know by sending a Mars bar to:
 The Jean-Luc confectionery collection, Centre IRMf, CHU La Timone, 264,
 Rue Saint Pierre 13385 Marseille Cedex 05, France
 If you find that it actively hinders your work, do send an
 elderly sardine to the same address.
 Please visit our friends at The Visible Mars Bar project:
 http://totl.net/VisibleMars
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
add_contrasts method to add contrast definitions to design
cd_images method for changing path to image files in design
descrip method gets cell string description of design
event_fitted method to compute fitted event time course
event_fitted_fir method to compute fitted event time courses using FIR
event_signal method to compute % signal change from fMRI events
event_types method to get / set event types for design
event_types_named method returns event types structures for events with same names
get_contrasts method to get contrasts from design object
get_data method to get data from design object
has_contrasts method returns 1 if design has contrasts
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images, NaN if not known
has_whitener returns 1 if design has whitening filter
image_names method returning image file names for design
is_fmri method returns 1 if this is an fmri design
is_valid returns 1 if object contains valid SPM/MarsBaR design
isempty overloaded isempty method for mardo object
isfield method to overload isfield for mardo objects
mardo mardo - class constructor for MarsBaR design object
prefix_images method for adding or removing prefix from file names in design
refresh_contrasts method to refresh contrasts to match design
residuals method returns residuals from model
savestruct saves data in def_struct as variables in .mat file
stat_table gets Mars statistics and creates statistic table as cell array
type returns SPM version string corresponding to design type
ui_event_types ui method for selection / editing of event types
ui_ft_design_data method plots FT of design and data to graphics window
ui_get_contrasts SPM contrast UI, wrapped for MarsBaR
add_trial_f method to add trial-specific F contrasts
apply_filter applies filter in design to data
bf_dt method returns length of time bin for basis functions
block_rows returns cell array of rows for each (subject/session) block
can_mars_estimate method returns 1 if design can be estimated in MarsBaR
estimate estimate method - estimates GLM for SPM2 model
event_onsets method gets onsets and durations for event/session
fill fills missing entries from SPM FMRI design matrix
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images
has_whitener returns 1 if design has whitening filter
mars_spm_graph Graphical display of adjusted data
savestruct saves data in def_struct into .mat file with variable name SPM
tr method returns TR in seconds, or empty if not available
type returns SPM version string corresponding to design type
ui_build method to create / fill design via GUI
ui_report method for SPM2 design reporting
estimate estimate method - estimates GLM for SPM2 model
fill fills missing entries from SPM FMRI design matrix
type returns SPM version string corresponding to design type
ui_build method to create / fill design via GUI
add_trial_f method to add trial-specific F contrasts
apply_filter applies filter in design to data
bf_dt method returns length of time bin for basis functions
block_rows returns cell array of rows for each (subject/session) block
can_mars_estimate method returns 1 if design can be estimated in MarsBaR
estimate estimate method - estimates GLM for SPM99 model
event_onsets method gets (estimated) onsets and durations for event/session
fill fills missing entries from SPM FMRI design matrix
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images
mars_spm_graph Graphical display of adjusted data
tr method returns TR in seconds, or empty if not available
type returns SPM version string corresponding to design type
ui_build method to create / fill design via GUI
ui_report mathod for SPM99 design reporting
add_if_absent Adds item only if not already present
marmoire marmoire - class constructor for marmoire container type
descrip name - returns / sets name value for object
flip_lr flips ROI left / right
get_marsy gets data in ROIs from images
has_space has_space method - returns true if object has a native space
label label - returns / sets label value for object
maroi maroi - class constructor for umbrella ROI object
save_as_image method save_as_image - saves ROI as image
saveroi saveroi method - checks fname, sets source field, saves object
source source - returns / sets source value for object
times overloaded times function
volume volume method - returns volume of ROI in mm
flip_lr flips ROI left / right
is_empty_roi returns 1 if ROI contains no volume
volume volume method - returns volume of ROI in mm
flip_lr flips ROI left / right
vol vol - returns / sets image vol for object
flip_lr flips ROI left / right
is_empty_roi is_empty_roi - returns true if ROI contains no volume
flip_lr flips ROI left / right
is_empty_roi is_empty_roi - returns true if ROI contains no volume
has_space has_space method - returns true if object has a native space
flip_lr flips ROI left / right
is_empty_roi is_empty_roi - returns true if ROI contains no volume
volume volume method - returns volume of ROI in mm
mars_space mars_space - class constructor for space defining object
block_rows gets/sets cell array of rows for each (subject/session) block
is_valid method returns 1 if object contains valid data
join joins marsy objects into one object
marsy Class constructor for marsy: the MarsBaR data object
n_regions get number of regions
region_data method gets or sets data for region(s) as cell array
region_name method gets or sets data for region name
savestruct saves data in y_struct as variables in .mat file
split method splits regions in object into separate objects
sumfunc method to get or set sumfunc
summary_data method to get summary data, maybe set sumfunc
summary_descrip get/set method for summary data description
ui_plot method plots data in various formats
mars_arm wrapper function for MarsBaR marmoire object
mars_build_roi builds ROIs via the SPM GUI
mars_image_scaling get image scaling data for images, maybe via SPM design
mars_img2rois creates ROIs from cluster image or image containing ROIs defined by unique nos
mars_options options utility routines
mars_rois2img creates cluster or number labelled ROI image from ROIs
mars_struct multifunction function for manipulating structures
mars_uifile wrapper for matlab uiputfile/getfile; to resolve version differences
mars_utils collection of useful utility functions for MarsBaR etc
marsbar Startup, callback and utility routine for Marsbar
savestruct saves data in structure as variables in .mat file
mars_veropts returns SPM version specific parameters
mars_veropts returns SPM version specific parameters
spm_get compatibility function to allow spm_get calls with SPM5
mars_veropts returns SPM version specific parameters
This function is called by:
mardo mardo - class constructor for MarsBaR design object
mardo_2 class constructor for SPM2 MarsBaR design object
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_spm_ui MarsBaR: setting up the general linear model for independent data
mardo_5 class constructor for SPM5 MarsBaR design object
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_spm_ui MarsBaR: Setting up the general linear model for independent data
mardo_99 class constructor for SPM99 MarsBaR design object
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_spm_ui MarsBaR: setting up the general linear model for independent data
marmoire marmoire - class constructor for marmoire container type
maroi maroi - class constructor for umbrella ROI object
marsy Class constructor for marsy: the MarsBaR data object
run_preprocess Run smoothing and SPM analysis for MarsBaR ER sample data
run_tutorial MarsBaR batch script to show off MarsBaR batching
mars_blob2roi saves ROI for cluster in xSPM structure, containing point pt
mars_options options utility routines
marsbar Startup, callback and utility routine for Marsbar
SUBFUNCTIONS
function sum_func = sf_get_sumfunc(sum_func)
function btn = sf_prev_save(obj_name)
SOURCE CODE
function varargout=marsbar(varargin)
% Startup, callback and utility routine for Marsbar
%
% MarsBaR: Marseille Boite a Regions d'interet
%          Marseille Region of Interest Toolbox
%
% MarsBaR (the collection of files listed by contents.m) is copyright under
% the GNU general public license.  Please see mars_licence.man for details.
%
% Marsbar written and copyright claimed by
% Jean-Luc Anton, Matthew Brett, Jean-Baptiste Poline, Romain Valabregue
%
% Portions of the code rely heavily on (or are copied from) SPM
% (http://www.fil.ion.ucl.ac.uk/spm), which is also released under the GNU
% public licence.  Many thanks the SPM authors: (John Ashburner, Karl Friston,
% Andrew Holmes et al, and of course our own Jean-Baptiste).
%
% This software is MarsBaRWare. It is written in the hope that it is
% helpful; if you find it so, please let us know by sending a Mars bar to:
% The Jean-Luc confectionery collection, Centre IRMf, CHU La Timone, 264,
% Rue Saint Pierre 13385 Marseille Cedex 05, France
%
% If you find that it actively hinders your work, do send an
% elderly sardine to the same address.
%
% Please visit our friends at The Visible Mars Bar project:
% http://totl.net/VisibleMars
%
% $Id$
% Programmer's help
% -----------------
% For a list of the functions implemented here, try
% grep "^case " marsbar.m
% Marsbar version
MBver = '0.45';  % First Github release
% Various working variables in global variable structure
global MARS;
%-Format arguments
%-----------------------------------------------------------------------
if nargin == 0, Action='Startup'; else, Action = varargin{1}; end
%=======================================================================
switch lower(Action), case 'startup'                     %-Start marsbar
%=======================================================================
%-Turn on warning messages for debugging
warning backtrace
% splash screen once per session
splashf = ~marsbar('is_started');
% promote spm directory to top of path, read defaults
marsbar('on');
% Workaround for bizarre linux uigetfile problem: see
% http://www.mathworks.com/support/bugreports/details.html?rp=259878
% (or search Mathworks support for uigetfile linux
mlv = version; mlv = str2num(mlv(1:3));
if mlv >= 7 && strcmp(computer, 'GLNX86')
  if usejava('jvm')
    setappdata(0,'UseNativeSystemDialogs',false)
  else
    warning(['Matlab 7, linux, no java, please see FAQ for '...
         'information on problems with file selection dialogs']);
  end
end
%-Open startup window, set window defaults
%-----------------------------------------------------------------------
S = get(0,'ScreenSize');
if all(S==1), error('Can''t open any graphics windows...'), end
PF = spm_platform('fonts');
% Splash screen
%------------------------------------------
if splashf
  marsbar('splash');
end
%-Draw marsbar window
%-----------------------------------------------------------------------
Fmenu = marsbar('CreateMenuWin','off');
%-Reveal windows
%-----------------------------------------------------------------------
set([Fmenu],'Visible','on')
%=======================================================================
case 'on'                                           %-Initialise MarsBaR
%=======================================================================
% promote spm replacement directory
% remove incorrect spm replacement directories
mbpath = fileparts(which('marsbar.m'));
spmV = mars_utils('spm_version');
m_spm_paths = {'spm99', 'spm2', 'spm5'};
v_path = lower(spmV);
% spm8 is effectively identical to spm5 for marsbar
switch v_path
case {'spm8', 'spm12b', 'spm12'}
    v_path = 'spm5';
end
w_s = warning;
warning off
for p = m_spm_paths(~ismember(m_spm_paths, v_path))
  rmpath(fullfile(mbpath, char(p)))
end
warning(w_s)
MARS.ADDPATHS = {fullfile(mbpath, v_path)};
addpath(MARS.ADDPATHS{:}, '-begin');
fprintf('MarsBaR analysis functions prepended to path\n');
% check SPM defaults are loaded
mars_veropts('defaults');
% set up the ARMOIRE stuff
% see marmoire help for details
if isfield(MARS, 'ARMOIRE')
  o = MARS.ARMOIRE;
else
  o = marmoire;
end
spm_design_filter = mars_veropts('design_filter_spec');
filter_specs  = {[spm_design_filter(1,:);...
          {'*_mdes.mat','MarsBaR: *_mdes.mat'}; ...
          spm_design_filter(2:end,:)], ...
         {'*_mdata.mat','MarsBaR data file (*_mdata.mat)'},...
         {'*_mres.mat', 'MarsBaR results (*_mres.mat)'}};
o = add_if_absent(o, 'def_design', ...
          struct('default_file_name', 'untitled_mdes.mat',...
             'filter_spec', {filter_specs{1}},...
             'title', 'Default design',...
             'set_action','mars_arm_call(''set_design'',o,item,old_o)'));
o = add_if_absent(o, 'roi_data',...
          struct('default_file_name', 'untitled_mdata.mat',...
             'filter_spec', {filter_specs{2}},...
             'title', 'ROI data',...
             'set_action','mars_arm_call(''set_data'',o,item,old_o)'));
o = add_if_absent(o, 'est_design',...
          struct('default_file_name', 'untitled_mres.mat',...
             'filter_spec', {filter_specs{3}},...
             'title', 'MarsBaR estimated design',...
             'set_action', 'mars_arm_call(''set_results'',o,item,old_o)'));
MARS.ARMOIRE = o;
% and workspace
if ~isfield(MARS, 'WORKSPACE'), MARS.WORKSPACE = []; end
% read any necessary defaults
if ~mars_struct('isthere', MARS, 'OPTIONS')
  loadf = 1;
  MARS.OPTIONS = [];
else
  loadf = 0;
end
[mbdefs sourcestr] = mars_options('Defaults');
MARS.OPTIONS = mars_options('fill',MARS.OPTIONS, mbdefs);
mars_options('put');
if loadf
  fprintf('Loaded MarsBaR defaults from %s\n',sourcestr);
end
% Add very very odd fix for maroi object path problem
% and matlab 7.1 (at least)
% Don't ask why this is needed - I don't know.
maroi;
%=======================================================================
case 'off'                                              %-Unload MarsBaR
%=======================================================================
% res = marsbar('Off')
%-----------------------------------------------------------------------
varargout = {0};
% leave if no signs of marsbar
if ~marsbar('is_started'), return, end
% save outstanding information
btn = mars_arm('save_ui', 'all', struct('ync', 1, 'no_no_save', 1));
if btn == -1, varargout = {-1}; return, end % cancel
% remove marsbar added directories
rmpath(MARS.ADDPATHS{:});
fprintf('MarsBaR analysis functions removed from path\n');
%=======================================================================
case 'quit'                                        %-Quit MarsBaR window
%=======================================================================
% marsbar('Quit')
%-----------------------------------------------------------------------
% do path stuff, save any pending changes
if marsbar('off') == -1, return, end % check for cancel
% leave if no signs of MARSBAR
if ~marsbar('is_started'), return, end
%-Close any existing 'MarsBaR' 'Tag'ged windows
delete(spm_figure('FindWin','MarsBaR'))
fprintf('Au revoir...\n\n')
%=======================================================================
case 'is_started'        %-returns 1 if MarsBaR GUI has been initialized
%=======================================================================
% tf  = marsbar('is_started')
varargout = {~isempty(MARS)};
%=======================================================================
case 'cfgfile'                                  %-finds MarsBaR cfg file
%=======================================================================
% cfgfn  = marsbar('cfgfile')
cfgfile = 'marsbarcfg.mat';
varargout = {which(cfgfile), cfgfile};
%=======================================================================
case 'createmenuwin'                          %-Draw MarsBaR menu window
%=======================================================================
% Fmenu = marsbar('CreateMenuWin',Vis)
if nargin<2, Vis='on'; else, Vis=varargin{2}; end
%-Close any existing 'MarsBaR' 'Tag'ged windows
delete(spm_figure('FindWin','MarsBaR'))
% Version etc info
[MBver,MBc] = marsbar('Ver');
%-Get size and scalings and create Menu window
%-----------------------------------------------------------------------
WS   = spm('WinScale');                %-Window scaling factors
FS   = spm('FontSizes');            %-Scaled font sizes
PF   = spm_platform('fonts');            %-Font names (for this platform)
Rect = [50 600 300 275];               %-Raw size menu window rectangle
bno = 6; bgno = bno+1;
bgapr = 0.25;
bh = Rect(4) / (bno + bgno*bgapr);      % Button height
gh = bh * bgapr;                        % Button gap
by = fliplr(cumsum([0 ones(1, bno-1)*(bh+gh)])+gh);
bx = Rect(3)*0.1;
bw = Rect(3)*0.8;
Fmenu = figure('IntegerHandle','off',...
    'Name',sprintf('%s',MBc),...
    'NumberTitle','off',...
    'Tag','MarsBaR',...
    'Position',Rect.*WS,...
    'Resize','off',...
    'Color',[1 1 1]*.8,...
    'UserData',struct('MBver',MBver,'MBc',MBc),...
    'MenuBar','none',...
    'DefaultTextFontName',PF.helvetica,...
    'DefaultTextFontSize',FS(12),...
    'DefaultUicontrolFontName',PF.helvetica,...
    'DefaultUicontrolFontSize',FS(12),...
    'DefaultUicontrolInterruptible','on',...
    'Renderer','painters',...
    'Visible','off');
%-Objects with Callbacks - main MarsBaR routines
%=======================================================================
funcs = {'mars_display_roi(''display'');',...
     'mars_blob_ui;',...
     'marsbar(''buildroi'');',...
     'marsbar(''transform'');',...
     'marsbar(''import_rois'');',...
     'marsbar(''export_rois'');'};
uicontrol(Fmenu,'Style','PopUp',...
      'String',['ROI definition',...
            '|View...'...
            '|Get SPM cluster(s)...'...
            '|Build...',...
            '|Transform...',...
            '|Import...',...
            '|Export...'],...
      'Position',[bx by(1) bw bh].*WS,...
      'ToolTipString','Draw / build / combine ROIs...',...
      'CallBack','spm(''PopUpCB'',gcbo)',...
      'UserData',funcs);
% Design menu
fw_st = 'struct(''force'', 1, ''warn_empty'', 1)';
funcs = {...
    'marsbar(''make_design'', ''pet'');',...
    'marsbar(''make_design'', ''fmri'');',...
    'marsbar(''make_design'', ''basic'');',...
    'marsbar(''design_report'')',...
    'marsbar(''design_filter'')',...
    'marsbar(''add_images'')',...
    'marsbar(''edit_filter'')',...
    'marsbar(''check_images'')',...
    'marsbar(''list_images'')',...
    'marsbar(''ana_cd'')',...
    'marsbar(''ana_desmooth'')',...
    'marsbar(''def_from_est'')',...
    'marsbar(''set_def'')',...
    ['mars_arm(''save_ui'', ''def_design'', ' fw_st ');'],...
    'mars_arm(''show_summary'', ''def_design'')'};
uicontrol(Fmenu,'Style','PopUp',...
      'String',['Design...'...
            '|PET models',...
            '|FMRI models',...
            '|Basic models',...
            '|Explore',...
            '|Frequencies (event+data)',...
            '|Add images to FMRI design',...
            '|Add/edit filter for FMRI design',...
            '|Check image names in design',...
            '|List image names to console',...
            '|Change design path to images',...
            '|Convert to unsmoothed',...
            '|Set design from estimated',...
            '|Set design from file',...
            '|Save design to file',...
            '|Show default design summary'],...
      'Position',[bx by(2) bw bh].*WS,...
      'ToolTipString','Set/specify design...',...
      'CallBack','spm(''PopUpCB'',gcbo)',...
      'UserData',funcs);
% Data menu
funcs = {'marsbar(''extract_data'', ''default'');',...
     'marsbar(''extract_data'', ''full'');',...
     'marsbar(''set_defregion'');',...
     'marsbar(''plot_data'', ''raw'');',...
     'marsbar(''plot_data'', ''full'');',...
     'marsbar(''import_data'');',...
     'marsbar(''export_data'');',...
     'marsbar(''split_data'');',...
     'marsbar(''join_data'');',...
     'mars_arm(''set_ui'', ''roi_data'');',...
     ['mars_arm(''save_ui'', ''roi_data'', ' fw_st ');'],...
     'mars_arm(''show_summary'', ''roi_data'')'};
uicontrol(Fmenu,'Style','PopUp',...
      'String',['Data...'...
            '|Extract ROI data (default)',...
            '|Extract ROI data (full options)',...
            '|Default region...',...
            '|Plot data (simple)',...
            '|Plot data (full)',...
            '|Import data',...
            '|Export data',...
            '|Split regions into files',...
            '|Merge data files',...
            '|Set data from file',...
            '|Save data to file',...
            '|Show data summary'],...
      'Position',[bx by(3) bw bh].*WS,...
      'ToolTipString','Extract/set/save data...',...
      'CallBack','spm(''PopUpCB'',gcbo)',...
      'UserData',funcs);
% results menu
funcs = {...
    'marsbar(''estimate'');',...
    'marsbar(''merge_contrasts'');',...
    'marsbar(''refresh_contrasts'');',...
    'marsbar(''add_trial_f'');',...
    'marsbar(''set_defcon'');',...
    'marsbar(''set_defregion'');',...
    'marsbar(''plot_residuals'');',...
    'marsbar(''spm_graph'');',...
    'marsbar(''stat_table'');',...
    'marsbar(''signal_change'');',...
    'marsbar(''fitted_events'');',...
    'marsbar(''fir_events'');',...
    'marsbar(''add_events_by_name'');',...
    'marsbar(''set_results'');',...
    ['mars_arm(''save_ui'', ''est_design'', ' fw_st ');'],...
    'mars_arm(''show_summary'', ''est_design'')'};
uicontrol(Fmenu,'Style','PopUp',...
      'String',['Results...'...
            '|Estimate results',...
            '|Import contrasts',...
            '|Refresh F contrasts',...
            '|Add trial-specific F',...
            '|Default contrast...',...
            '|Default region...',...
            '|Plot residuals',...
            '|MarsBaR SPM graph',...
            '|Statistic table',...
            '|% signal change',...
            '|Fitted event time course',...
            '|FIR event time course',...
            '|Add event types by name',...
            '|Set results from file',...
            '|Save results to file',...
            '|Show estimated design summary'],...
      'Position',[bx by(4) bw bh].*WS,...
      'ToolTipString','Write/display contrasts...',...
      'CallBack','spm(''PopUpCB'',gcbo)',...
      'UserData',funcs);
% options menu
funcs = {['global MARS; '...
     'MARS.OPTIONS=mars_options(''edit'');mars_options(''put'');'],...
     ['global MARS; '...
      '[MARS.OPTIONS str]=mars_options(''defaults'');' ...
      'mars_options(''put''); '...
      'fprintf(''Defaults loaded from %s\n'', str)'],...
     ['global MARS; '...
      '[MARS.OPTIONS str]=mars_options(''basedefaults'');' ...
      'mars_options(''put''); '...
      'fprintf(''Defaults loaded from %s\n'', str)'],...
     ['global MARS; '...
      'MARS.OPTIONS=mars_options(''load'');mars_options(''put'');'],...
     'mars_options(''save'');'...
    };
uicontrol(Fmenu,'Style','PopUp',...
      'String',['Options...'...
            '|Edit options'...
            '|Restore defaults'...
            '|Base defaults',...
            '|Set options from file'...
            '|Save options to file'],...
      'Position',[bx by(5) bw bh].*WS,...
      'ToolTipString','Load/save/edit MarsBaR options',...
      'CallBack','spm(''PopUpCB'',gcbo)',...
      'UserData',funcs);
% quit button
uicontrol(Fmenu,'String','Quit',...
      'Position',[bx by(6) bw bh].*WS,...
      'ToolTipString','exit MarsBaR',...
      'ForeGroundColor','r',...
      'Interruptible','off',...
      'CallBack','marsbar(''Quit'')');
% Set quit action if MarsBaR window is closed
%-----------------------------------------------------------------------
set(Fmenu,'CloseRequestFcn','marsbar(''Quit'')')
set(Fmenu,'Visible',Vis)
varargout = {Fmenu};
%=======================================================================
case {'ver', 'version'}                         %-Return MarsBaR version
%=======================================================================
% [v [,banner]] = marsbar('Ver')
%-----------------------------------------------------------------------
varargout = {MBver, 'MarsBaR - Marseille ROI toolbox'};
%=======================================================================
case 'splash'                                       %-show splash screen
%=======================================================================
% marsbar('splash')
%-----------------------------------------------------------------------
% Shows splash screen
WS   = spm('WinScale');        %-Window scaling factors
[X,map] = imread('marsbar.jpg');
aspct = size(X,1) / size(X,2);
ww = 400;
srect = [200 300 ww ww*aspct] .* WS;   %-Scaled size splash rectangle
h = figure('visible','off',...
       'menubar','none',...
       'numbertitle','off',...
       'name','Welcome to MarsBaR',...
       'pos',srect);
im = image(X);
colormap(map);
ax = get(im, 'Parent');
axis off;
axis image;
axis tight;
set(ax,'plotboxaspectratiomode','manual',...
       'unit','pixels',...
       'pos',[0 0 srect(3:4)]);
set(h,'visible','on');
pause(3);
close(h);
%=======================================================================
case 'buildroi'                                     %-build and save ROI
%=======================================================================
% o = marsbar('buildroi')
%-----------------------------------------------------------------------
% build and save object
varargout = {[]};
o = mars_build_roi;
if ~isempty(o)
  varargout = {marsbar('saveroi', o)};
end
%=======================================================================
case 'transform'                                        %-transform ROIs
%=======================================================================
% marsbar('transform')
%-----------------------------------------------------------------------
marsbar('mars_menu', 'Transform ROI', 'Transform:', ...
    {{'combinerois'},{'flip_lr'}},...
    {'Combine ROIs','Flip L/R'});
%=======================================================================
case 'import_rois'                                       %- import ROIs!
%=======================================================================
% marsbar('import_rois')
%-----------------------------------------------------------------------
marsbar('mars_menu', 'Import ROIs', 'Import ROIs from:',...
    {{'img2rois','c'},...
     {'img2rois','i'}},...
    {'cluster image',...
     'number labelled ROI image'});
%=======================================================================
case 'export_rois'                                         %-export ROIs
%=======================================================================
% marsbar('export_rois')
%-----------------------------------------------------------------------
marsbar('mars_menu', 'Export ROI(s)', 'Export ROI(s) to:',...
    {{'roi_as_image'},...
     {'rois2img', 'c'},...
     {'rois2img', 'i'}},...
    {'image', 'cluster image',...
    'number labelled ROI image'});
%=======================================================================
case 'img2rois'                                       %-import ROI image
%=======================================================================
%  marsbar('img2rois', roi_type)
%-----------------------------------------------------------------------
if nargin < 2
  roi_type = 'c'; % default is cluster image
else
  roi_type = varargin{2};
end
mars_img2rois('','','',roi_type);
%=======================================================================
case 'rois2img'                                       %-export ROI image
%=======================================================================
%  marsbar('roi2img', roi_type)
%-----------------------------------------------------------------------
if nargin < 2
  roi_type = 'c'; % default is cluster image
else
  roi_type = varargin{2};
end
mars_rois2img('','','',roi_type);
%=======================================================================
case 'saveroi'                                                %-save ROI
%=======================================================================
% o = marsbar('saveroi', obj, flags)
%-----------------------------------------------------------------------
% flags will usually be empty, or one or more characters from
% 'n'   do not ask for label or description
% 'l'   use label to make filename, rather than source field
if nargin < 2 || isempty(varargin{2})
  return
end
if nargin < 3
  flags = '';
else
  flags = varargin{3};
end
if isempty(flags), flags = ' '; end
o = varargin{2};
varargout = {[]};
% Label, description
if ~any(flags=='n')
  d = spm_input('Description of ROI', '+1', 's', descrip(o));
  o = descrip(o,d);
  l = spm_input('Label for ROI', '+1', 's', label(o));
  o = label(o,l);
end
fn = source(o);
if isempty(fn) || any(flags=='l')
  fn = maroi('filename', mars_utils('str2fname', label(o)));
end
f_f = ['*' maroi('classdata', 'fileend')];
[f p] = mars_uifile('put', ...
            {f_f, ['ROI files (' f_f ')']},...
            'File name for ROI', fn);
if any(f~=0)
  roi_fname = maroi('filename', fullfile(p, f));
  try
    varargout = {saveroi(o, roi_fname)};
  catch
    warning([lasterr ' Error saving ROI to file ' roi_fname])
  end
end
%=======================================================================
case 'combinerois'                                        %-combine ROIs
%=======================================================================
% marsbar('combinerois')
%-----------------------------------------------------------------------
roilist = spm_get(Inf,['*' maroi('classdata', 'fileend')], ...
          'Select ROI(s) to combine');
if isempty(roilist)
  return
end
roilist = maroi('load_cell', roilist);
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Combine ROIs');
spm_input('(r1 & r2) & ~r3',1,'d','Example function:');
func = spm_input('Function to combine ROIs', '+1', 's', '');
if isempty(func), retnrn, end
for i = 1:length(roilist)
  eval(sprintf('r%d = roilist{%d};', i, i));
end
try
  eval(['o=' func ';']);
catch
  warning(['Hmm, probem with function ' func ': ' lasterr]);
  return
end
if isempty(o)
  warning('Empty object resulted');
  return
end
if is_empty_roi(o)
  warning('No volume resulted for ROI');
  return
end
% save ROI
if isa(o, 'maroi')
  o = label(o, func);
  o = marsbar('saveroi', o);
  if ~isempty(o)
    fprintf('\nSaved ROI as %s\n', source(o));
  end
else
  warning(sprintf('\nNo ROI resulted from function %s...\n', func));
end
%=======================================================================
case 'flip_lr'                                          %-flip roi L<->R
%=======================================================================
% marsbar('flip_lr')
%-----------------------------------------------------------------------
roilist = spm_get([0 1],['*' maroi('classdata', 'fileend')],...
          'Select ROI to flip L/R');
if isempty(roilist)
  return
end
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Flip ROI L<->R');
o = maroi('load', roilist);
o = flip_lr(o);
% save ROI
o = marsbar('saveroi', o, 'l');
fprintf('\nSaved ROI as %s\n', source(o));
%=======================================================================
case 'show_volume'                  %- shows ROI volume in mm to console
%=======================================================================
% marsbar('show_volume')
%-----------------------------------------------------------------------
roi_names = spm_get([0 Inf], '*roi.mat', 'Select ROIs tp get volume');
if isempty(roi_names),return,end
rois = maroi('load_cell', roi_names);
for i = 1:size(rois, 1)
  fprintf('Volume of %s: %6.2f\n', source(rois{i}), volume(rois{i}));
end
return
%=======================================================================
case 'roi_as_image'                               %- writes ROI as image
%=======================================================================
% marsbar('roi_as_image')
%-----------------------------------------------------------------------
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Write ROI to image');
roi = spm_get([0 1], '*roi.mat', 'Select ROI to write');
if isempty(roi),return,end
[pn fn ext] = fileparts(roi);
roi = maroi('load', roi);
% space of object
spopts = {'spacebase','image'};
splabs =  {'Base space for ROIs','From image'};
if has_space(roi)
  spopts = {spopts{:} 'native'};
  splabs = {splabs{:} 'ROI native space'};
end
spo = spm_input('Space for ROI image', '+1', 'm',splabs,...
        spopts, 1);
switch char(spo)
 case 'spacebase'
   sp = maroi('classdata', 'spacebase');
 case 'image'
  img = spm_get([0 1], mars_veropts('get_img_ext'), 'Image defining space');
  if isempty(img),return,end
  sp = mars_space(img);
 case 'native'
  sp = [];
end
% remove ROI file ending
gend = maroi('classdata', 'fileend');
lg = length(gend);
f2 = [fn ext];
if length(f2)>=lg && strcmp(gend, [f2(end - lg +1 : end)])
  f2 = f2(1:end-lg);
else
  f2 = fn;
end
fname = mars_utils('get_img_name', f2);
if isempty(fname), return, end
save_as_image(roi, fname, sp);
fprintf('Saved ROI as %s\n',fname);
%=======================================================================
case 'attach_image'                          %- attaches image to ROI(s)
%=======================================================================
% marsbar('attach_image' [,img [,roilist]])
%-----------------------------------------------------------------------
if nargin < 2
  V = spm_get([0 1], mars_veropts('get_img_ext'), 'Image to attach');
  if isempty(V), return, end
else
  V = varargin{1};
end
if nargin < 3
  rois = spm_get([0 Inf], ['*' maroi('classdata', 'fileend')], ...
         'Select ROIs to attach image to');
  if isempty(rois), return, end
else
  rois = varargin{2};
end
if ischar(V), V = spm_vol(V); end
for i = 1:size(rois, 1)
  n = deblank(rois(i,:));
  try
    r = maroi('load', n);
  catch
    r = []
    if ~strmatch(lasterr, 'Cant map image file.')
      error(lasterr);
    end
  end
  if isempty(r)
    continue
  end
  if ~isa(r, 'maroi_image')
    fprintf('ROI %s is not an image ROI - ignored\n', n);
    continue
  end
  r = vol(r, V);
  saveroi(r, n);
  fprintf('Saved ROI %s, attached to image %s\n',...
      n, V.fname)
end
return
%=======================================================================
case 'make_design'                       %-runs design creation routines
%=======================================================================
% marsbar('make_design', des_type)
%-----------------------------------------------------------------------
if nargin < 2
  des_type = 'basic';
else
  des_type = varargin{2};
end
if sf_prev_save('def_design') == -1, return, end
D = ui_build(mars_veropts('default_design'), des_type);
mars_arm('set', 'def_design', D);
marsbar('design_report');
%=======================================================================
case 'list_images'                     %-lists image files in SPM design
%=======================================================================
% marsbar('list_images')
%-----------------------------------------------------------------------
marsD = mars_arm('get', 'def_design');
if isempty(marsD), return, end;
if has_images(marsD)
  P = image_names(marsD);
  strvcat(P{:})
else
  disp('Design does not contain images');
end
%=======================================================================
case 'check_images'                   %-checks image files in SPM design
%=======================================================================
% marsbar('check_images')
%-----------------------------------------------------------------------
marsD = mars_arm('get', 'def_design');
if isempty(marsD), return, end;
if ~has_images(marsD)
  disp('Design does not contain images');
  return
end
P = image_names(marsD);
P = strvcat(P{:});
ok_f = 1;
for i = 1:size(P, 1)
  fname = deblank(P(i,:));
  if ~exist(fname, 'file');
    fprintf('Image %d: %s does not exist\n', i, fname);
    ok_f = 0;
  end
end
if ok_f
  disp('All images in design appear to exist');
end
%=======================================================================
case 'ana_cd'                      %-changes path to files in SPM design
%=======================================================================
% marsbar('ana_cd')
%-----------------------------------------------------------------------
marsD = mars_arm('get', 'def_design');
if isempty(marsD), return, end;
% Setup input window
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Change image path in design', 0);
% root path shown in output window
P = image_names(marsD);
P = strvcat(P{:});
root_names = spm_str_manip(P, 'H');
spm_input(deblank(root_names(1,:)),1,'d','Common path is:');
% new root
newpath = spm_get([-1 0], '', 'New directory root for files');
if isempty(newpath), return, end
% do
marsD = cd_images(marsD, newpath);
mars_arm('set', 'def_design', marsD);
%=======================================================================
case 'ana_desmooth'           %-makes new SPM design for unsmoothed data
%=======================================================================
% marsbar('ana_desmooth')
%-----------------------------------------------------------------------
marsD = mars_arm('get', 'def_design');
if isempty(marsD), return, end;
marsD = prefix_images(marsD, 'remove', 's');
mars_arm('set', 'def_design', marsD);
disp('Done');
%=======================================================================
case 'add_images'                            %-add images to FMRI design
%=======================================================================
% marsbar('add_images')
%-----------------------------------------------------------------------
marsD = mars_arm('get', 'def_design');
if isempty(marsD), return, end
if ~is_fmri(marsD), return, end
marsD = fill(marsD, {'images'});
mars_arm('update', 'def_design', marsD);
mars_arm('set_param', 'def_design', 'file_name', '');
mars_arm('show_summary', 'def_design');
%=======================================================================
case 'edit_filter'                   %-add / edit filter for FMRI design
%=======================================================================
% marsbar('edit_filter')
%-----------------------------------------------------------------------
marsD = mars_arm('get', 'def_design');
if isempty(marsD), return, end
if ~is_fmri(marsD), return, end
tmp = {'filter'};
if ~strcmp(type(marsD), 'SPM99'), tmp = [tmp {'autocorr'}]; end
marsD = fill(marsD, tmp);
mars_arm('update', 'def_design', marsD);
mars_arm('set_param', 'def_design', 'file_name', '');
mars_arm('show_summary', 'def_design');
%=======================================================================
case 'def_from_est'          %-sets default design from estimated design
%=======================================================================
% marsbar('def_from_est')
%-----------------------------------------------------------------------
marsE = mars_arm('get', 'est_design');
if isempty(marsE), return, end;
errf = mars_arm('set', 'def_design', marsE);
if ~errf, marsbar('design_report'); end
%=======================================================================
case 'set_def'                           %-sets default design using GUI
%=======================================================================
% marsbar('set_def')
%-----------------------------------------------------------------------
if mars_arm('set_ui', 'def_design'), return, end
marsbar('design_report');
%=======================================================================
case 'design_report'                         %-does explore design thing
%=======================================================================
% marsbar('design_report')
%-----------------------------------------------------------------------
marsD = mars_arm('get', 'def_design');
if isempty(marsD), return, end;
spm('FnUIsetup','Explore design', 0);
fprintf('%-40s: ','Design reporting');
ui_report(marsD, 'DesMtx');
ui_report(marsD, 'DesRepUI');
fprintf('%30s\n','...done');
%=======================================================================
case 'design_filter'                      %-shows FFT of data and design
%=======================================================================
% marsbar('design_filter')
%-----------------------------------------------------------------------
marsD = mars_arm('get', 'def_design');
if isempty(marsD), return, end;
marsY = mars_arm('get', 'roi_data');
if isempty(marsY), return, end
% If the design and data didn't match, the design will have been cleared
if mars_arm('isempty', 'def_design')
  error('Need data and design with matching number of rows');
end
ui_ft_design_data(marsD, marsY);
%=======================================================================
case 'extract_data'                       % gets data maybe using design
%=======================================================================
% marsY = marsbar('extract_data'[, roi_list [, 'full'|'default']]);
if nargin < 2
  etype = 'default';
else
  etype = varargin{2};
end
if nargin < 3
  roi_list = '';
else
  roi_list = varargin{3};
end
varargout = {[]};
% Check for save of current data
if sf_prev_save('roi_data') == -1, return, end
if isempty(roi_list)
  roi_list = spm_get(Inf,'*roi.mat','Select ROI(s) to extract data for');
end
if isempty(roi_list), return, end
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Extract data', 0);
if strcmp(etype, 'default')
  marsD = mars_arm('get', 'def_design');
  if isempty(marsD), return, end;
  if ~has_images(marsD),
    marsD = fill(marsD, 'images');
    mars_arm('update', 'def_design', marsD);
  end
  VY = marsD;
  row = block_rows(marsD);
else  % full options extraction
  % question for design
  marsD = [];
  if spm_input('Use SPM design?', '+1', 'b', 'Yes|No', [1 0], 1)
    marsD = mars_arm('get', 'def_design');
    if ~has_images(marsD),
      marsD = fill(marsD, 'images');
      mars_arm('update', 'def_design', marsD);
    end
  end
  [VY row] = mars_image_scaling(marsD);
end
% Summary function
sumfunc = sf_get_sumfunc(MARS.OPTIONS.statistics.sumfunc);
% ROI names to objects
o = maroi('load_cell', roi_list);
% Do data extraction
marsY = get_marsy(o{:}, VY, sumfunc, 'v');
marsY = block_rows(marsY, row);
if ~n_regions(marsY)
  msgbox('No data returned','Data extraction', 'warn');
  return
end
% set into armoire, and display
mars_arm('set', 'roi_data', marsY);
mars_arm('show_summary', 'roi_data');
1000
1001 varargout = {marsY};
1002
1003 %=======================================================================
1004 case 'plot_data'                                       %- it plots data!
1005 %=======================================================================
1006 % marsbar('plot_data', p_type)
1007 %-----------------------------------------------------------------------
1008 % p_type     - plot type: one of 'raw','acf','fft','all' or 'full'
1009 % where 'full' results in a options to filter and choice of plot
1010
1011 if nargin < 2
1012   p_type = [];
1013 else
1014   p_type = varargin{2};
1015 end
1016 if isempty(p_type)
1017   p_type = 'full';
1018 end
1019 marsY = mars_arm('get', 'roi_data');
1020 if isempty(marsY), return, end
1021
1022 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Plot data', 0);
1023 if strcmp(p_type, 'full')
1024   if ~mars_arm('isempty', 'def_design')
1025     D = mars_arm('get', 'def_design');
1026     if isempty(D), return, end
1027     if has_filter(D)
1028       if spm_input('Use design filter?', '+1', 'y/n', [1 0], 1)
1029     flags = {};
1030     if has_whitener(D)
1031       if ~spm_input('Use whitening filter?', '+1', 'y/n', [1 0], 1)
1032         flags = 'no_whitening';
1033       end
1034     end
1035     marsY = apply_filter(D, marsY, flags);
1036       end
1037     end
1038   end
1039   p_type = char(spm_input('Type of plot', '+1', 'm', ...
1040              'All|Time course|FFT|ACF', ...
1041              {'all','raw','fft','acf'}));
1042 end
1043
1044 ns  = region_name(marsY);
1045 rno = mars_struct('getifthere', MARS, 'WORKSPACE', 'default_region');
1046 if ~isempty(rno)
1047   fprintf('Using default region: %s\n', ns{rno});
1048 end
1049 ui_plot(marsY, struct('types', p_type, 'r_nos', rno));
1050
1051 %=======================================================================
1052 case 'import_data'                                    %- it imports data
1053 %=======================================================================
1054 % marsbar('import_data')
1055 %-----------------------------------------------------------------------
1056
1057 % Check for save of current dataa
1058 if sf_prev_save('roi_data') == -1, return, end
1059
1060 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Import data', 0);
1061
1062 r_f = spm_input('Import what?', '+1', 'm', ...
1063         ['Sample time courses for one region'...
1064          '|Summary time course(s) for region(s)'],...
1065         [1 0], 2);
1066
1067 Ls =         ['Matlab workspace' ...
1068          '|Text file',...
1069          '|Lotus spreadsheet'];,...
1070 Os =            {'matlab','txt','wk1'};
1071
1072 if ~isempty(which('xlsread'))
1073   Ls = [Ls  '|Excel spreadsheet'];
1074   Os = [Os {'xls'}];
1075 end
1076
1077 src = spm_input('Import fron?', '+1', 'm', Ls, Os, 1);
1078
1079 switch src{1}
1080  case 'matlab'
1081   Y = spm_input('Matlab expression', '+1', 'e');
1082   fn = 'Matlab input';
1083   pn_fn = lower(fn);
1084  case 'txt'
1085   [fn, pn] = mars_uifile('get',  ...
1086       {'*.txt;*.dat;*.csv', 'Text files (*.txt, *.dat, *.csv)'; ...
1087        '*.*',                   'All Files (*.*)'}, ...
1088       'Select a text file');
1089   if isequal(fn,0), return, end
1090   pn_fn = fullfile(pn, fn);
1091   Y = spm_load(pn_fn);
1092  case 'wk1'
1093   [fn, pn] = mars_uifile('get',  ...
1094       {'*.wk1', 'Lotus spreadsheet files (*.wk1)'; ...
1095        '*.*',                   'All Files (*.*)'}, ...
1096       'Select a Lotus file');
1097   if isequal(fn,0), return, end
1098   pn_fn = fullfile(pn, fn);
1099   Y = wk1read(pn_fn);
1100  case 'xls'
1101   [fn, pn] = mars_uifile('get',  ...
1102       {'*.xls', 'Excel spreadsheet files (*.xls)'; ...
1103        '*.*',                   'All Files (*.*)'}, ...
1104       'Select an Excel file');
1105   if isequal(fn,0), return, end
1106   pn_fn = fullfile(pn, fn);
1107   Y = xlsread(pn_fn);
1108  otherwise
1109   error('Strange source');
1110 end
1111 if r_f   % region data
1112   s_f = sf_get_sumfunc(MARS.OPTIONS.statistics.sumfunc);
1113   r_st = struct('name', fn,...
1114         'descrip', pn_fn);
1115   s_st = struct('descrip', ['Region data loaded from ' pn_fn],...
1116         'sumfunc', s_f);
1117   marsY = marsy({Y},r_st, s_st);
1118   pref = '';  % Region name prefix not used, as names are set
1119 else     % summary data
1120   s_st = struct('descrip', ['Summary data loaded from ' pn_fn]);
1121   marsY = marsy(Y, '', s_st);
1122   pref = spm_input('Prefix for region names', '+1', 's', [fn '_']);
1123 end
1124
1125 % Names
1126 stop_f = 0;
1127 ns = region_name(marsY, [], [], pref);
1128 spm_input('Return name with spaces only to abort entry','+1','d');
1129 for r = 1:length(ns)
1130   ns{r} = spm_input(...
1131       sprintf('Name for region %d', r),...
1132       '+1', 's', ns{r});
1133   if all(ns{r}==' '), stop_f = 1; break, end
1134 end
1135 if ~stop_f
1136   marsY = region_name(marsY, [], ns);
1137 end
1138
1139 mars_arm('set', 'roi_data', marsY);
1140 mars_arm('show_summary', 'roi_data');
1141 disp(['Data loaded from ' pn_fn]);
1142
1143 %=======================================================================
1144 case 'export_data'                                            %- exports
1145 %=======================================================================
1146 % marsbar('export_data')
1147 %-----------------------------------------------------------------------
1148 marsY = mars_arm('get', 'roi_data');
1149 if isempty(marsY), return, end
1150
1151 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Export data', 0);
1152
1153 r_f = spm_input('Export what?', '+1', 'm', ...
1154         ['Sample time courses for one region'...
1155          '|Summary time course(s) for region(s)'],...
1156         [1 0], 2);
1157
1158 Ls =         ['Matlab workspace' ...
1159          '|Text file',...
1160          '|Lotus spreadsheet'];,...
1161 Os =            {'matlab','txt','wk1'};
1162
1163 if ~isempty(which('xlswrite'))
1164   xls_write = 1;
1165 elseif ~isempty(which('xlswrite5'))
1166   xls_write = 2;
1167 else
1168   xls_write = 0;
1169 end
1170
1171 if xls_write
1172   Ls = [Ls  '|Excel spreadsheet'];
1173   Os = [Os {'xls'}];
1174 end
1175
1176 src = spm_input('Export to?', '+1', 'm', Ls, Os, 1);
1177
1178 if r_f
1179   rno = marsbar('get_region', region_name(marsY));
1180   Y = region_data(marsY, rno);
1181   Y = Y{1};
1182 else
1183   Y = summary_data(marsY);
1184 end
1185
1186 switch src{1}
1187  case 'matlab'
1188   str = '';
1189   while ~mars_utils('is_valid_varname', str)
1190     str = spm_input('Matlab variable name', '+1', 's');
1191     if isempty(str), return, end
1192   end
1193   assignin('base', str, Y);
1194   fn = ['Matlab variable: ' str];
1195  case 'txt'
1196   [fn, pn] = mars_uifile('put',  ...
1197       {'*.txt;*.dat;*.csv', 'Text files (*.txt, *.dat, *.csv)'; ...
1198        '*.*',                   'All Files (*.*)'}, ...
1199       'Text file name');
1200   if isequal(fn,0), return, end
1201   save(fullfile(pn,fn), 'Y', '-ascii');
1202  case 'wk1'
1203   [fn, pn] = mars_uifile('put',  ...
1204       {'*.wk1', 'Lotus spreadsheet files (*.wk1)'; ...
1205        '*.*',                   'All Files (*.*)'}, ...
1206       'Lotus spreadsheet file');
1207   if isequal(fn,0), return, end
1208   wk1write(fullfile(pn,fn), Y);
1209  case 'xls'
1210   [fn, pn] = mars_uifile('put',  ...
1211       {'*.xls', 'Excel spreadsheet files (*.xls)'; ...
1212        '*.*',                   'All Files (*.*)'}, ...
1213       'Excel spreadsheet file');
1214   if isequal(fn,0), return, end
1215   if xls_write == 1
1216     xlswrite(fullfile(pn,fn), Y);
1217   else
1218     xlswrite5(fullfile(pn,fn), Y);
1219   end
1220  otherwise
1221   error('Strange source');
1222 end
1223 disp(['Data saved to ' fn]);
1224
1225 %=======================================================================
1226 case 'split_data'                %- splits data into one file per region
1227 %=======================================================================
1228 % marsbar('split_data')
1229 %-----------------------------------------------------------------------
1230 marsY = mars_arm('get', 'roi_data');
1231 if isempty(marsY), return, end
1232 if n_regions(marsY) == 1
1233   disp('Only one region in ROI data');
1234   return
1235 end
1236
1237 % Setup input window
1238 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Split regions to files', 0);
1239
1240 d = spm_get([-1 0], '', 'New directory root for files');
1241 if isempty(d), return, end
1242
1243 def_f = summary_descrip(marsY);
1244 if ~isempty(def_f)
1245   def_f = mars_utils('str2fname', def_f);
1246 end
1247 f = spm_input('Root filename for regions', '+1', 's', def_f);
1248 f = mars_utils('str2fname', f);
1249 mYarr = split(marsY);
1250 for i = 1:length(mYarr)
1251   fname = fullfile(d, sprintf('%s_region_%d_mdata.mat', f, i));
1252   savestruct(mYarr(i), fname);
1253   fprintf('Saved region %d as %s\n', i, fname);
1254 end
1255
1256 %=======================================================================
1257 case 'join_data'                %- joins many data files into one object
1258 %=======================================================================
1259 % marsbar('join_data')
1260 %-----------------------------------------------------------------------
1261
1262 % Check save of current data first
1263 if sf_prev_save('roi_data') == -1, return, end
1264
1265 P = spm_get([0 Inf], '*_mdata.mat', 'Select data files to join');
1266
1267 if isempty(P), return, end
1268 for i = 1:size(P,1)
1269   d_o{i} = marsy(deblank(P(i,:)));
1270 end
1271 marsY = join(d_o{:});
1272 mars_arm('set', 'roi_data', marsY);
1273 mars_arm('show_summary', 'roi_data');
1274 disp(P)
1275 disp('Files merged and set as current data')
1276
1277 %=======================================================================
1278 case 'estimate'                                       %-Estimates design
1279 %=======================================================================
1280 % marsbar('estimate')
1281 %-----------------------------------------------------------------------
1282 % Sequence is bit complex here, as setting the design may clear the ROI
1283 % data, and setting the ROI data may clear the default design, if they
1284 % have different numbers of rows
1285 marsD= mars_arm('get', 'def_design');
1286 if isempty(marsD), return, end
1287 marsY = mars_arm('get', 'roi_data');
1288 if isempty(marsY), return, end
1289 if mars_arm('isempty', 'def_design')
1290   error('Need design and data with matching number of rows');
1291 end
1292 if sf_prev_save('est_design') == -1, return, end
1293 if ~can_mars_estimate(marsD)
1294   marsD = fill(marsD, 'for_estimation');
1295   mars_arm('update', 'def_design', marsD);
1296 end
1297 marsRes = estimate(marsD, marsY, struct(...
1298     'redo_covar', 1, 'redo_whitening', 1));
1299 mars_arm('set', 'est_design', marsRes);
1300 mars_arm('show_summary', 'est_design');
1301
1302 %=======================================================================
1303 case 'set_results'          %-sets estimated design into global stucture
1304 %=======================================================================
1305 % donef = marsbar('set_results')
1306 %-----------------------------------------------------------------------
1307 % Set results, put results ROI data into roi_data container
1308
1309 varargout = {0};
1310
1311 % Check if there's anything we don't want to write over
1312 if sf_prev_save('est_design') == -1, return, end
1313 if sf_prev_save('roi_data') == -1, return, end
1314
1315 % Do set
1316 mars_arm('set_ui', 'est_design');
1317 if mars_arm('isempty', 'est_design'), return, end
1318
1319 % Get design, set ROI data
1320 marsRes = mars_arm('get', 'est_design');
1321 mars_arm('set', 'roi_data', get_data(marsRes));
1322
1323 % Clear default contrast
1324 if mars_struct('isthere', MARS, 'WORKSPACE', 'default_contrast')
1325   MARS.WORKSPACE.default_contrast = [];
1326   fprintf('Reset of estimated design, cleared default contrast...\n');
1327 end
1328
1329 % Report on design
1330 fprintf('%-40s: ','Design reporting');
1331 ui_report(marsRes, 'DesMtx');
1332 ui_report(marsRes, 'DesRepUI');
1333 fprintf('%30s\n','...done');
1334
1335 varargout = {1};
1336 return
1337
1338 %=======================================================================
1339 case 'plot_residuals'                  %-plots residuals from estimation
1340 %=======================================================================
1341 % marsbar('plot_residuals')
1342 %-----------------------------------------------------------------------
1343 marsRes = mars_arm('get', 'est_design');
1344 if isempty(marsRes), return, end
1345 Y = residuals(marsRes);
1346 ns  = region_name(Y);
1347 rno = mars_struct('getifthere', MARS, 'WORKSPACE', 'default_region');
1348 if ~isempty(rno)
1349   fprintf('Using default region: %s\n', ns{rno});
1350 end
1351 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Plot residuals', 1);
1352 p_type = char(spm_input('Type of plot', '+1', 'm', ...
1353             'All|Time course|FFT|ACF', ...
1354             {'all','raw','fft','acf'}));
1355 ui_plot(Y, struct('types', p_type, 'r_nos', rno));
1356
1357 %=======================================================================
1358 case 'set_defcon'                                 %-set default contrast
1359 %=======================================================================
1360 % Ic = marsbar('set_defcon')
1361 %-----------------------------------------------------------------------
1362 varargout = {[]};
1363 marsRes = mars_arm('get', 'est_design');
1364 if isempty(marsRes), return, end
1365
1366 % Setup input window
1367 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Default contrast', 0);
1368 Ic = mars_struct('getifthere',MARS, 'WORKSPACE', 'default_contrast');
1369 if isempty(Ic)
1370   cname = '[Not set]';
1371 else
1372   xCon = get_contrasts(marsRes);
1373   cname = xCon(Ic).name;
1374 end
1375 spm_input(cname, 1, 'd', 'Default contrast');
1376 opts = {'Quit', 'Set new default'};
1377 if ~isempty(Ic), opts = [opts {'Clear default contrast'}]; end
1378 switch spm_input('What to do?', '+1', 'm', opts, [1:length(opts)], 1);
1379  case 1
1380  case 2
1381   [Ic marsRes changef] = ui_get_contrasts(marsRes, 'T|F',1,...
1382              'Select default contrast','',1);
1383   if changef
1384     mars_arm('update', 'est_design', marsRes);
1385   end
1386  case 3
1387   Ic = [];
1388 end
1389 MARS.WORKSPACE.default_contrast = Ic;
1390 varargout = {Ic};
1391
1392 %=======================================================================
1393 case 'set_defregion'                                %-set default region
1394 %=======================================================================
1395 % rno = marsbar('set_defregion')
1396 %-----------------------------------------------------------------------
1397 varargout = {[]};
1398 marsY = mars_arm('get', 'roi_data');
1399 if isempty(marsY), return, end
1400 ns = region_name(marsY);
1401 if length(ns) == 1
1402   disp('Only one region in data');
1403   MARS.WORKSPACE.default_region = 1;
1404   varargout = {1};
1405   return
1406 end
1407
1408 % Setup input window
1409 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Default region', 0);
1410 rno = mars_struct('getifthere',MARS, 'WORKSPACE', 'default_region');
1411 if isempty(rno), rname = '[Not set]'; else rname = ns{rno}; end
1412 spm_input(rname, 1, 'd', 'Default region:');
1413 opts = {'Quit', 'Set new default'};
1414 if ~isempty(rno), opts = [opts {'Clear default region'}]; end
1415 switch spm_input('What to do?', '+1', 'm', opts, [1:length(opts)], 1);
1416  case 1
1417  case 2
1418   rno = marsbar('get_region', ns);
1419   disp(['Default region set to: ' ns{rno}]);
1420  case 3
1421   rno = [];
1422 end
1423 MARS.WORKSPACE.default_region = rno;
1424 varargout = {rno};
1425
1426 %=======================================================================
1427 case 'get_region'                                  %-ui to select region
1428 %=======================================================================
1429 % select region from list box / input
1430 % rno = marsbar('get_region', names, prompt)
1431 % names is cell array of strings identifying regions
1432 % prompt is prompt string
1433 %-----------------------------------------------------------------------
1434
1435 if nargin < 2
1436   error('Need region names to select from');
1437 else
1438   names = varargin{2};
1439 end
1440 if nargin < 3
1441   prompt = 'Select region';
1442 else
1443   prompt = varargin{3};
1444 end
1445
1446 % maximum no of items in list box
1447 maxlist = 200;
1448 if length(names) > maxlist
1449   % text input, maybe
1450   error('Too many regions');
1451 end
1452 if length(names) == 1
1453   rno = 1;
1454 elseif isempty(names)
1455   rno = []
1456 else
1457   % listbox
1458   rno = spm_input(prompt, '+1', 'm', names);
1459 end
1460 varargout = {rno};
1461
1462 %=======================================================================
1463 case 'spm_graph'                                         %-run spm_graph
1464 %=======================================================================
1465 % marsbar('spm_graph')
1466 %-----------------------------------------------------------------------
1467 marsRes = mars_arm('get', 'est_design');
1468 if isempty(marsRes), return, end
1469
1470 % Setup input window
1471 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Mars SPM graph', 1);
1472
1473 ns  = region_name(get_data(marsRes));
1474 rno = mars_struct('getifthere', MARS, 'WORKSPACE', 'default_region');
1475 if ~isempty(rno)
1476   fprintf('Using default region: %s\n', ns{rno});
1477 else
1478   rno = marsbar('get_region', ns, 'Select region to plot');
1479 end
1480
1481 Ic = mars_struct('getifthere', MARS, 'WORKSPACE', 'default_contrast');
1482 if ~isempty(Ic)
1483   xCon = get_contrasts(marsRes);
1484   fprintf('Using default contrast: %s\n', xCon(Ic).name);
1485 end
1486
1487 % Variables returned in field names to allow differences
1488 % in return variables between versions of spm_graph
1489 [r_st marsRes changef] = mars_spm_graph(marsRes, rno, Ic);
1490
1491 % Dump field names to global workspace as variables
1492 fns = fieldnames(r_st);
1493 for f = 1:length(fns)
1494   assignin('base', fns{f}, getfield(r_st, fns{f}));
1495 end
1496
1497 % Store if changed
1498 if changef
1499   mars_arm('update', 'est_design', marsRes);
1500 end
1501
1502 %=======================================================================
1503 case 'stat_table'                                       %-run stat_table
1504 %=======================================================================
1505 % marsbar('stat_table')
1506 %-----------------------------------------------------------------------
1507 marsRes = mars_arm('get', 'est_design');
1508 if isempty(marsRes), return, end
1509 Ic = mars_struct('getifthere', MARS, 'WORKSPACE', 'default_contrast');
1510 if ~isempty(Ic)
1511   xCon = get_contrasts(marsRes);
1512   fprintf('Using default contrast: %s\n', xCon(Ic).name);
1513 end
1514 [strs marsS marsRes changef] = ...
1515     stat_table(marsRes, Ic);
1516 disp(char(strs));
1517 assignin('base', 'marsS', marsS);
1518 if changef
1519   mars_arm('update', 'est_design', marsRes);
1520 end
1521
1522 %=======================================================================
1523 case 'signal_change'                             % percent signal change
1524 %=======================================================================
1525 % marsbar('signal_change')
1526 %-----------------------------------------------------------------------
1527 marsRes = mars_arm('get', 'est_design');
1528 if isempty(marsRes), return, end
1529 if ~is_fmri(marsRes)
1530   fprintf('Need FMRI design for %% signal change\n');
1531   return
1532 end
1533
1534 % Setup input window
1535 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Percent signal change', 0);
1536
1537 [marsRes ic status] = ui_event_types(marsRes);
1538 if (status==0), return, end
1539 if (status>1), mars_arm('update', 'est_design', marsRes); end
1540 if isempty(ic), return, end
1541
1542 dur       = spm_input('Event duration', '+1', 'e', 0);
1543
1544 % Choose event difference function
1545 diff_func = mars_struct('getifthere', MARS, 'OPTIONS', ...
1546             'events', 'diff_func');
1547 if isempty(diff_func), diff_func = 'max abs';
1548 elseif strcmp(diff_func, 'window')
1549   spm_input('Event signal change window...', '+1','d', mfilename);
1550   times = spm_input('Mean signal between times', ...
1551             '+1', 'r', [4 6], 2, [0 dur+32]);
1552   other_args = {times, bf_dt(marsRes)};
1553 else
1554   other_args = {};
1555 end
1556
1557 ic_len    = length(ic);
1558 et = event_types(marsRes);
1559 for i = 1:ic_len
1560   pc(i,:) = event_signal(marsRes, et(ic(i)).e_spec, dur,  ...
1561              diff_func, ...
1562              other_args{:});
1563 end
1564 rns       = region_name(get_data(marsRes));
1565 disp('Sort-of % signal change');
1566 disp(sprintf('Duration: %3.2f seconds', dur));
1567 for i = 1:ic_len
1568   disp(['Event: ' et(ic(i)).name]);
1569   for r = 1:length(rns)
1570     disp(sprintf('Region: %40s; %5.3f', rns{r}, pc(i, r)));
1571   end
1572 end
1573 assignin('base', 'pc', pc);
1574
1575 %=======================================================================
1576 case 'fitted_events'                    % show fitted event time courses
1577 %=======================================================================
1578 % marsbar('fitted_events')
1579 %-----------------------------------------------------------------------
1580 marsRes = mars_arm('get', 'est_design');
1581 if isempty(marsRes), return, end
1582 if ~is_fmri(marsRes)
1583   fprintf('Need FMRI design for fitted event time courses\n');
1584   return
1585 end
1586
1587 % Setup input window
1588 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','Fitted events', 1);
1589
1590 [marsRes ic status] = ui_event_types(marsRes);
1591 if (status==0), return, end
1592 if (status>1), mars_arm('update', 'est_design', marsRes); end
1593 if isempty(ic), return, end
1594
1595 dur       = spm_input('Event duration', '+1', 'e', 0);
1596 ic_len    = length(ic);
1597 et = event_types(marsRes);
1598 for i = 1:ic_len
1599   [tc{i} dt] = event_fitted(marsRes, et(ic(i)).e_spec, dur);
1600 end
1601
1602 if ic_len > 8
1603   warning('Too many event types to plot, plotting first 8');
1604   ic_len = 8;
1605 end
1606
1607 figure(Fgraph);
1608 if ic_len > 1, p_cols = 2; else p_cols = 1; end
1609 p_rows = ceil(ic_len / p_cols);
1610 last_row_starts = (p_rows-1) * p_cols + 1;
1611 for i = 1:ic_len
1612   t = tc{i};
1613   secs = ([1:size(t, 1)]-1) * dt;
1614   subplot(p_rows, p_cols, i);
1615   plot(secs, t);
1616   title(et(ic(i)).name);
1617   if i >= last_row_starts, xlabel('Seconds'); end
1618   if rem(i-1, p_cols)==0, ylabel('Signal change'); end
1619 end
1620
1621 legend(region_name(get_data(marsRes)));
1622
1623 assignin('base', 'time_courses', tc);
1624 assignin('base', 'dt', dt);
1625
1626 %=======================================================================
1627 case 'fir_events'                                  % show FIR for events
1628 %=======================================================================
1629 % marsbar('fir_events')
1630 %-----------------------------------------------------------------------
1631 marsRes = mars_arm('get', 'est_design');
1632 if isempty(marsRes), return, end
1633 if ~is_fmri(marsRes)
1634   fprintf('Need FMRI design for FIR event time courses\n');
1635   return
1636 end
1637
1638 % Setup input window
1639 [Finter,Fgraph,CmdLine] = spm('FnUIsetup','FIR for events', 1);
1640
1641 [marsRes ic status] = ui_event_types(marsRes);
1642 if (status==0), return, end
1643 if (status>1), mars_arm('update', 'est_design', marsRes); end
1644 if isempty(ic), return, end
1645
1646 et = event_types(marsRes);
1647 ic_len = length(ic);
1648
1649 % Single or stacked?
1650 % If all the events have zero duration, the model is already single, and
1651 % there is no point in asking.  If any of the durations are different
1652 % across events, then the single model is invalid.
1653 d_a = []; opts = [];
1654 for i = 1:ic_len
1655   e_spec = et(ic(i)).e_spec;
1656   for j = 1:size(e_spec, 2)
1657     [o d] = event_onsets(marsRes, e_spec(:, j));
1658     d_a = [d_a; d];
1659   end
1660 end
1661 if any(d_a) && ~any(diff(d_a))
1662   if spm_input('FIR type', '+1','m',...
1663            'Single|Stacked', [1 0], 1)
1664     opts.single = 1;
1665   end
1666 end
1667 if spm_input('Signal units', '+1','m',...
1668          'Percent|Beta units', [1 0], 1)
1669   opts.percent = 1;
1670 end
1671
1672 bin_length = spm_input('Bin length (secs)', '+1', 'e', tr(marsRes));
1673 def_bin_no = round(25/bin_length);
1674 bin_no     = spm_input('No of bins', '+1', 'e', def_bin_no);
1675
1676 for i = 1:ic_len
1677   tc{i} = event_fitted_fir(marsRes, ...
1678                et(ic(i)).e_spec, ...
1679                bin_length, ...
1680                bin_no, ...
1681                opts);
1682 end
1683
1684 if ic_len > 8
1685   warning('Too many event types to plot, plotting first 8');
1686   ic_len = 8;
1687 end
1688
1689 figure(Fgraph);
1690 if ic_len > 1, p_cols = 2; else p_cols = 1; end
1691 p_rows = ceil(ic_len / p_cols);
1692 last_row_starts = (p_rows-1) * p_cols + 1;
1693 secs = ([1:bin_no]-1) * bin_length + bin_length/2;
1694 for i = 1:ic_len
1695   t = tc{i};
1696   subplot(p_rows, p_cols, i);
1697   plot(secs, t);
1698   title(et(ic(i)).name);
1699   if i >= last_row_starts, xlabel('Seconds'); end
1700   if rem(i-1, p_cols)==0, ylabel('Signal change'); end
1701 end
1702 legend(region_name(get_data(marsRes)));
1703
1704 assignin('base', 'time_courses', tc);
1705 assignin('base', 'bin_length', bin_length);
1706 assignin('base', 'bin_no', bin_no);
1707
1708 %=======================================================================
1709 case 'add_events_by_name'  %-make event types from events with same name
1710 %=======================================================================
1711 % marsbar(''add_events_by_name')
1712 %-----------------------------------------------------------------------
1713 D = mars_arm('get', 'est_design');
1714 if isempty(D), return, end
1715 if ~is_fmri(D)
1716   disp('Can only add event types to FMRI designs');
1717   return
1718 end
1719 et = event_types(D);
1720 et = [et event_types_named(D)];
1721 D  = event_types(D, et);
1722 mars_arm('update', 'est_design', D);
1723
1724 %=======================================================================
1725 case 'merge_contrasts'                                %-import contrasts
1726 %=======================================================================
1727 % marsbar('merge_contrasts')
1728 %-----------------------------------------------------------------------
1729 D = mars_arm('get', 'est_design');
1730 if isempty(D), return, end
1731 filter_spec = {...
1732     'SPM.mat','SPM: SPM.mat';...
1733     '*_mres.mat','MarsBaR: *_mres.mat';...
1734     '*x?on.mat','xCon.mat file'};
1735 [fn pn] = mars_uifile('get', ...
1736     filter_spec, ...
1737     'Source design/contrast file...');
1738 if isequal(fn,0) || isequal(pn,0), return, end
1739 fname = fullfile(pn, fn);
1740 D2 = mardo(fname);
1741
1742 % has this got contrasts?
1743 if ~has_contrasts(D2)
1744   error(['Cannot find contrasts in design/contrast file ' fname]);
1745 end
1746
1747 % now try to trap case of contrast only file
1748 if ~is_valid(D2)
1749   D2 = get_contrasts(D2);
1750 end
1751
1752 [D Ic changef] = add_contrasts(D, D2, 'ui');
1753 disp('Done');
1754 if changef
1755   mars_arm('update', 'est_design', D);
1756 end
1757
1758 %=======================================================================
1759 case 'refresh_contrasts'                             %-refresh contrasts
1760 %=======================================================================
1761 % marsbar('refresh_contrasts')
1762 %-----------------------------------------------------------------------
1763 D = mars_arm('get', 'est_design');
1764 if isempty(D), return, end
1765 D = refresh_contrasts(D);
1766 disp('Refreshed contrasts');
1767 mars_arm('update', 'est_design', D);
1768
1769 %=======================================================================
1770 case 'add_trial_f'            %-add trial-specific F contrasts to design
1771 %=======================================================================
1772 % marsbar('add_trial_f')
1773 %-----------------------------------------------------------------------
1774 D = mars_arm('get', 'est_design');
1775 if isempty(D), return, end
1776 if ~is_fmri(D)
1777   disp('Can only add trial specific F contrasts for FMRI designs');
1778   return
1779 end
1780 [D changef] = add_trial_f(D);
1781 disp('Done');
1782 if changef
1783   mars_arm('update', 'est_design', D);
1784 end
1785
1786 %=======================================================================
1787 case 'error_log'                  %- makes file to help debugging errors
1788 %=======================================================================
1789 % fname = marsbar('error_log', fname);
1790 %-----------------------------------------------------------------------
1791 if nargin < 2
1792   fname = 'error_log.mat';
1793 else
1794   fname = varargin{2};
1795 end
1796
1797 e_log = struct('last_error', lasterr, ...
1798            'm_ver', marsbar('ver'),...
1799            'mars', MARS);
1800 savestruct(fname, e_log);
1801 if ~isempty(which('zip'))
1802   zip([fname '.zip'], fname);
1803   fname = [fname '.zip'];
1804 end
1805 disp(['Saved error log as ' fname]);
1806
1807 %=======================================================================
1808 case 'mars_menu'                     %-menu selection of marsbar actions
1809 %=======================================================================
1810 % marsbar('mars_menu',tstr,pstr,tasks_str,tasks)
1811 %-----------------------------------------------------------------------
1812
1813 [tstr pstr optfields optlabs] = deal(varargin{2:5});
1814 if nargin < 6
1815   optargs = cell(1, length(optfields));
1816 else
1817   optargs = varargin{6};
1818 end
1819
1820 [Finter,Fgraph,CmdLine] = spm('FnUIsetup',tstr);
1821 of_end = length(optfields)+1;
1822 my_task = spm_input(pstr, '+1', 'm',...
1823           {optlabs{:} 'Quit'},...
1824           [1:of_end],of_end);
1825 if my_task == of_end, return, end
1826 marsbar(optfields{my_task}{:});
1827
1828 %=======================================================================
1829 otherwise                                        %-Unknown action string
1830 %=======================================================================
1831 error('Unknown action string')
1832
1833 %=======================================================================
1834 end
1835 return
1836
1837 % subfunctions
1838 function sum_func = sf_get_sumfunc(sum_func)
1839 if strcmp(sum_func, 'ask')
1840   sum_func = char(spm_input('Summary function', '+1','m',...
1841                'Mean|Weighted mean|Median|1st eigenvector',...
1842                {'mean','wtmean','median','eigen1'}, 1));
1843 end
1844
1845 function btn = sf_prev_save(obj_name)
1846 btn = mars_arm('save_ui', obj_name, ...
1847            struct('ync', 1, ...
1848               'no_no_save', 1, ...
1849               'prompt_prefix', 'previous '));
1850 % If answer is 'No', then flag that we don't need to save
1851 if btn == 0
1852   mars_arm('set_param', obj_name, 'has_changed', 0);
1853 end
1854 return
1855