Description of pr_is_nix
Home > marsbar > @marmoire > private > pr_is_nix.m
pr_is_nix
PURPOSE
SYNOPSIS
function res = pr_is_nix(v)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
pr_is_nan
This function is called by:
do_save method to save data for item
do_set private function to set data into item
save_item_data save data for item to file
SOURCE CODE
function res = pr_is_nix(v)
res = isempty(v) | pr_is_nan(v);
return