Description of pr_isempty
Home > marsbar > @marmoire > private > pr_isempty.m
pr_isempty
PURPOSE
private function returns 1 if there is no data, or filename
SYNOPSIS
function res = pr_isempty(I)
DESCRIPTION
 private function returns 1 if there is no data, or filename
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
This function is called by:
do_save method to save data for item
do_set private function to set data into item
isempty_item_data returns 1 if no data for this item
pr_needs_save private function returning 1 if item data needs save
SOURCE CODE
function res = pr_isempty(I)
% private function returns 1 if there is no data, or filename
%
% $Id$
res = isempty(I.data) & isempty(I.file_name);