Description of pr_needs_save
Home > marsbar > @marmoire > private > pr_needs_save.m
pr_needs_save
PURPOSE
private function returning 1 if item data needs save
SYNOPSIS
function res = pr_needs_save(I)
DESCRIPTION
 private function returning 1 if item data needs save
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
pr_isempty private function returns 1 if there is no data, or filename
This function is called by:
do_save method to save data for item
item_needs_save return 1 if item requires a save
SOURCE CODE
function res = pr_needs_save(I)
% private function returning 1 if item data needs save
%
% $Id$
res = ~pr_isempty(I) & I.has_changed & I.save_if_changed;