Description of c_o_m
Home > marsbar > @maroi_shape > c_o_m.m
c_o_m
PURPOSE
c_o_m method - calculates centre of mass
SYNOPSIS
function pt = c_o_m(o, sp, pt_type)
DESCRIPTION
 c_o_m method - calculates centre of mass
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
centre centre method - sets / returns centre of ROI in mm
centre centre method - sets / returns centre of ROI in mm
This function is called by:
mars_build_roi builds ROIs via the SPM GUI
mars_display_roi utility routines for display of ROIs in graphic window
SOURCE CODE
function pt = c_o_m(o, sp, pt_type)
% c_o_m method - calculates centre of mass
%
% $Id$
if nargin < 2
  sp = '';
end
if nargin < 3
  pt_type = 'real';
end
pt = centre(o);
switch pt_type
 case {'real','mm'}
 case 'vox'
  if isempty(sp)
    error('Need space to define voxel centre of mass');
  end
  pt = sp.mat * [pt; 1];
  pt = pt(1:3)';
 otherwise
  error(['Do not recognize point type' pt_type]);
end