Description of add_item
Home > marsbar > @marmoire > add_item.m
add_item
PURPOSE
add item to armoire
SYNOPSIS
function o = add_item(o, item_name, item_contents)
DESCRIPTION
 add item to armoire
 FORMAT o = add_item(o, item, I)
 o              - object
 item_name     - item name
 item_contents = item ... contents
 $Id $
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
default_item returns default item
set_item_struct set whole item structure, including parameters
This function is called by:
add_if_absent Adds item only if not already present
SOURCE CODE
function o = add_item(o, item_name, item_contents)
% add item to armoire
% FORMAT o = add_item(o, item, I)
%
% o              - object
% item_name     - item name
% item_contents = item ... contents
%
% $Id $
if nargin < 2
  error('Need item name to add');
end
if nargin < 3
  item_contents = [];
end
I = default_item(o);
if isempty(item_contents)
  item_contents = I;
else
  def_fns = fieldnames(I);
  new_fns = def_fns(~ismember(def_fns, fieldnames(item_contents)));
  for fn = new_fns'
    item_contents = setfield(item_contents, fn{1}, getfield(I, fn{1}));
  end
end
o = set_item_struct(o, item_name, item_contents);