Description of add_if_absent
Home > marsbar > @marmoire > add_if_absent.m
add_if_absent
PURPOSE
Adds item only if not already present
SYNOPSIS
function o = add_if_absent(o, item, data)
DESCRIPTION
 Adds item only if not already present
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
data method to get or set data object
add_item add item to armoire
item_exists returns true if there is an item of this name
This function is called by:
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function o = add_if_absent(o, item, data)
% Adds item only if not already present
%
% $Id$
if nargin < 2
  error('Need name of item to add');
end
if nargin < 3
  error('Need data to put into item');
end
if ~item_exists(o, item)
  o = add_item(o, item, data);
end