Description of do_save
Home > marsbar > @marmoire > do_save.m
do_save
PURPOSE
method to save data for item
SYNOPSIS
function [res, o] = do_save(o, item, flags, filename)
DESCRIPTION
 method  to save data for item
 FORMAT [res, o] = do_save(o, item, flags, filename)
 o        - object
 item     - item name
 flags    - flags for save (see save_item_data.m for details)
 filename - (maybe) filename for save
 Returns
 saved_f  - flag set to 1 if save done, 0 not done, -1 if cancel
 o        - possibly modified object
 The function is written like this so that, in the future, we can use
 callbacks in this code to manipulate all the objects in the armoire
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
savestruct saves data in def_struct as variables in .mat file
savestruct saves data in def_struct into .mat file with variable name SPM
get_item_struct get whole item structure, including parameters
pr_is_nix
pr_isempty private function returns 1 if there is no data, or filename
pr_needs_save private function returning 1 if item data needs save
set_item_param method to set item parameters
set_item_struct set whole item structure, including parameters
savestruct saves data in y_struct as variables in .mat file
mars_uifile wrapper for matlab uiputfile/getfile; to resolve version differences
savestruct saves data in structure as variables in .mat file
This function is called by:
save_item_data save data for item to file
SOURCE CODE
function [res, o] = do_save(o, item, flags, filename)
% method  to save data for item
% FORMAT [res, o] = do_save(o, item, flags, filename)
%
% o        - object
% item     - item name
% flags    - flags for save (see save_item_data.m for details)
% filename - (maybe) filename for save
%
% Returns
% saved_f  - flag set to 1 if save done, 0 not done, -1 if cancel
% o        - possibly modified object
%
% The function is written like this so that, in the future, we can use
% callbacks in this code to manipulate all the objects in the armoire
%
% $Id$
if nargin < 2
  error('Need item');
end
if nargin < 3
  flags = NaN;
end
if nargin < 4
  filename = NaN;
end
% Get item
item_struct = get_item_struct(o, item);
% process flags
if ~isstruct(flags), flags = []; end
if pr_is_nix(filename), filename = item_struct.file_name; end
if pr_is_nix(filename), filename = item_struct.default_file_name; end
if pr_needs_save(item_struct) || isfield(flags, 'force') % force flag
  % prompt for filename if UI
  if isfield(flags, 'ui')
    % warn if empty, and warn_empty flag (we must be forcing to get here)
    if pr_isempty(item_struct)
      if isfield(flags, 'warn_empty')
    msgbox('Nothing to save', ...
           [item_struct.title ' is not set'], 'warn');
      end
      res = 0;
      return
    end
    % Work out prompt
    if isfield(flags, 'prompt')
      prompt = flags.prompt;
    else
      prompt = item_struct.title;
    end
    if isfield(flags, 'prompt_prefix')
      prompt = [flags.prompt_prefix prompt];
    end
    if isfield(flags, 'prompt_suffix')
      prompt = [prompt flags.prompt_suffix];
    end
    if isfield(flags, 'ync')
      save_yn = questdlg(['Save ' prompt '?'],...
             'Save', 'Yes', 'No', 'Cancel', 'Yes');
      if strcmp(save_yn, 'Cancel'), res = -1; return, end
      if strcmp(save_yn, 'No')
    if isfield(flags, 'no_no_save')
      o  = set_item_param(o, item, 'has_changed', 0);
    end
    res = 0;
    return
      end
    end
    pr = ['Filename to save ' prompt];
    [f p] = mars_uifile('put', item_struct.filter_spec, pr, filename);
    if all(f==0), res = -1; return, end
    filename = fullfile(p, f);
  end
  savestruct(item_struct.data, filename);
  if item_struct.verbose
    fprintf('%s saved to %s\n', item_struct.title, filename);
  end
  item_struct.file_name = filename;
  item_struct.has_changed = 0;
  if item_struct.leave_as_file
    % maintain only on file, as it has beed saved
    item_struct.data = [];
  end
  o  = set_item_struct(o, item, item_struct);
  res = 1;
else
  res = 0;
end
return