Description of get_item_struct
Home > marsbar > @marmoire > get_item_struct.m
get_item_struct
PURPOSE
get whole item structure, including parameters
SYNOPSIS
function I = get_item_struct(o, item)
DESCRIPTION
 get whole item structure, including parameters
 FORMAT I = get_item_struct(o, item)
 This is used internally, and might be useful for debugging
 o       - object
 item    - item name
 Returns
 I       - item structure, with data in field 'data' and/or specified in
           field 'filename'
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
item_exists returns true if there is an item of this name
This function is called by:
do_save method to save data for item
do_set private function to set data into item
get_item_data get data for item
get_item_param method to get item parameters
isempty_item_data returns 1 if no data for this item
item_needs_save return 1 if item requires a save
save_item_data save data for item to file
set_item_param method to set item parameters
mars_arm_call services callbacks from marmoire object set functions
SOURCE CODE
function I = get_item_struct(o, item)
% get whole item structure, including parameters
% FORMAT I = get_item_struct(o, item)
%
% This is used internally, and might be useful for debugging
%
% o       - object
% item    - item name
%
% Returns
% I       - item structure, with data in field 'data' and/or specified in
%           field 'filename'
%
% $Id$
if ~item_exists(o, item)
  error('Item does not exist');
end
I = getfield(o.items, item);