Description of isempty_item_data
Home > marsbar > @marmoire > isempty_item_data.m
isempty_item_data
PURPOSE
returns 1 if no data for this item
SYNOPSIS
function tf = isempty_item_data(o, item)
DESCRIPTION
 returns 1 if no data for this item
 FORMAT tf = sjjs(o, item)
 o     - object
 item  - item name
 tf    - flag, 1 if not empty
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
get_item_struct get whole item structure, including parameters
pr_isempty private function returns 1 if there is no data, or filename
This function is called by:
get_item_data get data for item
mars_arm wrapper function for MarsBaR marmoire object
mars_arm_call services callbacks from marmoire object set functions
SOURCE CODE
function tf = isempty_item_data(o, item)
% returns 1 if no data for this item
% FORMAT tf = sjjs(o, item)
%
% o     - object
% item  - item name
%
% tf    - flag, 1 if not empty
%
% $Id$
if nargin < 2
  error('Need item')
end
I  = get_item_struct(o, item);
tf = pr_isempty(I);