Description of item_exists
Home > marsbar > @marmoire > item_exists.m
item_exists
PURPOSE
returns true if there is an item of this name
SYNOPSIS
function tf = item_exists(o, item)
DESCRIPTION
 returns true if there is an item of this name
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
This function is called by:
add_if_absent Adds item only if not already present
get_item_struct get whole item structure, including parameters
mars_arm wrapper function for MarsBaR marmoire object
SOURCE CODE
function tf = item_exists(o, item)
% returns true if there is an item of this name
%
% $Id$
tf = 0;
if ~isempty(o.items)
  tf = ismember(item, fieldnames(o.items));
end