Description of save_item_data_ui
Home > marsbar > @marmoire > save_item_data_ui.m
save_item_data_ui
PURPOSE
save data for item to file using GUI
SYNOPSIS
function [saved_f, o] = save_item_data_ui(o, item, flags, filename)
DESCRIPTION
 save data for item to file using GUI
 FORMAT [saved_f o] = save_item_data_ui(o, item, flags, filename)
 o        - object
 item     - name of item
 flags    - flags for save; see save_item_data.m for details
 filename - filename for save
 Returns
 saved_f  - flag set to 1 if save done, 0 not done, -1 if cancel
            Note that, if saving with more than one item, then the value
            is from the last value saved/not saved.  Cancel aborts the
            attempt to save.
 o        - possibly modified object (changed filename, maybe data is
            left as a file, and data field made empty)
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
save_item_data save data for item to file
This function is called by:
mars_arm wrapper function for MarsBaR marmoire object
mars_arm_call services callbacks from marmoire object set functions
SOURCE CODE
function [saved_f, o] = save_item_data_ui(o, item, flags, filename)
% save data for item to file using GUI
% FORMAT [saved_f o] = save_item_data_ui(o, item, flags, filename)
%
% o        - object
% item     - name of item
% flags    - flags for save; see save_item_data.m for details
% filename - filename for save
%
% Returns
% saved_f  - flag set to 1 if save done, 0 not done, -1 if cancel
%            Note that, if saving with more than one item, then the value
%            is from the last value saved/not saved.  Cancel aborts the
%            attempt to save.
% o        - possibly modified object (changed filename, maybe data is
%            left as a file, and data field made empty)
%
% $Id$
if nargin < 2
  error('Need item');
end
if nargin < 3
  flags = NaN;
end
if nargin < 4
  filename = NaN;
end
if ~isstruct(flags), flags = []; end
flags.ui = 1;
[saved_f o] = save_item_data(o, item, flags, filename);