Description of set_item_struct
Home > marsbar > @marmoire > set_item_struct.m
set_item_struct
PURPOSE
set whole item structure, including parameters
SYNOPSIS
function o = set_item_struct(o, item, item_struct)
DESCRIPTION
 set whole item structure, including parameters
 FORMAT I = get_item_struct(o, item, item_struct)
 o           - object
 item        - item name
 item_struct - item structure
 Returns
 o           - object with item structure set
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
add_item add item to armoire
do_save method to save data for item
do_set private function to set data into item
set_item_param method to set item parameters
mars_arm_call services callbacks from marmoire object set functions
SOURCE CODE
function o = set_item_struct(o, item, item_struct)
% set whole item structure, including parameters
% FORMAT I = get_item_struct(o, item, item_struct)
%
% o           - object
% item        - item name
% item_struct - item structure
%
% Returns
% o           - object with item structure set
%
% $Id$
% We might consider error checking here.  But hey.
o.items = setfield(o.items, item, item_struct);