Description of update_item_data
Home > marsbar > @marmoire > update_item_data.m
update_item_data
PURPOSE
updates data for item (sets data, flags change)
SYNOPSIS
function [o, errf] = update_item_data(o, item, data, filename)
DESCRIPTION
 updates data for item (sets data, flags change)
 FORMAT [o, errf] = update_item_data(o, item, data, filename)
 o        - object
 item     - name of item to update for
 data     - data to set
 filename - filename for data
 Returns
 o        - object with data (probably) updated
 errf     - flag is 1 if data was not updated for some reason
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
data method to get or set data object
do_set private function to set data into item
This function is called by:
mars_arm wrapper function for MarsBaR marmoire object
SOURCE CODE
function [o, errf] = update_item_data(o, item, data, filename)
% updates data for item (sets data, flags change)
% FORMAT [o, errf] = update_item_data(o, item, data, filename)
%
% o        - object
% item     - name of item to update for
% data     - data to set
% filename - filename for data
%
% Returns
% o        - object with data (probably) updated
% errf     - flag is 1 if data was not updated for some reason
%
% $Id$
if nargin < 2
  error('Need item to set to');
end
if nargin < 3
  data = NaN;
end
if nargin < 4
  filename = NaN;
end
[o errf] = do_set(o, item, 'update', data, filename);