Description of my_roifname
Home > marsbar > @maroi > private > my_roifname.m
my_roifname
PURPOSE
changes fname to appropriate ROI format
SYNOPSIS
function roifname = my_roifname(fname)
DESCRIPTION
 changes fname to appropriate ROI format
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
maroi maroi - class constructor for umbrella ROI object
spm_get compatibility function to allow spm_get calls with SPM5
This function is called by:
maroi maroi - class constructor for umbrella ROI object
SOURCE CODE
function roifname = my_roifname(fname)
% changes fname to appropriate ROI format
%
% $Id$
if nargin < 1
  fname = [];
end
roifname = fname;
if isempty(fname)
  return
end
gend = maroi('classdata', 'fileend');
lg = length(gend);
[p f e] = fileparts(roifname);
f2 = [f e];
if length(f2)<lg | ~strcmp(gend, [f2(end - lg +1 : end)])
  roifname = fullfile(p, [f gend]);
end
% make absolute path
roifname = spm_get('cpath', roifname);