Description of get_subjroot
Home > marsbar > examples > batch > get_subjroot.m
get_subjroot
PURPOSE
FORMAT subjroot = get_subjroot()
SYNOPSIS
function subjroot = get_subjroot()
DESCRIPTION
 FORMAT subjroot = get_subjroot()
 Gets the root path for the example data.
 Looks first for an environment variable, if not defined, uses GUI
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
spm_get compatibility function to allow spm_get calls with SPM5
This function is called by:
run_preprocess Run smoothing and SPM analysis for MarsBaR ER sample data
run_s3_model Run SPM 2-session model for MarsBaR ER sample data
run_tutorial MarsBaR batch script to show off MarsBaR batching
SOURCE CODE
function subjroot = get_subjroot()
% FORMAT subjroot = get_subjroot()
%
% Gets the root path for the example data.
% Looks first for an environment variable, if not defined, uses GUI
subjroot = getenv('MARSBAR_EG_DATAPATH');
% Otherwise fetch via the GUI
if isempty(subjroot)
    subjroot = spm_get(-1, '', 'Root directory of example data');
end
if ~exist(fullfile(subjroot, 'sess1'), 'dir')
    error(sprintf('Expecting "sess1" directory in %s', subjroot))
end
return