Description of my_design
Home > marsbar > @mardo_99 > private > my_design.m
my_design
PURPOSE
returns 1 if design looks like it is of SPM99 type
SYNOPSIS
function tf = my_design(des)
DESCRIPTION
 returns 1 if design looks like it is of SPM99 type
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
isfield method to overload isfield for mardo objects
This function is called by:
mardo_2 class constructor for SPM2 MarsBaR design object
mardo_5 class constructor for SPM5 MarsBaR design object
mardo_99 class constructor for SPM99 MarsBaR design object
SOURCE CODE
function tf = my_design(des)
% returns 1 if design looks like it is of SPM99 type
%
% $Id$
tf = 0;
if isfield(des, 'SPMid')
  % Can be SPM99 design with SPM99 tag or MarsBaR tag
  % (MarsBaR tag used only by MarsBaR <= 0.23)
  tf = ~isempty(strmatch('SPM99', des.SPMid)) | ...
       ~isempty(strmatch('MarsBar', des.SPMid));
end