Description of adjusted_data
Home > marsbar > @mardo > adjusted_data.m
adjusted_data
PURPOSE
Return adjusted data for estimated design and contrast no
SYNOPSIS
function Ya = adjusted_data(D, Ic)
DESCRIPTION
 Return adjusted data for estimated design and contrast no
 FORMAT Ya = adjusted_data(D, Ic)
 D      - Estimated marsbar design
 Ic     - Contrast number to adjust for
 Outputs
 Ya     - Adjusted data, N by M, where N is number of time points
          and M is number of regions in estimated marsbar design
 e.g
 E = estimate(D, Y);
 [E Ic] = add_contrasts(E, 'task', 'T', [1 0 0]);
 Ya = adjusted_data(E, Ic);
 Matthew Brett
CROSS-REFERENCE INFORMATION
This function calls:
betas method to get estimated betas
des_struct get/set method for des_struct field
get_contrasts method to get contrasts from design object
is_mars_estimated method returns 1 if design has been estimated in MarsBaR
This function is called by:
SOURCE CODE
function Ya = adjusted_data(D, Ic)
% Return adjusted data for estimated design and contrast no
% FORMAT Ya = adjusted_data(D, Ic)
%
% D      - Estimated marsbar design
% Ic     - Contrast number to adjust for
%
% Outputs
% Ya     - Adjusted data, N by M, where N is number of time points
%          and M is number of regions in estimated marsbar design
%
% e.g
% E = estimate(D, Y);
% [E Ic] = add_contrasts(E, 'task', 'T', [1 0 0]);
% Ya = adjusted_data(E, Ic);
%
% Matthew Brett
if nargin < 2
  error('Need contrast number');
end
if nargin < 3
  r_no = 1;
end
Ya = [];
if ~is_mars_estimated(D)
  error('Need a MarsBaR estimated design');
end
SPM   = des_struct(D);
B = betas(D);
xCon = get_contrasts(D);
Ya = spm_FcUtil('Yc', xCon(Ic),SPM.xX.xKXs, B);