Description of betas
Home > marsbar > @mardo > betas.m
betas
PURPOSE
method to get estimated betas
SYNOPSIS
function r = betas(o)
DESCRIPTION
 method to get estimated betas
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
is_mars_estimated method returns 1 if design has been estimated in MarsBaR
This function is called by:
adjusted_data Return adjusted data for estimated design and contrast no
event_fitted method to compute fitted event time course
event_fitted_fir method to compute fitted event time courses using FIR
pr_stat_compute private function to compute statistics for SPM2 design
pr_stat_compute_mv private function to compute mutlivariate statistics across ROIs
pr_stat_compute private function to compute statistics for SPM2 design
pr_stat_compute_mv private function to compute mutlivariate statistics across ROIs
pr_stat_compute calculates contrast value, stats and p values for contrasts
pr_stat_compute_mv compute multivariate statistics across ROIs
SOURCE CODE
function r = betas(o)
% method to get estimated betas
%
% $Id$
if ~is_mars_estimated(o)
  error('No betas, model not estimated');
end
SPM = des_struct(o);
r   = SPM.betas;