Description of block_means
Home > marsbar > @mardo > block_means.m
block_means
PURPOSE
method returns means for blocks in design
SYNOPSIS
function bms = block_means(D)
DESCRIPTION
 method returns means for blocks in design
 Inputs
 D        - design object
 Outputs
 bms      - means over block.  Returns B x N matrix
            where B is number of blocks, and N is number
            of ROIs
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
data method to get or set data object
isempty overloaded isempty method for mardo object
summary_block_means return raw means over blocks in summary data
This function is called by:
event_fitted_fir method to compute fitted event time courses using FIR
event_signal method to compute % signal change from fMRI events
run_tutorial MarsBaR batch script to show off MarsBaR batching
SOURCE CODE
function bms = block_means(D)
% method returns means for blocks in design
%
% Inputs
% D        - design object
%
% Outputs
% bms      - means over block.  Returns B x N matrix
%            where B is number of blocks, and N is number
%            of ROIs
%
% $Id$
Y = data(D);
if isempty(Y)
  error('Design does not yet have data');
end
bms = summary_block_means(data(D));