Description of contrasts
Home > marsbar > @mardo > contrasts.m
contrasts
PURPOSE
method to get or set contrasts
SYNOPSIS
function r = contrasts(o, xcon)
DESCRIPTION
 method to get or set contrasts
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
get_contrasts method to get contrasts from design object
set_contrasts method to set contrasts into design object
This function is called by:
er_contrast_spm99 ------------------------------------------------------------------
SOURCE CODE
function r = contrasts(o, xcon)
% method to get or set contrasts
%
% $Id$
if nargin < 2
  r = get_contrasts(o);
else
  % Always refreshes the contrasts for safety
  r = set_contrasts(o, xcon);
end