Description of data
Home > marsbar > @mardo > data.m
data
PURPOSE
method to get or set data object
SYNOPSIS
function r = data(o, Y)
DESCRIPTION
 method to get or set data object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
get_data method to get data from design object
set_data method to set data for design object
This function is called by:
block_means method returns means for blocks in design
event_fitted_fir method to compute fitted event time courses using FIR
flip_option get/set flag for flipping images in design
mars_tag returns, or sets, Mars tagging structure in design
verbose get/set method for verbose field
add_if_absent Adds item only if not already present
do_set private function to set data into item
set_item_data sets data for item
update_item_data updates data for item (sets data, flags change)
getdata getdata method - fetches time series data for ROI from images
verbose get/set method for verbose field
mars_arm_call services callbacks from marmoire object set functions
mars_armoire multifunction function to get/set various stores of stuff
SOURCE CODE
function r = data(o, Y)
% method to get or set data object
%
% $Id$
if nargin < 2
  r = get_data(o);
else
  r = set_data(o, Y);
end