Description of des_struct
Home > marsbar > @mardo > des_struct.m
des_struct
PURPOSE
get/set method for des_struct field
SYNOPSIS
function res = des_struct(obj, Struct)
DESCRIPTION
 get/set method for des_struct field
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
add_contrasts method to add contrast definitions to design
adjusted_data Return adjusted data for estimated design and contrast no
betas method to get estimated betas
block_mean_cols method returns rows for means for blocks in design
descrip method gets cell string description of design
design_matrix method returns design matrix from design
design_structure method to get or set SPM design structure
error_df method returns error df from design
event_fitted method to compute fitted event time course
event_signal method to compute % signal change from fMRI events
event_types method to get / set event types for design
get_contrasts method to get contrasts from design object
get_data method to get data from design object
get_vol_field method to get named field, containing or referring to vol structs
has_contrasts method returns 1 if design has contrasts
has_filter returns 1 if object contains filter
is_valid returns 1 if object contains valid SPM/MarsBaR design
masking_struct method to get or set SPM masking structure
n_effects get number of effects (columns) in design
n_time_points get number of time_points in design
residuals method returns residuals from model
savestruct saves data in def_struct as variables in .mat file
set_contrasts method to set contrasts into design object
set_data method to set data for design object
set_vol_field method to set named field, containing or referring to vol structs
subsasgn method to overload . notation in assignments.
subsref method to overload the . notation.
swd method to get/set design directory
ui_get_contrasts SPM contrast UI, wrapped for MarsBaR
add_trial_f method to add trial-specific F contrasts
apply_filter applies filter in design to data
autocorr method to set autocorrelation types for design
bf_dt method returns length of time bin for basis functions
block_cols method gets design columns for block (session / subject)
block_rows returns cell array of rows for each (subject/session) block
compute_contrasts compute and return results of contrast statistics
convert_vols method that converts vol structs in design and converts to format 'ver'
estimate estimate method - estimates GLM for SPM2 model
event_cols method gets design columns for single event
event_onsets method gets onsets and durations for event/session
event_regressor method gets estimated regressor for single event
event_specs method to return event specifications for all event in model
event_x_fir method to return FIR design matrix columns for session
fill fills missing entries from SPM FMRI design matrix
fwhm method returns FWHM, or empty if not available
get_images method to get image vols from design
has_autocorr returns 1 if object contains autocorrelation specification
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images
has_whitener returns 1 if design has whitening filter
mardo_2 class constructor for SPM2 MarsBaR design object
mars_spm_graph Graphical display of adjusted data
modality method returns modality of design
save_spm method to save design as SPM format design structure
savestruct saves data in def_struct into .mat file with variable name SPM
set_images method to set image vols to design
tr method returns TR in seconds, or empty if not available
ui_build method to create / fill design via GUI
ui_get_event method to select an event
ui_get_filter method to get filter via GUI
ui_report method for SPM2 design reporting
ui_report_fmri Interactive review of fMRI design matrix
autocorr method to set autocorrelation types for design
convert_vols method that converts vol structs in design and converts to format 'ver'
estimate estimate method - estimates GLM for SPM2 model
fill fills missing entries from SPM FMRI design matrix
mardo_5 class constructor for SPM5 MarsBaR design object
ui_build method to create / fill design via GUI
add_trial_f method to add trial-specific F contrasts
apply_filter applies filter in design to data
bf_dt method returns length of time bin for basis functions
block_cols method gets design columns for block (session / subject)
block_rows returns cell array of rows for each (subject/session) block
compute_contrasts compute and return stats
convert_vols method that converts vol structs in design and converts to format 'ver'
estimate estimate method - estimates GLM for SPM99 model
event_cols method gets design columns for single event
event_onsets method gets (estimated) onsets and durations for event/session
event_regressor method gets estimated regressor for single event
event_specs method to return event specifications for all event in model
event_x_fir method to return FIR design matrix columns for session
fill fills missing entries from SPM FMRI design matrix
fwhm method returns FWHM, or empty if not available
get_images method to get image vols from design
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images
mardo_99 class constructor for SPM99 MarsBaR design object
mars_spm_graph Graphical display of adjusted data
modality method returns modality of design
save_spm method to save design as SPM format design structure
set_images method to set image vols into design
tr method returns TR in seconds, or empty if not available
ui_build method to create / fill design via GUI
ui_get_event method to select an event
ui_get_filter method to get filter via GUI
ui_report mathod for SPM99 design reporting
ui_report_fmri Interactive review of fMRI design matrix
SOURCE CODE
function res = des_struct(obj, Struct)
% get/set method for des_struct field
%
% $Id$
if nargin > 1
  obj.des_struct = Struct;
  res = obj;
else
  res = obj.des_struct;
end