Description of descrip
Home > marsbar > @mardo > descrip.m
descrip
PURPOSE
method gets cell string description of design
SYNOPSIS
function strs = descrip(D)
DESCRIPTION
 method gets cell string description of design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
isfield method to overload isfield for mardo objects
mars_struct multifunction function for manipulating structures
This function is called by:
summary method returns cell array of strings describing design
ui_get_filter method to get filter via GUI
ui_get_filter method to get filter via GUI
display display - method
get_marsy gets data in ROIs from images
domaths helper function to do maths on matrix object
summary_descrip get/set method for summary data description
mars_build_roi builds ROIs via the SPM GUI
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function strs = descrip(D)
% method gets cell string description of design
%
% $Id$
SPM = des_struct(D);
strs = {'Not specified'};
if ~isfield(SPM, 'xsDes');
  return
end
strs = mars_struct('celldisp', SPM.xsDes);