Description of design_matrix
Home > marsbar > @mardo > design_matrix.m
design_matrix
PURPOSE
method returns design matrix from design
SYNOPSIS
function X = design_matrix(D)
DESCRIPTION
 method returns design matrix from design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
event_fitted_fir method to compute fitted event time courses using FIR
ui_ft_design_data method plots FT of design and data to graphics window
unfiltered_efficiency Calculate unfiltered efficiency for given SPM design and contrast
SOURCE CODE
function X = design_matrix(D)
% method returns design matrix from design
%
% $Id$
SPM = des_struct(D);
X   = mars_struct('getifthere', SPM, 'xX', 'X');