Description of error_df
Home > marsbar > @mardo > error_df.m
error_df
PURPOSE
method returns error df from design
SYNOPSIS
function e = error_df(D)
DESCRIPTION
 method returns error df from design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
run_tutorial MarsBaR batch script to show off MarsBaR batching
SOURCE CODE
function e = error_df(D)
% method returns error df from design
%
% $Id$
SPM = des_struct(D);
e   = mars_struct('getifthere', SPM, 'xX', 'erdf');