Description of event_types_named
Home > marsbar > @mardo > event_types_named.m
event_types_named
PURPOSE
method returns event types structures for events with same names
SYNOPSIS
function et = event_types_named(D)
DESCRIPTION
 method returns event types structures for events with same names
 FORMAT et = event_types_named(D)
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
event_specs method to return event specifications for all event in model
event_specs method to return event specifications for all event in model
This function is called by:
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function et = event_types_named(D)
% method returns event types structures for events with same names
% FORMAT et = event_types_named(D)
%
% $Id$
[e_s enames] = event_specs(D);
ets = unique(enames);
for e = 1:length(ets)
  et(e).name = ets{e};
  in_evs = ismember(enames, ets{e});
  et(e).e_spec = e_s(:, in_evs);
end