Description of event_types
Home > marsbar > @mardo > event_types.m
event_types
PURPOSE
method to get / set event types for design
SYNOPSIS
function res = event_types(D, et)
DESCRIPTION
 method to get / set event types for design
 FORMAT et = event_types(D)
 to return event types for design
 FORMAT D  = event_types(D, et)
 to set event types for design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
pr_refresh_et Refreshes data and display of event type window after edit
ui_et_edit method to edit invidual event types in design
ui_et_edit_cb method to handle callbacks from ui_et_edit
ui_event_types ui method for selection / editing of event types
ui_event_types_cb method to handle callbacks from ui_event_types
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function res = event_types(D, et)
% method to get / set event types for design
% FORMAT et = event_types(D)
% to return event types for design
%
% FORMAT D  = event_types(D, et)
% to set event types for design
%
% $Id$
SPM = des_struct(D);
if nargin < 2
  % get
  res = mars_struct('getifthere', SPM, 'event_types');
else
  % set
  SPM.event_types = et;
  res = des_struct(D, SPM);
end