Description of flip_images
Home > marsbar > @mardo > flip_images.m
flip_images
PURPOSE
flips images in design
SYNOPSIS
function o = flip_images(o)
DESCRIPTION
 flips images in design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
has_images returns 1 if design contains images, NaN if not known
get_images method to get image vols from design
has_images returns 1 if design contains images
set_images method to set image vols to design
get_images method to get image vols from design
has_images returns 1 if design contains images
set_images method to set image vols into design
This function is called by:
mardo mardo - class constructor for MarsBaR design object
SOURCE CODE
function o = flip_images(o)
% flips images in design
%
% $Id$
if ~has_images(o), return, end
VY = get_images(o);
M = diag([-1 1 1 1]);
for i = 1:length(VY)
  VY(i).mat = M * VY(i).mat;
end
o = set_images(o, VY);