Description of get_contrasts
Home > marsbar > @mardo > get_contrasts.m
get_contrasts
PURPOSE
method to get contrasts from design object
SYNOPSIS
function xCon = get_contrasts(D)
DESCRIPTION
 method to get contrasts from design object
 FORMAT xCon = get_contrasts(D)
 Returns contrast structure from design
 See ui_get_contrasts for UI to get individual contrasts
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
adjusted_data Return adjusted data for estimated design and contrast no
contrasts method to get or set contrasts
get_contrast_by_name get named contrast(s) from design contrast structure
refresh_contrasts method to refresh contrasts to match design
ui_get_contrasts SPM contrast UI, wrapped for MarsBaR
unfiltered_efficiency Calculate unfiltered efficiency for given SPM design and contrast
convert_vols method that converts vol structs in design and converts to format 'ver'
mars_spm_graph Graphical display of adjusted data
convert_vols method that converts vol structs in design and converts to format 'ver'
mars_spm_graph Graphical display of adjusted data
marsbar Startup, callback and utility routine for Marsbar
test_rig runs tests on MarsBaR using specified designs
SOURCE CODE
function xCon = get_contrasts(D)
% method to get contrasts from design object
% FORMAT xCon = get_contrasts(D)
%
% Returns contrast structure from design
% See ui_get_contrasts for UI to get individual contrasts
%
% $Id$
SPM = des_struct(D);
xCon = mars_struct('getifthere', SPM, 'xCon');