Description of get_contrast_by_name
Home > marsbar > @mardo > get_contrast_by_name.m
get_contrast_by_name
PURPOSE
get named contrast(s) from design contrast structure
SYNOPSIS
function [xc, ic] = get_contrast_by_name(D, cname)
DESCRIPTION
 get named contrast(s) from design contrast structure
 FORMAT [xc, ic] = get_contrast_by_name(D, cname)
 D      - design object
 cname  - contrast name(s) (string or cell array)
 Returns
 xc     - xCon structure containing only named contrast
 ic     - index of contrast in design contrast structure
 e.g. [con ic] = get_named_contrasts(D, 'effects of interest');
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
get_contrasts method to get contrasts from design object
isempty overloaded isempty method for mardo object
This function is called by:
run_tutorial MarsBaR batch script to show off MarsBaR batching
SOURCE CODE
function [xc, ic] = get_contrast_by_name(D, cname)
% get named contrast(s) from design contrast structure
% FORMAT [xc, ic] = get_contrast_by_name(D, cname)
%
% D      - design object
% cname  - contrast name(s) (string or cell array)
%
% Returns
% xc     - xCon structure containing only named contrast
% ic     - index of contrast in design contrast structure
%
% e.g. [con ic] = get_named_contrasts(D, 'effects of interest');
%
% $Id$
if nargin < 2
  error('Need contrast name(s)');
end
if ischar(cname)
  cname = cellstr(cname);
end
xc = get_contrasts(D);
if isempty(xc)
  ic = [];
else
  ic = find(ismember({xc(:).name}, cname));
end
xc = xc(ic);