Description of get_vol_field
Home > marsbar > @mardo > get_vol_field.m
get_vol_field
PURPOSE
method to get named field, containing or referring to vol structs
SYNOPSIS
function V = get_vol_field(D, fieldn)
DESCRIPTION
 method to get named field, containing or referring to vol structs
 FORMAT V = get_vol_field(D, fieldn)
 D        - design object
 fieldn   - field name
 Returns
 V        - vol struct
 e.g Vbeta = get_vol_field(D, 'Vbeta');
 We need to deal with the fact that vol fields can be char or vol_structs.
 SPM99, for good reason, stored the design structs from the results of the
 estimation as file names, which then had to be remapped with spm_vol to
 get the vol structs.  The good reason was that this avoided
 byte-swapping problems if the design was copied to another system.
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
full_vol returns vol with full path, from vols, or image names
isfield method to overload isfield for mardo objects
This function is called by:
SOURCE CODE
function V = get_vol_field(D, fieldn)
% method to get named field, containing or referring to vol structs
% FORMAT V = get_vol_field(D, fieldn)
%
% D        - design object
% fieldn   - field name
%
% Returns
% V        - vol struct
%
% e.g Vbeta = get_vol_field(D, 'Vbeta');
%
% We need to deal with the fact that vol fields can be char or vol_structs.
% SPM99, for good reason, stored the design structs from the results of the
% estimation as file names, which then had to be remapped with spm_vol to
% get the vol structs.  The good reason was that this avoided
% byte-swapping problems if the design was copied to another system.
%
% $Id$
if nargin < 2
  error('Need field name');
end
SPM = des_struct(D);
if ~isfield(SPM, fieldn)
  error([ fieldn ' is not a field in design']);
end
V = getfield(SPM, fieldn);
V = full_vol(D, V);