Description of has_images
Home > marsbar > @mardo > has_images.m
has_images
PURPOSE
returns 1 if design contains images, NaN if not known
SYNOPSIS
function tf = has_images(o)
DESCRIPTION
 returns 1 if design contains images, NaN if not known
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cd_images method for changing path to image files in design
flip_images flips images in design
image_names method returning image file names for design
mardo mardo - class constructor for MarsBaR design object
prefix_images method for adding or removing prefix from file names in design
summary method returns cell array of strings describing design
save_spm method to save design as SPM format design structure
get_marsy gets data in ROIs from images
mars_image_scaling get image scaling data for images, maybe via SPM design
marsbar Startup, callback and utility routine for Marsbar
test_rig runs tests on MarsBaR using specified designs
SOURCE CODE
function tf = has_images(o)
% returns 1 if design contains images, NaN if not known
%
% $Id$
tf = NaN;