Description of images
Home > marsbar > @mardo > images.m
images
PURPOSE
method to get or set images
SYNOPSIS
function r = images(o, imgs)
DESCRIPTION
 method to get or set images
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
get_images method to get image vols from design
set_images method to set image vols to design
get_images method to get image vols from design
set_images method to set image vols into design
This function is called by:
SOURCE CODE
function r = images(o, imgs)
% method to get or set images
%
% $Id$
if nargin < 2
  r = get_images(o);
else
  r = set_images(o, imgs);
end