Description of image_names
Home > marsbar > @mardo > image_names.m
image_names
PURPOSE
method returning image file names for design
SYNOPSIS
function P = image_names(D)
DESCRIPTION
 method returning image file names for design
 Returns cell array of same dimension of image list
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
has_images returns 1 if design contains images, NaN if not known
get_images method to get image vols from design
has_images returns 1 if design contains images
get_images method to get image vols from design
has_images returns 1 if design contains images
This function is called by:
ui_report method for SPM2 design reporting
mardo_2 method to convert SPM2 design to SPM99 design
ui_report mathod for SPM99 design reporting
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function P = image_names(D)
% method returning image file names for design
% Returns cell array of same dimension of image list
%
% $Id$
P = {};
if has_images(D)
  VY = get_images(D);
  P = reshape({VY.fname},size(VY));
end