Description of is_fmri
Home > marsbar > @mardo > is_fmri.m
is_fmri
PURPOSE
method returns 1 if this is an fmri design
SYNOPSIS
function tf = is_fmri(D)
DESCRIPTION
 method returns 1 if this is an fmri design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
modality method returns modality of design
modality method returns modality of design
modality method returns modality of design
This function is called by:
event_fitted method to compute fitted event time course
event_fitted_fir method to compute fitted event time courses using FIR
event_signal method to compute % signal change from fMRI events
residuals method returns residuals from model
summary method returns cell array of strings describing design
ui_ft_design_data method plots FT of design and data to graphics window
apply_filter applies filter in design to data
autocorr method to set autocorrelation types for design
block_cols method gets design columns for block (session / subject)
can_mars_estimate method returns 1 if design can be estimated in MarsBaR
event_cols method gets design columns for single event
event_onsets method gets onsets and durations for event/session
event_regressor method gets estimated regressor for single event
event_specs method to return event specifications for all event in model
fill fills missing entries from SPM FMRI design matrix
ui_get_event method to select an event
autocorr method to set autocorrelation types for design
fill fills missing entries from SPM FMRI design matrix
apply_filter applies filter in design to data
block_cols method gets design columns for block (session / subject)
can_mars_estimate method returns 1 if design can be estimated in MarsBaR
event_cols method gets design columns for single event
event_onsets method gets (estimated) onsets and durations for event/session
event_regressor method gets estimated regressor for single event
event_specs method to return event specifications for all event in model
fill fills missing entries from SPM FMRI design matrix
save_spm method to save design as SPM format design structure
ui_get_event method to select an event
mars_image_scaling get image scaling data for images, maybe via SPM design
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function tf = is_fmri(D)
% method returns 1 if this is an fmri design
%
% $Id$
tf = strcmp(modality(D), 'fmri');