Description of is_mars_estimated
Home > marsbar > @mardo > is_mars_estimated.m
is_mars_estimated
PURPOSE
method returns 1 if design has been estimated in MarsBaR
SYNOPSIS
function tf = is_mars_estimated(D)
DESCRIPTION
 method returns 1 if design has been estimated in MarsBaR
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
This function is called by:
adjusted_data Return adjusted data for estimated design and contrast no
betas method to get estimated betas
event_fitted method to compute fitted event time course
event_fitted_fir method to compute fitted event time courses using FIR
event_signal method to compute % signal change from fMRI events
mardo mardo - class constructor for MarsBaR design object
residuals method returns residuals from model
summary method returns cell array of strings describing design
mars_spm_graph Graphical display of adjusted data
mars_spm_graph Graphical display of adjusted data
mars_arm_call services callbacks from marmoire object set functions
SOURCE CODE
function tf = is_mars_estimated(D)
% method returns 1 if design has been estimated in MarsBaR
%
% $Id$
tf = isfield(D.des_struct, 'marsY');