Description of is_valid
Home > marsbar > @mardo > is_valid.m
is_valid
PURPOSE
returns 1 if object contains valid SPM/MarsBaR design
SYNOPSIS
function tf = is_valid(o)
DESCRIPTION
 returns 1 if object contains valid SPM/MarsBaR design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
isfield method to overload isfield for mardo objects
This function is called by:
mars_arm_call services callbacks from marmoire object set functions
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function tf = is_valid(o)
% returns 1 if object contains valid SPM/MarsBaR design
%
% $Id$
tf = isfield(des_struct(o), 'xX');