Description of isempty
Home > marsbar > @mardo > isempty.m
isempty
PURPOSE
overloaded isempty method for mardo object
SYNOPSIS
function tf = isempty(o)
DESCRIPTION
 overloaded isempty method for mardo object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
This function is called by:
add_contrasts method to add contrast definitions to design
block_means method returns means for blocks in design
cd_images method for changing path to image files in design
event_fitted method to compute fitted event time course
event_fitted_fir method to compute fitted event time courses using FIR
event_signal method to compute % signal change from fMRI events
full_vol returns vol with full path, from vols, or image names
get_contrast_by_name get named contrast(s) from design contrast structure
isempty overloaded isempty method for mardo object
mardo mardo - class constructor for MarsBaR design object
pr_ev_diff method to calculate event height for % signal change
stat_table gets Mars statistics and creates statistic table as cell array
swd_writable returns true if swd directory can be written to
ui_et_edit method to edit invidual event types in design
ui_et_edit_cb method to handle callbacks from ui_et_edit
ui_event_types ui method for selection / editing of event types
ui_event_types_cb method to handle callbacks from ui_event_types
ui_ft_design_data method plots FT of design and data to graphics window
ui_get_contrasts SPM contrast UI, wrapped for MarsBaR
apply_filter applies filter in design to data
convert_vols method that converts vol structs in design and converts to format 'ver'
estimate estimate method - estimates GLM for SPM2 model
event_x_fir method to return FIR design matrix columns for session
fill fills missing entries from SPM FMRI design matrix
mardo_2 class constructor for SPM2 MarsBaR design object
mars_spm_graph Graphical display of adjusted data
my_design returns 1 if design looks like it is of SPM99 type
pr_estimate Estimation of a General Linear Model
pr_spm_gpdf Probability Density Function (PDF) of Gamma distribution
pr_spm_hrf returns a hemodynamic response function
pr_spm_ui MarsBaR: setting up the general linear model for independent data
save_spm method to save design as SPM format design structure
ui_report method for SPM2 design reporting
convert_vols method that converts vol structs in design and converts to format 'ver'
estimate estimate method - estimates GLM for SPM2 model
fill fills missing entries from SPM FMRI design matrix
mardo_5 class constructor for SPM5 MarsBaR design object
my_design returns 1 if design looks like it is of SPM5 / 8 type
pr_estimate Estimation of a General Linear Model
pr_spm_cat converts a cell array into a matrix
pr_spm_fileparts Like fileparts, but separates off a comma separated list at the end
pr_spm_gpdf Probability Density Function (PDF) of Gamma distribution
pr_spm_justify Justify text
pr_spm_reml ReML estimation of covariance components from y*y'
pr_spm_select File selector
pr_spm_ui MarsBaR: Setting up the general linear model for independent data
apply_filter applies filter in design to data
convert_vols method that converts vol structs in design and converts to format 'ver'
event_x_fir method to return FIR design matrix columns for session
fill fills missing entries from SPM FMRI design matrix
mardo_2 method to convert SPM2 design to SPM99 design
mardo_99 class constructor for SPM99 MarsBaR design object
mars_spm_graph Graphical display of adjusted data
my_design returns 1 if design looks like it is of SPM99 type
pr_estimate Estimation of a General Linear Model
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_get_filter gets filter using spm_fmri_spm_ui routines
pr_spm_filter contruct and/or apply high and/or low pass filter
pr_spm_get_ons returns onset times for events
pr_spm_hrf returns a hemodynamic response function
pr_spm_ui MarsBaR: setting up the general linear model for independent data
save_spm method to save design as SPM format design structure
ui_report mathod for SPM99 design reporting
add_item add item to armoire
do_set private function to set data into item
get_item_data get data for item
item_exists returns true if there is an item of this name
pr_is_nan
pr_is_nix
pr_isempty private function returns 1 if there is no data, or filename
save_item_data save data for item to file
are_same returns 1 if rois are the same
back2base back2base method - check for spacebase, transform thereto
display display - method
get_marsy gets data in ROIs from images
getdata getdata method - fetches time series data for ROI from images
maroi maroi - class constructor for umbrella ROI object
my_classdata my_classdata method - sets/gets class data
my_loadroi my_loadroi function - loads ROI from file, sets source field
my_roifname changes fname to appropriate ROI format
realpts realpts method - returns 3xN XYZ matrix in mm
rle run length encoding method
saveroi saveroi method - checks fname, sets source field, saves object
is_empty_roi returns 1 if ROI contains no volume
loadobj loadobj method - reloads matrix from img file
maroi_image maroi_image - class constructor
my_vol_func checks vol and func, returns processed image matrix or error
maroi_matrix maroi_matrix - class constructor
rebase rebase method - returns data from maroi_matrix in new space
getvals returns vals for pointlist object
is_empty_roi is_empty_roi - returns true if ROI contains no volume
maroi_pointlist maroi_pointlist - class constructor
my_voxblock returns voxel block and modified mat file for pointlist
c_o_m c_o_m method - calculates centre of mass
maroi_matrix method to convert shape objects to maroi_matrix objects
is_empty_roi is_empty_roi - returns true if ROI contains no volume
mars_space mars_space - class constructor for space defining object
can_summarize returns 1 if object contains enough information to be summarized
join joins marsy objects into one object
marsy Class constructor for marsy: the MarsBaR data object
pr_sum_func creates summary stats for region data
region gets / sets data for region or regions
region_name method gets or sets data for region name
resummarize recalculate summary data if possible
summary method returns cell array of strings describing marsy object
summary_data method to get summary data, maybe set sumfunc
ui_plot method plots data in various formats
xyz gets XYZ coordinates for region
configure_er_model batch script wrapper to configure model for MarsBaR ER data
estimate_er_model SPM estimate of ER model, and add contrast to ER model
get_subjroot FORMAT subjroot = get_subjroot()
run_tutorial MarsBaR batch script to show off MarsBaR batching
mars_arm wrapper function for MarsBaR marmoire object
mars_arm_call services callbacks from marmoire object set functions
mars_armoire multifunction function to get/set various stores of stuff
mars_blob2roi saves ROI for cluster in xSPM structure, containing point pt
mars_blobs2rois creates ROIs from spm_results_ui SPM
mars_build_roi builds ROIs via the SPM GUI
mars_display_roi utility routines for display of ROIs in graphic window
mars_get_option Get option subfield as named by ``varargin``.
mars_image_scaling get image scaling data for images, maybe via SPM design
mars_img2rois creates ROIs from cluster image or image containing ROIs defined by unique nos
mars_new_space make a new image space to contain image with rotations etc
mars_options options utility routines
mars_orthviews Display Orthogonal Views of a Normalized Image
mars_rois2img creates cluster or number labelled ROI image from ROIs
mars_struct multifunction function for manipulating structures
mars_uifile wrapper for matlab uiputfile/getfile; to resolve version differences
mars_utils collection of useful utility functions for MarsBaR etc
mars_vol_check FORMAT [samef, msg, chgf] = mars_vol_check(V1, V2, ...)
marsbar Startup, callback and utility routine for Marsbar
make_contents MAKECONTENTS makes Contents file, usually in current working directory.
pre_release Runs pre-release export, cleanup
test_rig runs tests on MarsBaR using specified designs
mars_veropts returns SPM version specific parameters
mars_veropts returns SPM version specific parameters
spm_get compatibility function to allow spm_get calls with SPM5
spm_read_hdr SPM2 routine to read (SPM customised) Analyze header
spm_write_plane Write a transverse plane of image data.
spm_write_vol Write an image volume to disk, setting scales and offsets as appropriate
SOURCE CODE
function tf = isempty(o)
% overloaded isempty method for mardo object
%
% $Id$
tf = isempty(o.des_struct);