Description of isfield
Home > marsbar > @mardo > isfield.m
isfield
PURPOSE
method to overload isfield for mardo objects
SYNOPSIS
function result = isfield(this, fieldn)
DESCRIPTION
 method to overload isfield for mardo objects
 isfield for mardo objects replies according to the contents of
 the des_struct field
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isfield method to overload isfield for mardo objects
This function is called by:
add_contrasts method to add contrast definitions to design
descrip method gets cell string description of design
event_fitted_fir method to compute fitted event time courses using FIR
get_data method to get data from design object
get_vol_field method to get named field, containing or referring to vol structs
has_contrasts method returns 1 if design has contrasts
has_filter returns 1 if object contains filter
is_mars_estimated method returns 1 if design has been estimated in MarsBaR
is_marsed returns 1 if design has been processed with MarsBaR
is_spm_estimated returns 1 if design has been estimated in SPM
is_valid returns 1 if object contains valid SPM/MarsBaR design
isfield method to overload isfield for mardo objects
mardo mardo - class constructor for MarsBaR design object
mars_tag returns, or sets, Mars tagging structure in design
pr_refresh_et Refreshes data and display of event type window after edit
savestruct saves data in def_struct as variables in .mat file
set_contrasts method to set contrasts into design object
ui_event_types ui method for selection / editing of event types
ui_ft_design_data method plots FT of design and data to graphics window
ui_get_contrasts SPM contrast UI, wrapped for MarsBaR
add_trial_f method to add trial-specific F contrasts
apply_filter applies filter in design to data
autocorr method to set autocorrelation types for design
block_rows returns cell array of rows for each (subject/session) block
estimate estimate method - estimates GLM for SPM2 model
event_x_fir method to return FIR design matrix columns for session
fill fills missing entries from SPM FMRI design matrix
has_autocorr returns 1 if object contains autocorrelation specification
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images
has_whitener returns 1 if design has whitening filter
mardo_2 class constructor for SPM2 MarsBaR design object
mardo_99 method to convert SPM2 design to SPM99 design
mars_spm_graph Graphical display of adjusted data
my_design returns 1 if design looks like it is of SPM99 type
pr_estimate Estimation of a General Linear Model
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_get_filter gets filter using spm_fmri_spm_ui routines
pr_spm_filter Removes low frequency confounds X0
pr_spm_get_bf fills in basis function structure
savestruct saves data in def_struct into .mat file with variable name SPM
ui_get_filter method to get filter via GUI
ui_report method for SPM2 design reporting
autocorr method to set autocorrelation types for design
estimate estimate method - estimates GLM for SPM2 model
fill fills missing entries from SPM FMRI design matrix
my_design returns 1 if design looks like it is of SPM5 / 8 type
pr_estimate Estimation of a General Linear Model
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_get_filter gets filter using spm_fmri_spm_ui routines
pr_spm_filter Removes low frequency confounds X0
pr_spm_get_bf fills in basis function structure
pr_spm_select File selector
add_trial_f method to add trial-specific F contrasts
apply_filter applies filter in design to data
block_rows returns cell array of rows for each (subject/session) block
event_x_fir method to return FIR design matrix columns for session
fill fills missing entries from SPM FMRI design matrix
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images
mardo_2 method to convert SPM2 design to SPM99 design
mars_spm_graph Graphical display of adjusted data
my_design returns 1 if design looks like it is of SPM99 type
pr_estimate Estimation of a General Linear Model
pr_get_filter gets filter using spm_fmri_spm_ui routines
pr_spm_filter contruct and/or apply high and/or low pass filter
ui_get_filter method to get filter via GUI
ui_report mathod for SPM99 design reporting
ui_report_fmri Interactive review of fMRI design matrix
do_save method to save data for item
do_set private function to set data into item
loadobj loadobj method - fills fields needed for backwards compatibility
maroi maroi - class constructor for umbrella ROI object
my_classdata my_classdata method - sets/gets class data
my_loadroi my_loadroi function - loads ROI from file, sets source field
maroi_image maroi_image - class constructor
my_vol_func checks vol and func, returns processed image matrix or error
loadobj loadobj function - undoes run length encoding if appropriate
as_summary_only returns object with region data removed
block_rows gets/sets cell array of rows for each (subject/session) block
is_summarized returns 1 if object contains calculated summary data
is_summary_only method returns 1 if object only contains summary data
is_valid method returns 1 if object contains valid data
marsy Class constructor for marsy: the MarsBaR data object
region gets / sets data for region or regions
region_size method to get size of specified region data
split method splits regions in object into separate objects
sumfunc method to get or set sumfunc
summary_data method to get summary data, maybe set sumfunc
summary_descrip get/set method for summary data description
summary_info get/set method for summary data info
summary_size method returns number of time points x number of regions
ui_plot method plots data in various formats
xyz gets XYZ coordinates for region
estimate_er_model SPM estimate of ER model, and add contrast to ER model
mars_arm wrapper function for MarsBaR marmoire object
mars_armoire multifunction function to get/set various stores of stuff
mars_display_roi utility routines for display of ROIs in graphic window
mars_options options utility routines
mars_orthviews Display Orthogonal Views of a Normalized Image
mars_struct multifunction function for manipulating structures
mars_vol_utils collection of useful utility functions for vol structs
marsbar Startup, callback and utility routine for Marsbar
spm_write_plane Write a transverse plane of image data.
spm_write_vol Write an image volume to disk, setting scales and offsets as appropriate
SOURCE CODE
function result = isfield(this, fieldn)
% method to overload isfield for mardo objects
% isfield for mardo objects replies according to the contents of
% the des_struct field
%
% $Id$
result =isfield(this.des_struct, fieldn);