Description of mars_tag
Home > marsbar > @mardo > mars_tag.m
mars_tag
PURPOSE
returns, or sets, Mars tagging structure in design
SYNOPSIS
function res = mars_tag(o, data)
DESCRIPTION
 returns, or sets, Mars tagging structure in design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
data method to get or set data object
isfield method to overload isfield for mardo objects
This function is called by:
mardo mardo - class constructor for MarsBaR design object
SOURCE CODE
function res = mars_tag(o, data)
% returns, or sets, Mars tagging structure in design
%
% $Id$
if nargin > 1 % set
  res = o;
  res.des_struct.xMars = data;
  return
end
if isfield(o.des_struct, 'xMars') % get
  res = o.des_struct.xMars;
else
  res = [];
end