Description of modality
Home > marsbar > @mardo > modality.m
modality
PURPOSE
method returns modality of design
SYNOPSIS
function mod_str = modality(D)
DESCRIPTION
 method returns modality of design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
is_fmri method returns 1 if this is an fmri design
summary method returns cell array of strings describing design
add_trial_f method to add trial-specific F contrasts
block_rows returns cell array of rows for each (subject/session) block
ui_report method for SPM2 design reporting
add_trial_f method to add trial-specific F contrasts
block_rows returns cell array of rows for each (subject/session) block
ui_report mathod for SPM99 design reporting
SOURCE CODE
function mod_str = modality(D)
% method returns modality of design
%
% $Id$
mod_str = 'unknown';