Description of n_time_points
Home > marsbar > @mardo > n_time_points.m
n_time_points
PURPOSE
get number of time_points in design
SYNOPSIS
function n = n_time_points(o)
DESCRIPTION
 get number of time_points in design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
This function is called by:
ui_ft_design_data method plots FT of design and data to graphics window
apply_filter applies filter in design to data
estimate estimate method - estimates GLM for SPM2 model
estimate estimate method - estimates GLM for SPM2 model
estimate estimate method - estimates GLM for SPM99 model
block_rows gets/sets cell array of rows for each (subject/session) block
join joins marsy objects into one object
region gets / sets data for region or regions
summary method returns cell array of strings describing marsy object
mars_arm_call services callbacks from marmoire object set functions
SOURCE CODE
function n = n_time_points(o)
% get number of time_points in design
%
% $Id$
SPM = des_struct(o);
n = size(SPM.xX.X, 1);