Description of native_vol_ver
Home > marsbar > @mardo > native_vol_ver.m
native_vol_ver
PURPOSE
return string specifying native vol type
SYNOPSIS
function res = native_vol_ver(obj)
DESCRIPTION
 return string specifying native vol type
 $Id: verbose.m 87 2004-01-06 01:48:35Z matthewbrett $
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
savestruct saves data in def_struct as variables in .mat file
save_spm method to save design as SPM format design structure
savestruct saves data in def_struct into .mat file with variable name SPM
save_spm method to save design as SPM format design structure
SOURCE CODE
function res = native_vol_ver(obj)
% return string specifying native vol type
%
% $Id: verbose.m 87 2004-01-06 01:48:35Z matthewbrett $
res = '99';