Description of paramfields
Home > marsbar > @mardo > paramfields.m
paramfields
PURPOSE
returns struct with fields from maroi object useful for copying objects
SYNOPSIS
function params = paramfields(o)
DESCRIPTION
 returns struct with fields from maroi object useful for copying objects
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mardo_99 method to convert SPM2 design to SPM99 design
mardo_2 method to convert SPM2 design to SPM99 design
maroi_matrix maroi_matrix - class constructor
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
maroi_matrix method to convert shape objects to maroi_matrix objects
SOURCE CODE
function params = paramfields(o)
% returns struct with fields from maroi object useful for copying objects
%
% $Id$
params = struct('des_struct', o.des_struct,...
        'flip_option', o.flip_option,...
        'verbose', o.verbose);