Description of refresh_contrasts
Home > marsbar > @mardo > refresh_contrasts.m
refresh_contrasts
PURPOSE
method to refresh contrasts to match design
SYNOPSIS
function o = refresh_contrasts(o)
DESCRIPTION
 method to refresh contrasts to match design
CROSS-REFERENCE INFORMATION
This function calls:
get_contrasts method to get contrasts from design object
set_contrasts method to set contrasts into design object
This function is called by:
mardo mardo - class constructor for MarsBaR design object
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function o = refresh_contrasts(o)
% method to refresh contrasts to match design
o = set_contrasts(o, get_contrasts(o));