Description of residuals
Home > marsbar > @mardo > residuals.m
residuals
PURPOSE
method returns residuals from model
SYNOPSIS
function r = residuals(D)
DESCRIPTION
 method returns residuals from model
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
get_data method to get data from design object
has_filter returns 1 if object contains filter
is_fmri method returns 1 if this is an fmri design
is_mars_estimated method returns 1 if design has been estimated in MarsBaR
apply_filter applies filter in design to data
block_rows returns cell array of rows for each (subject/session) block
has_filter returns 1 if object contains filter
apply_filter applies filter in design to data
block_rows returns cell array of rows for each (subject/session) block
has_filter returns 1 if object contains filter
block_rows gets/sets cell array of rows for each (subject/session) block
is_summarized returns 1 if object contains calculated summary data
marsy Class constructor for marsy: the MarsBaR data object
region_name method gets or sets data for region name
resummarize recalculate summary data if possible
summary_data method to get summary data, maybe set sumfunc
summary_descrip get/set method for summary data description
summary_info get/set method for summary data info
This function is called by:
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function r = residuals(D)
% method returns residuals from model
%
% $Id$
if ~is_mars_estimated(D)
  error('Need estimated model');
end
Y = get_data(D);
if ~is_summarized(Y)
  Y = resummarize(Y);
end
if ~is_summarized(Y)
  error('Cannot get summarized data from model data');
end
y = summary_data(Y);
if is_fmri(D)
  if ~has_filter(D)
    error('FMRI design lacks filter');
  end
  y = apply_filter(D, y);
end
SPM = des_struct(D);
r   = marsy(spm_sp('r',SPM.xX.xKXs,y), ...
        region_name(Y), ...
        struct('info',   summary_info(Y),...
           'descrip', ['Residuals for ' summary_descrip(Y)],...
           'block_rows', {block_rows(D)}));