Description of savestruct
Home > marsbar > @mardo > savestruct.m
savestruct
PURPOSE
saves data in def_struct as variables in .mat file
SYNOPSIS
function savestruct(obj, filename)
DESCRIPTION
 saves data in def_struct as variables in .mat file
 FORMAT savestruct(object, matname)
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
isfield method to overload isfield for mardo objects
native_vol_ver return string specifying native vol type
savestruct saves data in def_struct as variables in .mat file
convert_vols method that converts vol structs in design and converts to format 'ver'
savestruct saves data in def_struct into .mat file with variable name SPM
convert_vols method that converts vol structs in design and converts to format 'ver'
native_vol_ver return string specifying native vol type
convert_vols method that converts vol structs in design and converts to format 'ver'
savestruct saves data in y_struct as variables in .mat file
y_struct get/set method for y_struct field
savestruct saves data in structure as variables in .mat file
This function is called by:
savestruct saves data in def_struct as variables in .mat file
save_spm method to save design as SPM format design structure
do_save method to save data for item
savestruct saves data in y_struct as variables in .mat file
mars_armoire multifunction function to get/set various stores of stuff
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function savestruct(obj, filename)
% saves data in def_struct as variables in .mat file
% FORMAT savestruct(object, matname)
%
% $Id$
if nargin ~= 2
  error('Need matfile name');
end
% allow args to be in reverse order
if ischar(obj)
  tmp = obj;
  obj = filename;
  filename = tmp;
end
% Convert vols to native format
obj = convert_vols(obj, native_vol_ver(obj));
% unobjectify marsy object before save
SPM = des_struct(obj);
if isfield(SPM, 'marsY')
  SPM.marsY = y_struct(SPM.marsY);
end
savestruct(SPM, filename)
return