Description of set_data
Home > marsbar > @mardo > set_data.m
set_data
PURPOSE
method to set data for design object
SYNOPSIS
function D = set_data(D, d)
DESCRIPTION
 method to set data for design object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
marsy Class constructor for marsy: the MarsBaR data object
This function is called by:
data method to get or set data object
marsy_data method to get or set marsy data
SOURCE CODE
function D = set_data(D, d)
% method to set data for design object
%
% $Id$
SPM = des_struct(D);
SPM.marsY = marsy(d);
D = des_struct(D, SPM);