Description of set_contrasts
Home > marsbar > @mardo > set_contrasts.m
set_contrasts
PURPOSE
method to set contrasts into design object
SYNOPSIS
function D = set_contrasts(D, C, refreshf)
DESCRIPTION
 method to set contrasts into design object
 D     - design
 C     - contrasts
           C can be a contrast structure, or a structure containing
           a contrast structure
 refreshf - if 1 then refresh contrasts with respect to design matrix
            structures in `D`. Default is 1
 Returns
 D     - design with contrasts set to C
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
add_contrasts method to add contrast definitions to design
des_struct get/set method for des_struct field
isfield method to overload isfield for mardo objects
This function is called by:
add_contrasts method to add contrast definitions to design
contrasts method to get or set contrasts
mardo mardo - class constructor for MarsBaR design object
refresh_contrasts method to refresh contrasts to match design
ui_get_contrasts SPM contrast UI, wrapped for MarsBaR
convert_vols method that converts vol structs in design and converts to format 'ver'
convert_vols method that converts vol structs in design and converts to format 'ver'
mars_arm_call services callbacks from marmoire object set functions
SOURCE CODE
function D = set_contrasts(D, C, refreshf)
% method to set contrasts into design object
%
% D     - design
% C     - contrasts
%           C can be a contrast structure, or a structure containing
%           a contrast structure
% refreshf - if 1 then refresh contrasts with respect to design matrix
%            structures in `D`. Default is 1
%
% Returns
% D     - design with contrasts set to C
%
% $Id$
if nargin < 2
  error('Need contrasts');
end
if nargin < 3
    refreshf = 1;
end
if isfield(C, 'xCon');
  C = C.xCon;
end
SPM = des_struct(D);
if refreshf
    % Use add contrasts routine to refresh contrasts
    SPM.xCon = [];
    D = des_struct(D, SPM);
    D = add_contrasts(D, C);
else % Hope for the best
    SPM.xCon = C;
    D = des_struct(D, SPM);
end