Description of set_vol_field
Home > marsbar > @mardo > set_vol_field.m
set_vol_field
PURPOSE
method to set named field, containing or referring to vol structs
SYNOPSIS
function D = set_vol_field(D, fieldn, imgs)
DESCRIPTION
 method to set named field, containing or referring to vol structs
 FORMAT D = get_vol_field(D, fieldn, imgs)
 D        - design object
 fieldn   - field name
 imgs     - image names or vol structs
 Returns
 D        - changed object
 e.g D = get_vol_field(D, 'Vbeta', Vbeta);
 We need to deal with the fact that vol fields can be char or vol_structs.
 SPM99, for good reason, stored the design structs from the results of the
 estimation as file names, which then had to be remapped with spm_vol to
 get the vol structs.  The good reason was that this avoided
 byte-swapping problems if the design was copied to another system.
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
design_vol returns vols in appropriate format for saving in design
design_vol returns vols in appropriate format for saving in design
This function is called by:
SOURCE CODE
function D = set_vol_field(D, fieldn, imgs)
% method to set named field, containing or referring to vol structs
% FORMAT D = get_vol_field(D, fieldn, imgs)
%
% D        - design object
% fieldn   - field name
% imgs     - image names or vol structs
%
% Returns
% D        - changed object
%
% e.g D = get_vol_field(D, 'Vbeta', Vbeta);
%
% We need to deal with the fact that vol fields can be char or vol_structs.
% SPM99, for good reason, stored the design structs from the results of the
% estimation as file names, which then had to be remapped with spm_vol to
% get the vol structs.  The good reason was that this avoided
% byte-swapping problems if the design was copied to another system.
%
% $Id$
if nargin < 2
  error('Need field name');
end
SPM = des_struct(D);
V = design_vol(D, imgs);
SPM = setfield(SPM, fieldn, V);
D = des_struct(D, SPM);