Description of summary
Home > marsbar > @mardo > summary.m
summary
PURPOSE
method returns cell array of strings describing design
SYNOPSIS
function strs = summary(D)
DESCRIPTION
 method returns cell array of strings describing design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
descrip method gets cell string description of design
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images, NaN if not known
is_fmri method returns 1 if this is an fmri design
is_mars_estimated method returns 1 if design has been estimated in MarsBaR
modality method returns modality of design
swd method to get/set design directory
type returns SPM version string corresponding to design type
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images
modality method returns modality of design
type returns SPM version string corresponding to design type
type returns SPM version string corresponding to design type
has_filter returns 1 if object contains filter
has_images returns 1 if design contains images
modality method returns modality of design
type returns SPM version string corresponding to design type
descrip name - returns / sets name value for object
This function is called by:
display display method for mardo objects
get_marsy gets data in ROIs from images
display display method for marsy objects
mars_arm wrapper function for MarsBaR marmoire object
SUBFUNCTIONS
function str = sf_recode(tf)
SOURCE CODE
function strs = summary(D)
% method returns cell array of strings describing design
%
% $Id$
strs{1} = sprintf('SPM working dir    \t%s',  swd(D));
strs{2} = sprintf('Design type:       \t%s',  type(D));
strs{3} = sprintf('Modality:          \t%s',  modality(D));
if is_fmri(D)
  tmp = sf_recode(has_filter(D));
else
  tmp = 'N/A';
end
strs{4} = sprintf('Has filter?:       \t%s',  tmp);
strs{5} = sprintf('Has images?:       \t%s',  ...
          sf_recode(has_images(D)));
strs{6} = sprintf('MarsBaR estimated?:\t%s', ...
          sf_recode(is_mars_estimated(D)));
strs = [strs {'Description:'}, descrip(D)];
return
function str = sf_recode(tf)
if isnan(tf), str = 'unknown';
elseif tf,    str = 'yes';
else          str = 'no';
end