Description of swd
Home > marsbar > @mardo > swd.m
swd
PURPOSE
method to get/set design directory
SYNOPSIS
function res = swd(D, dir)
DESCRIPTION
 method to get/set design directory
 FORMAT dir = swd(D);      % get
 FORMAT D   = swd(D, dir); % set
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
full_vol returns vol with full path, from vols, or image names
summary method returns cell array of strings describing design
swd_writable returns true if swd directory can be written to
estimate_er_model SPM estimate of ER model, and add contrast to ER model
SOURCE CODE
function res = swd(D, dir)
% method to get/set design directory
% FORMAT dir = swd(D);      % get
% FORMAT D   = swd(D, dir); % set
%
% $Id$
SPM = des_struct(D);
if nargin < 2
  res = mars_struct('getifthere', SPM, 'swd');
else
  SPM.swd = dir;
  res = des_struct(D, SPM);
end