Description of ui_get_contrasts
Home > marsbar > @mardo > ui_get_contrasts.m
ui_get_contrasts
PURPOSE
SPM contrast UI, wrapped for MarsBaR
SYNOPSIS
function varargout=ui_get_contrasts(D, varargin)
DESCRIPTION
 SPM contrast UI, wrapped for MarsBaR
=======================================================================
 - FORMAT specifications
=======================================================================
(This is a multi function function: If the first argument is a string,)
(then this is the action string, specifying the particular action)
(function to take.)
 FORMAT [I,D,changef] = ui_get_contrasts(D,STATmode,n,Prompt,Mcstr,OK2chg)
 Takes design, offers contrast GUI, returns possibly modified design
 Fields used in design are:
   xX         - Design Matrix structure
              - (see spm_spm.m for structure)
              - fields used directly are:
   .xKXs      - space structure of smoothed design matrix
   .name|xNames - cellstr of parameter names
   xCon     - Contrast definitions structure array
                (see spm_FcUtil.m for structure, rules & handling)
              - defaults to empty contrast structure
              - fields used directly are:
   .name      - contrast name string
   .STAT      - character describing statistic required: 'T' or 'F'
   .c         - contrast weights (column) vector / matrix
 STATmode   - string indicating STAT modes to allow contrast
              selection/definition for:
            - 'T' to limit to (1-dimensional) contrasts defined for SPM{t}
            - 'F' to limit to contrasts defined for SPM{F}
            - 'T|F' to allow either contrasts for SPM{t} or SPM{F}
              (both may be defined, but only one type may be selected)
            - 'T&F' to allow both contrasts for SPM{t} and SPM{F}
            - defaults to 'T|F'
 n          - Number of contrasts to select, Inf for unlimited
 Prompt     - Prompt string
 Mcstr      - string to describe multiple contrast selection
              E.g. ' for conjunction' will result in the status message
                   reading 'Selected 2 contrasts for conjunction' when
                   two contrasts are selected.
 OK2chg     - logical, specifying whether the contrast structure can be
              changed. If false, then new contrasts cannot be defined, and
              existing contrasts cannot be renamed.
 I          - Index (or indices) of contrasts selected
 D (out)    - Design with modified contrast definitions structure array
 changef    - flag set to 1 if contrast definitions have changed
                           ----------------
 [F,cF] = ui_get_contrasts(D, 'Initialise',...
                              Vis,STATmode,n,Prompt,Mcstr,OK2chg)
 Initialise mConMan GUI for contrast selection/definition
 Vis        - Initialisation action:
              'close' - closes mConMan window
              'off'   - hides mConMan window
              'reset' - hides and resets mConMan window
              'on'    - initialises mConMan window using arguments given
 STATmode   - string indicating STAT modes to allow contrast
 n          - number of contrasts to select, Inf for unlimited
 Prompt     - Prompt string
 Mcstr      - string to describe multiple contrast selection
 OK2chg     - logical, specifying whether contrast structure can be changed
 F          - figure used for contrast manager window
 cF         - Figure which was current before function call
 FORMAT ui_get_contrasts(D, 'ListCon',hConList,STAT,I)
 Utility function to list contrasts in ListBox
 hConList   - handle of GUI ListBox object
 STAT       - STAT character: 'T' or 'F' or empty (show all)
 I          - indices of currently selected contrasts
 FORMAT ui_get_contrasts(D, 'GraphCons',xCon,I,F)
 Utility function to display contrast image/bar-graph & setup "surfing"
 xCon       - contrast definitions structure array
 I          - indicies of contrasts to display
 F          - handle of 'mConMan' figure
 FORMAT ui_get_contrasts(D, 'StatusLine',F,str,col)
 Utility function to update mConMan window statusline
 F          - handle of 'mConMan' figure
 str        - string to display
              (defaults to status of contrast selection)
 col        - colour to use [defaults to 'w' - white
 FORMAT ui_get_contrasts(D, 'Done_CB')
 CallBack for "Done" button on mConMan contrast selection interface
 FORMAT ui_get_contrasts(D, 'ConList_CB')
 CallBack for contrast selection ListBox
 FORMAT STAT = ui_get_contrasts(D, 'TFA')
 CallBack for 'T','F' or 'any' STAT selection RadioButtons
 FORMAT STAT = ui_get_contrasts(D, 'TFA',F,STAT)
 Initialisation of 'T','F' or 'any' STAT selection RadioButtons
 FORMAT STAT = ui_get_contrasts(D, 'TFA',F,STAT,STATmode)
 Function to set STAT & STATmode
 Initialisation of 'T','F' or 'any' STAT selection RadioButtons & STATmode
 F          - handle of 'mConMan' figure
 STAT       - STAT character: 'T' or 'F' of empty (all)
 STATmode   - string indicating STAT modes to allow contrast
 FORMAT ui_get_contrasts(D, 'FConMenu_CB')
 CallBack to set state of mConMan contrast selection figure context menu
 FORMAT ui_get_contrasts(D, 'Rename_CB')
 CallBack to handle contrast renaming
 FORMAT [c,I,emsg,imsg,msg] = ui_get_contrasts(D, 'ParseCon',cstr,X,STAT)
 Contrast weights parser: Catch evaluation errors and invalid contrasts
 cstr       - string (or cellstr) to evaluate to get contrast(s)
 X          - design matrix
 STAT       - 'T' or 'F' (for contrast checking)
 c          - contrast weights matrix
 I          - logical validity indicator: indicates which rows of
              cellstr(cstr) generated valid contrasts which were
              included in c
 emsg       - cellstr of error messages produced during parsing
 imsg       - cellstr of information messages for valid contrasts
 msg        - cellstr of all messages produced during parsing,
              one cell per string in cstr
 FORMAT [iX0,I,emsg,imsg] = ui_get_contrasts(D, 'ParseIStr',str,max)
 DesMtx column index parser: Catch eval errors and invalid indices
 str        - string for evaluation to get column indices
 max        - number of columns in design matrix
 iX0        - vector of column indices: '!' if evaluation error
 I          - 0 if evaluation error, 1 if evaluated OK
 emsg       - error message
              (evaluation errors, non-integer indices, out of range indices)
 imsg       - information message (valid indices)
 FORMAT ui_get_contrasts(D, 'Reset_CB')
 CallBack handler for "reset" button on contrast selection interface
 FORMAT ui_get_contrasts(D, 'D_Setup_CB')
 CallBack handler for "Define new" button:
 Initialises Contrast Definition interface for use
 FORMAT ui_get_contrasts(D, 'D_ConMtx_CB')
 CallBack handler for contrast weights definition widget
 FORMAT ui_get_contrasts(D, 'D_X1cols_CB')
 Callback handler for F-contrast "columns for reduced design" widget
 FORMAT ui_get_contrasts(D, 'D_Reset_CB')
 CallBack handler for "reset" button on contrast definition interface
 FORMAT ui_get_contrasts(D, 'D_Cancel_CB')
 CallBack handler for "cancel" button on contrast definition interface
 FORMAT ui_get_contrasts(D, 'D_OK_CB')
 CallBack handler for "OK" button on contrast definiton interface
 FORMAT ui_get_contrasts(D, 'D_Status',F)
 Set status line of contrast definition interface
 F          - Handle of mConMan figure [defaults gcbf]
 FORMAT [F,H] = ui_get_contrasts(D, 'CreateFig')
 Creates mConMan dialog figure (definition interface initially hidden)
 F          - Handle of mConMan figure created
 H          - Stricture of Handles:
 .hConList  - handle of contrast selection ListBox
 .hDesMtxAx - handle of axes for design matrix imaging
 .hPrompt   - handle of prompt text object
 .hSTATmode - handle of frame containing "T/F/All" radio buttons
 .hStatLin  - handle of status line text object (in selection interface)
 .hNew      - handle of "Define new contrast" pushbutton
_______________________________________________________________________
 MarsBaR edits
 -------------
 The contrasts are stored in a stripped down mardo design structure, to
 allow this function to be called using object methods.  We need to return
 a flag (changef) to tell us if the contrasts have been changed by the GUI.
 This is stored in the D_Reset tagged handle (which is attached to the
 reset button).
 Edited from @(#)spm_conman.m    2.18 Andrew Holmes 02/09/10
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
get_contrasts method to get contrasts from design object
isempty overloaded isempty method for mardo object
isfield method to overload isfield for mardo objects
set_contrasts method to set contrasts into design object
ui_get_contrasts SPM contrast UI, wrapped for MarsBaR
This function is called by:
add_contrasts method to add contrast definitions to design
stat_table gets Mars statistics and creates statistic table as cell array
ui_get_contrasts SPM contrast UI, wrapped for MarsBaR
mars_spm_graph Graphical display of adjusted data
mars_spm_graph Graphical display of adjusted data
marsbar Startup, callback and utility routine for Marsbar
SUBFUNCTIONS
function sf_ImDesMtx(xX, h)
function sf_ImParEst(xX, h)
function sf_SetD(D, changef, F)
SOURCE CODE
function varargout=ui_get_contrasts(D, varargin)
% SPM contrast UI, wrapped for MarsBaR
%
%=======================================================================
% - FORMAT specifications
%=======================================================================
%(This is a multi function function: If the first argument is a string,)
%(then this is the action string, specifying the particular action)
%(function to take.)
%
% FORMAT [I,D,changef] = ui_get_contrasts(D,STATmode,n,Prompt,Mcstr,OK2chg)
%
% Takes design, offers contrast GUI, returns possibly modified design
% Fields used in design are:
%   xX         - Design Matrix structure
%              - (see spm_spm.m for structure)
%              - fields used directly are:
%   .xKXs      - space structure of smoothed design matrix
%   .name|xNames - cellstr of parameter names
%
%   xCon     - Contrast definitions structure array
%                (see spm_FcUtil.m for structure, rules & handling)
%              - defaults to empty contrast structure
%              - fields used directly are:
%   .name      - contrast name string
%   .STAT      - character describing statistic required: 'T' or 'F'
%   .c         - contrast weights (column) vector / matrix
%
% STATmode   - string indicating STAT modes to allow contrast
%              selection/definition for:
%            - 'T' to limit to (1-dimensional) contrasts defined for SPM{t}
%            - 'F' to limit to contrasts defined for SPM{F}
%            - 'T|F' to allow either contrasts for SPM{t} or SPM{F}
%              (both may be defined, but only one type may be selected)
%            - 'T&F' to allow both contrasts for SPM{t} and SPM{F}
%            - defaults to 'T|F'
%
% n          - Number of contrasts to select, Inf for unlimited
%
% Prompt     - Prompt string
%
% Mcstr      - string to describe multiple contrast selection
%              E.g. ' for conjunction' will result in the status message
%                   reading 'Selected 2 contrasts for conjunction' when
%                   two contrasts are selected.
%
% OK2chg     - logical, specifying whether the contrast structure can be
%              changed. If false, then new contrasts cannot be defined, and
%              existing contrasts cannot be renamed.
%
% I          - Index (or indices) of contrasts selected
%
% D (out)    - Design with modified contrast definitions structure array
% changef    - flag set to 1 if contrast definitions have changed
%
%                           ----------------
%
% [F,cF] = ui_get_contrasts(D, 'Initialise',...
%                              Vis,STATmode,n,Prompt,Mcstr,OK2chg)
% Initialise mConMan GUI for contrast selection/definition
% Vis        - Initialisation action:
%              'close' - closes mConMan window
%              'off'   - hides mConMan window
%              'reset' - hides and resets mConMan window
%              'on'    - initialises mConMan window using arguments given
% STATmode   - string indicating STAT modes to allow contrast
% n          - number of contrasts to select, Inf for unlimited
% Prompt     - Prompt string
% Mcstr      - string to describe multiple contrast selection
% OK2chg     - logical, specifying whether contrast structure can be changed
% F          - figure used for contrast manager window
% cF         - Figure which was current before function call
%
% FORMAT ui_get_contrasts(D, 'ListCon',hConList,STAT,I)
% Utility function to list contrasts in ListBox
% hConList   - handle of GUI ListBox object
% STAT       - STAT character: 'T' or 'F' or empty (show all)
% I          - indices of currently selected contrasts
%
% FORMAT ui_get_contrasts(D, 'GraphCons',xCon,I,F)
% Utility function to display contrast image/bar-graph & setup "surfing"
% xCon       - contrast definitions structure array
% I          - indicies of contrasts to display
% F          - handle of 'mConMan' figure
%
% FORMAT ui_get_contrasts(D, 'StatusLine',F,str,col)
% Utility function to update mConMan window statusline
% F          - handle of 'mConMan' figure
% str        - string to display
%              (defaults to status of contrast selection)
% col        - colour to use [defaults to 'w' - white
%
% FORMAT ui_get_contrasts(D, 'Done_CB')
% CallBack for "Done" button on mConMan contrast selection interface
%
% FORMAT ui_get_contrasts(D, 'ConList_CB')
% CallBack for contrast selection ListBox
%
% FORMAT STAT = ui_get_contrasts(D, 'TFA')
% CallBack for 'T','F' or 'any' STAT selection RadioButtons
% FORMAT STAT = ui_get_contrasts(D, 'TFA',F,STAT)
% Initialisation of 'T','F' or 'any' STAT selection RadioButtons
% FORMAT STAT = ui_get_contrasts(D, 'TFA',F,STAT,STATmode)
% Function to set STAT & STATmode
% Initialisation of 'T','F' or 'any' STAT selection RadioButtons & STATmode
% F          - handle of 'mConMan' figure
% STAT       - STAT character: 'T' or 'F' of empty (all)
% STATmode   - string indicating STAT modes to allow contrast
%
% FORMAT ui_get_contrasts(D, 'FConMenu_CB')
% CallBack to set state of mConMan contrast selection figure context menu
%
% FORMAT ui_get_contrasts(D, 'Rename_CB')
% CallBack to handle contrast renaming
%
% FORMAT [c,I,emsg,imsg,msg] = ui_get_contrasts(D, 'ParseCon',cstr,X,STAT)
% Contrast weights parser: Catch evaluation errors and invalid contrasts
% cstr       - string (or cellstr) to evaluate to get contrast(s)
% X          - design matrix
% STAT       - 'T' or 'F' (for contrast checking)
% c          - contrast weights matrix
% I          - logical validity indicator: indicates which rows of
%              cellstr(cstr) generated valid contrasts which were
%              included in c
% emsg       - cellstr of error messages produced during parsing
% imsg       - cellstr of information messages for valid contrasts
% msg        - cellstr of all messages produced during parsing,
%              one cell per string in cstr
%
% FORMAT [iX0,I,emsg,imsg] = ui_get_contrasts(D, 'ParseIStr',str,max)
% DesMtx column index parser: Catch eval errors and invalid indices
% str        - string for evaluation to get column indices
% max        - number of columns in design matrix
% iX0        - vector of column indices: '!' if evaluation error
% I          - 0 if evaluation error, 1 if evaluated OK
% emsg       - error message
%              (evaluation errors, non-integer indices, out of range indices)
% imsg       - information message (valid indices)
%
% FORMAT ui_get_contrasts(D, 'Reset_CB')
% CallBack handler for "reset" button on contrast selection interface
%
% FORMAT ui_get_contrasts(D, 'D_Setup_CB')
% CallBack handler for "Define new" button:
% Initialises Contrast Definition interface for use
%
% FORMAT ui_get_contrasts(D, 'D_ConMtx_CB')
% CallBack handler for contrast weights definition widget
% FORMAT ui_get_contrasts(D, 'D_X1cols_CB')
% Callback handler for F-contrast "columns for reduced design" widget
%
% FORMAT ui_get_contrasts(D, 'D_Reset_CB')
% CallBack handler for "reset" button on contrast definition interface
%
% FORMAT ui_get_contrasts(D, 'D_Cancel_CB')
% CallBack handler for "cancel" button on contrast definition interface
%
% FORMAT ui_get_contrasts(D, 'D_OK_CB')
% CallBack handler for "OK" button on contrast definiton interface
%
% FORMAT ui_get_contrasts(D, 'D_Status',F)
% Set status line of contrast definition interface
% F          - Handle of mConMan figure [defaults gcbf]
%
% FORMAT [F,H] = ui_get_contrasts(D, 'CreateFig')
% Creates mConMan dialog figure (definition interface initially hidden)
% F          - Handle of mConMan figure created
% H          - Stricture of Handles:
% .hConList  - handle of contrast selection ListBox
% .hDesMtxAx - handle of axes for design matrix imaging
% .hPrompt   - handle of prompt text object
% .hSTATmode - handle of frame containing "T/F/All" radio buttons
% .hStatLin  - handle of status line text object (in selection interface)
% .hNew      - handle of "Define new contrast" pushbutton
%_______________________________________________________________________
%
%
% MarsBaR edits
% -------------
% The contrasts are stored in a stripped down mardo design structure, to
% allow this function to be called using object methods.  We need to return
% a flag (changef) to tell us if the contrasts have been changed by the GUI.
% This is stored in the D_Reset tagged handle (which is attached to the
% reset button).
%
% Edited from @(#)spm_conman.m    2.18 Andrew Holmes 02/09/10
%
% $Id$
% simplify access to design
xCon = get_contrasts(D);
%-Parameters
%=======================================================================
COLOUR   = [.8,.8,1];    %-Question background colour
PJump    = 1;        %-Jumping of pointer to mConMan window
if (nargin<2) | ismember(varargin{1}, {'T', 'F', 'T|F', 'T&F'})
%=======================================================================
% [I,D,changef] = ui_get_contrasts(D,STATmode,n,Prompt,Mcstr,OK2chg)
%-Condition arguments
%-----------------------------------------------------------------------
if nargin<6, OK2chg = 0; else, OK2chg=varargin{5}; end
if nargin<5, Mcstr = ''; else, Mcstr=varargin{4}; end
if nargin<4, Prompt='Select contrast(s)...'; else, Prompt=varargin{3}; end
if nargin<3, n=1; else, n=varargin{2}; end
if nargin<2, STATmode='T|F'; else, STATmode=varargin{1}; end
%-----------------------------------------------------------------------
%-Setup mConMan window & jump cursor
[F,cF] = ui_get_contrasts(D, 'Initialise','on',STATmode,n,Prompt,Mcstr,OK2chg);
if PJump
    PLoc = get(0,'PointerLocation');
    FRec = get(F,'Position');
    set(0,'PointerLocation',[FRec(1)+FRec(3)/2, FRec(2)+FRec(2)/2])
end
%-Wait until filenames have been selected
hDone = findobj(F,'Tag','Done');
waitfor(hDone,'UserData')
%-Exit with error if mConManWin deleted
if ~ishandle(hDone), error('Contrast Manager was quit!'), end
%-Get xCon, I & exit status
status   = get(hDone,'UserData');
hConList = findobj(F,'Tag','ConList');
Q        = get(hConList,'UserData');
I        = Q(get(hConList,'Value'));
changef  = get(findobj(F,'Tag','D_Reset'), 'UserData');
% Set new contrasts, if modified
if changef
    D = set_contrasts(D, get_contrasts(get(F,'UserData')), 0);
end
%-Reset and hide SelFileWin
ui_get_contrasts(D, 'Initialise','off');
%-Return focus to previous figure (if any)
set(0,'CurrentFigure',cF)
%-Jump cursor back to previous location
if PJump, set(0,'PointerLocation',PLoc), end
%-Exit with error if reset (status=-1)
if status == -1, error(['reset: ',mfilename,' bailing out!']), end
%-Output arguments
varargout={I,D,changef};
return
end
%=======================================================================
% - Callbacks & Utility embedded functions
%=======================================================================
%=======================================================================
switch lower(varargin{1}), case 'initialise'
%=======================================================================
% [F,cF] = ui_get_contrasts(D,'Initialise',Vis,STATmode,n,Prompt,Mcstr,OK2chg)
if nargin<2, Vis='on'; else, Vis=varargin{2}; end
%-Recover mConMan figure number (if it exists)
F  = findobj(get(0,'Children'),'Flat','Tag','mConMan');
cF = get(0,'CurrentFigure');                %-Save current figure
switch lower(Vis), case 'close'
    close(F)
    varargout = {[],cF};
    return
case {'off','reset'}
    varargout = {F,cF};                %-Return figure handles
    if isempty(F), return, end            %-Return if no mConMan win
    set(F,'Visible','off')                %-Make window Invisible
    if strcmp(lower(Vis),'reset')
        set(findobj(F,'Tag','Done'),'UserData',-1)
    end
    return
case 'on'
    %-Sort out arguments
    %---------------------------------------------------------------
    if nargin<8, OK2chg = 0; else, OK2chg=varargin{7}; end
    if nargin<7, Mcstr = ''; else, Mcstr=varargin{6}; end
    Mcstr = cellstr(Mcstr); if length(Mcstr)<2, Mcstr{2}=''; end
    if nargin<6, Prompt='Select contrast(s)'; else, Prompt=varargin{5}; end
    if nargin<5, n=Inf; else, n=varargin{4}; end
    if nargin<4, STATmode='T&F'; else, STATmode=varargin{3}; end
    %-Create/find mConMan window
    %---------------------------------------------------------------
    if isempty(F)                    %-Create mConMan win
        [F,H] = ui_get_contrasts(D, 'CreateFig');
    else                        %-Get handles
        H.hDesMtxAx = findobj(F,'Tag','DesMtxAx');
        H.hParEstAx = findobj(F,'Tag','ParEstAx');
        H.hConList  = findobj(F,'Tag','ConList');
        H.hPrompt   = findobj(F,'Tag','Prompt');
        H.hTFAf     = findobj(F,'Tag','TFAf');
        H.hSTATmode = findobj(F,'Tag','STATmode');
        H.hStatLin  = findobj(F,'Tag','StatusLine');
        H.hNew      = findobj(F,'Tag','New');
    end
    varargout = {F,cF};                %-Return figure handles
    %-Set up xX for display etc
    %---------------------------------------------------------------
    SPM = des_struct(D);
    xX   = SPM.xX;
    %-Store required parameters in UserData of various objects
    %---------------------------------------------------------------
    tmpD = des_struct(D, struct('xCon', xCon));
    sf_SetD(tmpD, 0, F);
    set(H.hStatLin,        'UserData', Mcstr)    %-**
    % A little hack to make designs compatible between SPM 99 and 2
    if isfield(xX, 'Xnames'), xX.name = xX.Xnames; end
    %-Initialise interface
    %---------------------------------------------------------------
    set(findobj(F,'Tag','Done'),'UserData',0)    %-Init. Done UserData
    STAT = ui_get_contrasts(D, 'TFA',F,'',STATmode);%-Init. TFA buttons
    set(H.hPrompt,'String',Prompt,'UserData',n)    %-Set prompt
    sf_ImDesMtx(xX, H.hDesMtxAx)                %-Depict DesMtx
    sf_ImParEst(xX, H.hParEstAx)                %-Parameter estimability
    ui_get_contrasts(D, 'ListCon',H.hConList,STAT,[])    %-List contrasts
    if OK2chg, tmp='on'; else, tmp='off'; end    %-OK to change xCon?
    set(H.hNew,'Enable',tmp)            %-En/dis-able change UI
%-****    if isempty(xCon), ui_get_contrasts(D); end    %-Go straight to DNewUI
    %-Popup figure, retaining CurrentFigure
    %---------------------------------------------------------------
    set(get(findobj(F,'Tag','DefineNew'),'UserData'),'Visible','off')
                            %-Hide define UI
    figure(F)                    %-PopUp figure
    set(0,'CurrentFigure',cF)            %-Return to prev. figure
    return
otherwise
    error('Unrecognised ''Vis'' option')
end
%=======================================================================
case 'listcon'
%=======================================================================
% ui_get_contrasts(D,'ListCon',hConList,STAT,I)
hConList = varargin{2};
STAT     = varargin{3};
if nargin<5
    Q = get(hConList,'UserData');
    I = Q(get(hConList,'Value'));
else
    I = varargin{4};
end
%-Sort out list, filtering by STAT, and display
%-----------------------------------------------------------------------
if isempty(xCon)
    Q = [];
elseif isempty(STAT)
    Q = 1:length(xCon);
else
    Q = find(strcmp({xCon(:).STAT},STAT));
end
q = find(ismember(Q,I));
if ~isempty(Q)
    str        = cell(0);
    for i=1:length(Q)
        str{i} = sprintf('%03d {%c} : %s',...
                Q(i),xCon(Q(i)).STAT,xCon(Q(i)).name);
    end
    FontAngle  = 'Normal';
    FontWeight = 'Normal';
    Enable     = 'on';
else
    str        = ['no',deblank([' ',STAT]),' contrasts defined'];
    FontAngle  = 'Italic';
    FontWeight = 'Bold';
    Enable     = 'off';
end
set(hConList,'String',str,...
    'UserData',Q,...
    'Value',q,...
    'FontAngle',FontAngle,'FontWeight',FontWeight,...
    'Enable',Enable)
ui_get_contrasts(D, 'GraphCons',xCon,Q(q),get(hConList,'Parent'))
ui_get_contrasts(D, 'StatusLine',get(hConList,'Parent'))
%=======================================================================
case 'graphcons'
%=======================================================================
% ui_get_contrasts(D, 'GraphCons',xCon,I,F)
if nargin>2, xCon=varargin{2}; end
if nargin<4, I=[1:length(xCon)]; else, I=varargin{3}; end
if nargin<5, F=[]; else, F=varargin{4}; end
if isempty(F), F=spm_figure('FindWin','mConMan'); end
if isempty(F), error('can''t find mConMan win'), end
cF = get(0,'CurrentFigure');        %-Save current figure
set(0,'CurrentFigure',F);        %-Make F current
delete(findobj(F,'Tag','ConGrphAx'));
%-Display contrasts
%-----------------------------------------------------------------------
if isempty(I)
    axes('Position',[0.65 (0.7 + .1*(1-0.9)) 0.3 .1*.9],...
        'Tag','ConGrphAx','Visible','off')
    text(0.5,0.5,'no contrast(s)',...
        'FontSize',spm('FontSize',8),...
        'FontAngle','Italic',...
        'HorizontalAlignment','Center',...
        'VerticalAlignment','Middle')
else
    nPar   = size(xCon(1).c,1);
    xx     = [repmat([0:nPar-1],2,1);repmat([1:nPar],2,1)];
    nCon   = length(I);
    dy     = 0.2/max(nCon,2);
    hConAx = axes('Position',[0.65 (0.70 + dy*.1) 0.30 dy*(nCon-.1)],...
            'Tag','ConGrphAx','Visible','off');
    title('contrast(s)')
    htxt   = get(hConAx,'title'); set(htxt,'Visible','on')
    for ii = nCon:-1:1
        i  = abs(I(ii));
        axes('Position',[0.65 (0.7 + dy*(nCon-ii+.1)) 0.3 dy*.9])
        if xCon(i).STAT == 'T' & size(xCon(i).c,2)==1
        %-Single vector contrast for SPM{t} - bar
        yy = [zeros(1,nPar);repmat(xCon(i).c',2,1);zeros(1,nPar)];
        h = patch(xx,yy,[1,1,1]*.5);
        set(gca,'Tag','ConGrphAx',...
            'Box','off','TickDir','out',...
            'XTick',[],...
            'XLim',    [0,nPar],...
            'YTick',[-1,0,+1],'YTickLabel','',...
            'YLim',    [min(xCon(i).c),max(xCon(i).c)] + ...
                [-1 +1] * max(abs(xCon(i).c))/10    )
        else
        %-F-contrast - image
        h = image((xCon(i).c'/max(abs(xCon(i).c(:)))+1)*32);
        set(gca,'Tag','ConGrphAx',...
            'Box','on','TickDir','out',...
            'XTick',[],...
            'XLim',    [0,nPar]+0.5,...
            'YTick',[0:size(xCon(i).c,2)]+0.5,'YTickLabel','',...
            'YLim',    [0,size(xCon(i).c,2)]+0.5    )
        end
        if I(ii)>0, ylabel(num2str(i)), end
        set(h,'ButtonDownFcn','spm_DesRep(''SurfCon_CB'')',...
          'UserData',    struct(    'i',        I(ii),...
                    'h',        htxt,...
                    'xCon',        xCon(i)))
    end
end
set(0,'CurrentFigure',cF)        %-Reset CurrentFigure to previous figure
%=======================================================================
case 'statusline'
%=======================================================================
% ui_get_contrasts(D, 'StatusLine',F,str,col)
if nargin<3,    F = findobj(get(0,'Children'),'Flat','Tag','mConMan');
    else,    F = varargin{2}; end
if nargin<4
    n = get(findobj(F,'Tag','Prompt'),'UserData');
    m = length(get(findobj(F,'Tag','ConList'),'Value'));
    str = sprintf('Selected %d contrast',m);
    if m~=1, str=[str,'s']; end
    Mcstr = get(findobj(F,'Tag','StatusLine'),'UserData');
    if m>1, str=[str,Mcstr{1}]; else, str=[str,Mcstr{2}]; end
    if m==0
        if n<0
            str = [str,', press "Done" when finished.'];
        else
            str = [str,'.'];
        end
    else
        if n==1
            str = [str,', press "Done".'];
        else
            str = [str,', press "Done" when finished.'];
        end
    end
else
    str = varargin{3};
end
if nargin<5, col='w'; else, col=varargin{4}; end
set(findobj(F,'Tag','StatusLine'),'String',str,'ForegroundColor',col)
%=======================================================================
case 'done_cb'
%=======================================================================
% ui_get_contrasts(D, 'Done_CB')
F = gcbf;
n = get(findobj(F,'Tag','Prompt'),'UserData');
q = get(findobj(F,'Tag','ConList'),'Value');
if n>0 & isempty(q)         %-Contrast(s) required, but none selected
    if n==1,            str = 'Select a contrast!';
    elseif isfinite(n), str = sprintf('Select %d contrasts!',n);
    else,               str = 'Select at least one contrast!';
    end
elseif length(q)>abs(n)     %-Too many contrasts selected
    if n<0, tstr='at most'; else, tstr='only'; end
    if abs(n)==1,       str = ['Select',tstr,' one contrast!'];
    else,               str = sprintf('Select %s %d contrasts!',tstr,abs(n));
    end
elseif n>0 & isfinite(n) & length(q)<n
    if n==1,            str = 'Select a contrast!';
    else,               str = sprintf('Select %d contrasts!',n);
    end
else
    str = '';
end
if ~isempty(str)             %-error: display error dialog box
    spm('Beep')
    msgbox(str,sprintf('%s%s: %s...',spm('ver'),...
        spm('GetUser',' (%s)'),mfilename),'error','modal')
else                         %-OK, set Done UserData tag for handling
    set(findobj(F,'Tag','Done'),'UserData',1)
end
%=======================================================================
case 'conlist_cb'
%=======================================================================
% ui_get_contrasts(D, 'ConList_CB')
F        = gcbf;
hConList = gcbo;
Q        = get(hConList,'UserData');
I        = Q(get(hConList,'Value'));
ui_get_contrasts(D, 'GraphCons',xCon,I,F)
ui_get_contrasts(D, 'StatusLine',get(hConList,'Parent'))
if strcmp(get(F,'SelectionType'),'open'), ui_get_contrasts(D, 'Done_CB'), end
%=======================================================================
case {'tfa','d_tf'}
%=======================================================================
% STAT = ui_get_contrasts(D, 'TFA')
% STAT = ui_get_contrasts(D, 'TFA',F,STAT)
% STAT = ui_get_contrasts(D, 'TFA',F,STAT,STATmode)
DefNew = strcmp(lower(varargin{1}),'d_tf');        %-Handling DefineNew UI?
if nargin<3, F = gcbf; else, F=varargin{2}; end
if nargin<4                   %-Called as CallBack of T or F RadioButton
%-----------------------------------------------------------------------
    h = gcbo;
    if get(h,'Value')==0
        %-Was selected - don't allow unselection
        set(h,'Value',1)
        varargout={get(h,'UserData')};
        return
    else
        %-Get new STAT
        STAT = get(h,'UserData');
    end
else
    STAT = varargin{3};
end
if ~(nargin<5)                           %-Called to set STAT & STATmode
%-----------------------------------------------------------------------
    STATmode = varargin{4};
    b_set = 1;
else
    STATmode = get(findobj(F,'Tag','STATmode'),'UserData');
    b_set = 0;
end
%-Check STATmode & STAT, set temporary STATmode & STAT indicies
%-----------------------------------------------------------------------
STATinfo = struct(...                    %-STAT info structure
        'mode',        { 'T',  'F',  'T|F',    'T&F'},...
        'vSTAT',    {{'T'},{'F'},{'T','F'},{'T','F',''}},...
        'defSTAT',    { 'T',  'F',  'T',      ''},...
        'Enable',    {    {'on', 'off','off'},...
                    {'off','on' ,'off'},...
                    {'on', 'on', 'off'},...
                    {'on', 'on', 'on' }}    );
i        = find(strcmp(STATmode,{STATinfo.mode}));    %-STATmode index
if isempty(i), error('unknown STATmode'), end        %-Check STATmode valid
if DefNew & i==4, i=3; end                    %-Treat 'T&F' as 'T|F'?
if isempty(STAT), STAT=STATinfo(i).defSTAT; end        %-Set STAT as default(?)
j        = find(strcmp(STAT,{'T','F',''}));        %-STAT index
if isempty(j), error('unknown STAT'); end        %-Check known STAT
if ~any(strcmp(STAT,STATinfo(i).vSTAT))            %-Check STAT is
    error('Invalid STAT for this STATmode')        % valid for
end                            % this STATmode
%-Set STAT buttons (& Dis/Enable according to STATmode if b_setEnable)
%-----------------------------------------------------------------------
if ~DefNew, Tag='TFA'; else, Tag='D_TF'; end
H = flipud(findobj(F,'Tag',Tag));
set(H(j),            'Value',1)
set(H(setdiff([1:length(H)],j)),'Value',0)
if b_set
    %-Set RadioButton 'Enable' & store STATmode
    set(findobj(F,'Tag','STATmode'),'UserData',STATmode)
    for k=1:length(H), set(H(k),'Enable',STATinfo(i).Enable{k}), end
end
if ~DefNew                    %-Additional UI setup for main contrast manager
%-----------------------------------------------------------------------
    %-Reset ConList for new STAT if callback for TFA button
    %-------------------------------------------------------------------
    if nargin<3
        ui_get_contrasts(D, 'ListCon',findobj(F,'Tag','ConList'),STAT)
    end
else     %-Additional UI setup for  DNew contrast definition interface
%-----------------------------------------------------------------------
    %-Get handles of control objects
    %-------------------------------------------------------------------
    hD_ConMtx  = findobj(F,'Tag','D_ConMtx');
    hD_X1cols  = findobj(F,'Tag','D_X1cols');
    hD_ConErrs = findobj(F,'Tag','D_ConErrs');
    hD_ConInfo = findobj(F,'Tag','D_ConInfo');
    HD_Ttxt    = findobj(F,'Tag','D_Ttxt');
    HD_Ftxt    = findobj(F,'Tag','D_Ftxt');
    %-Set interface for new STAT
    %-------------------------------------------------------------------
    set(hD_ConMtx,'String',{},'UserData',[])            %-Clear ConMtx box
    set(hD_X1cols,'String','')                          %-Clear X1cols box
    set([hD_ConErrs,hD_ConInfo],'String',{},'Value',[]) %-Clear parsing boxes
    ui_get_contrasts(D, 'GraphCons',[],[],F)                     %-Clear contrast plot
    ui_get_contrasts(D, 'D_Status',F)                            %-Set StatusLine
    switch STAT
    case 'T'
        set(hD_ConMtx,'Max',1)
        set(HD_Ttxt,'Visible','on')
        set([hD_X1cols;HD_Ftxt],'Visible','off')
    case 'F'
        set(hD_ConMtx,'Max',2)
        set(HD_Ttxt,'Visible','off')
        set([hD_X1cols;HD_Ftxt],'Visible','on')
    otherwise
        error('illegal case')
    end
end
%-Return STAT
%-----------------------------------------------------------------------
varargout = {STAT};
%=======================================================================
case 'fconmenu_cb'
%=======================================================================
% ui_get_contrasts(D, 'FConMenu_CB')
if strcmp(get(findobj(gcbf,'Tag','New'),'Enable'),'off')
    set(findobj(gcbo,'Tag','CM_New'),'Enable','off')
    set(findobj(gcbo,'Tag','CM_Ren'),'Enable','off')
else
    set(findobj(gcbo,'Tag','CM_New'),'Enable','on')
    if length(get(findobj(gcbf,'Tag','ConList'),'Value'))==1
            set(findobj(gcbo,'Tag','CM_Ren'),'Enable','on')
    else
            set(findobj(gcbo,'Tag','CM_Ren'),'Enable','off')
    end
end
%=======================================================================
case 'rename_cb'
%=======================================================================
% ui_get_contrasts(D, 'Rename_CB')
F = gcbf;
hConList = findobj(F,'Tag','ConList');
Q        = get(hConList,'UserData');
i        = get(hConList,'Value');
%-Make sure there's only one selected contrast
%-----------------------------------------------------------------------
if length(i)~=1
    msgbox('Can only rename a single contrast!',...
        sprintf('%s%s: %s...',spm('ver'),...
        spm('GetUser',' (%s)'),mfilename),'error','modal')
    return
end
%-Get indices of current contrast
%-----------------------------------------------------------------------
I      = Q(i);
%-Get new name
%-----------------------------------------------------------------------
str = sprintf('Enter new name for contrast %d (currently "%s"):',I,xCon(I).name);
nname  = inputdlg(str,'SPM: Rename contrast',1,{''},'off');
if isempty(nname), return, end
%-Change name in ConList
%-----------------------------------------------------------------------
tmp    = get(hConList,'String');
tmp{i} = strrep(tmp{i},xCon(I).name,nname{1});
set(hConList,'String',tmp)
%-Change name in contrast structure
%-----------------------------------------------------------------------
xCon(I).name = nname{1};
D = set_contrasts(D, xCon, 0);
sf_SetD(D, 1, F);
%=======================================================================
case 'parsecon'                       %-Parse (cell)string into contrast
%=======================================================================
% [c,I,emsg,imsg,msg] = ui_get_contrasts(D, 'ParseCon',cstr,X,STAT)
% X is raw DesMtx or space structure
%-Sort out parameters
%-----------------------------------------------------------------------
if nargin<5, STAT='F'; else, STAT=varargin{4}; end
cstr = varargin{2};
X    = varargin{3};
p    = spm_SpUtil('size',X,2);
%-Preliminary parsing of contrast string (cstr) into cellstr
%-----------------------------------------------------------------------
if isempty(cstr)
    varargout = {[],0,{'    <- !empty input'},{},{}};
    return
elseif iscell(cstr)
    if size(cstr,1)~=1, cstr=cstr(:); end
    c    = cstr;
elseif isstr(cstr)
    cstr = cellstr(cstr);
    c    = cstr;
elseif isnumeric(cstr)
    if ndims(cstr)>2, error('matrices only!'), end
    c    = num2cell(cstr,2);
    cstr = cell(size(c));
    for i=1:prod(size(c)), cstr{i}=num2str(c{i}); end
else
    error('contrast input must be string or number')
end
%-Evaluate individual lines of contrast matrix input
%-----------------------------------------------------------------------
I   = zeros(size(c,1),1);
msg = cell(size(c)); [msg{:}] = deal(' (OK)');
for i=1:size(c,1)
    if isstr(c{i})
        c{i} = evalin('base',['[',c{i},']'],'''!''');
    end
    if isstr(c{i})
        msg{i} = '!evaluation error';
    else
        if isempty(c{i})
            msg{i}=' (empty line  - ignored)';
        elseif all(c{i}(:)==0)
            if size(c{i},1)==1, str='vector'; else, str='matrix'; end
            c{i}=[]; msg{i}=[' (zero ',str,' - ignored)'];
        elseif STAT=='T' & size(c{i},1)>1
            c{i}='!'; msg{i}='!vector required';
        elseif size(c{i},2)>p
            c{i}='!'; msg{i}=sprintf('!too long - only %d prams',p);
        else
            if size(c{i},2)<p
                tmp = p-size(c{i},2);
                c{i}=[c{i}, zeros(size(c{i},1),tmp)];
                if size(c{i},1)>1, str=' column'; else, str=''; end
                if tmp>1,          str=[str,'s']; end
                msg{i} = sprintf(' (right padded with %d zero%s)',tmp,str);
            end
            if ~spm_SpUtil('allCon',X,c{i}')
                c{i}='!'; msg{i}='!invalid contrast';
            end
        end
    end
    I(i)=~isstr(c{i});
end
%-Construct contrast matrix, validity indicator, and collate parsing messages
%-----------------------------------------------------------------------
c    = cat(1,c{find(I)});
msg  = [char(cstr), repmat('  <-  ',size(msg,1),1), char(msg)];
emsg = msg(find(~I),:);
imsg = msg(find(I),:);
if all(I) & STAT=='T' & size(c,1)>1      %-Check for vector t-contrasts!
    I=zeros(size(I)); emsg={'!vector required'}; imsg={};
end
%-Return arguments
%-----------------------------------------------------------------------
varargout = {c',I,emsg,imsg,msg};
%=======================================================================
case 'parseistr'                     %-Parse index string
%=======================================================================
% [iX0,I,emsg,imsg] = ui_get_contrasts(D, 'ParseIStr',str,max)
% str should be a string (row)vector
%-Sort out parameters
%-----------------------------------------------------------------------
str = varargin{2};
mx  = varargin{3};
%-Process input string
%-----------------------------------------------------------------------
I = evalin('base',['[',str,']'],'''!''');
if isstr(I)
    varargout = {'!',0,[str,'  <- !evaluation error'],''};
    return
end
%-Construct list of valid indicies
%-----------------------------------------------------------------------
ok  = ismember(I(:)',[1:mx]);
iX0 = I(ok);
%-Construct diagnostic info messages
%-----------------------------------------------------------------------
str = ''; msg='';
if any(ok)
    str = strvcat(str,num2str(I(ok)));
    msg = strvcat(msg,'  <-  (OK)');
end
tmp = (I<1 | I>mx);            %-Out of range
if any(tmp)
    str = strvcat(str,num2str(I(tmp)));
    msg = strvcat(msg,sprintf('  <-  (ignored - not in [1:%d]',mx));
end
tmp = (~tmp & ~ok);            %-Non integer in range
if any(tmp)
    str = strvcat(str,num2str(I(tmp)));
    msg = strvcat(msg,'  <-  (ignored - non-integer)');
end
%-Return arguments
%-----------------------------------------------------------------------
varargout = {iX0,1,'',cellstr([str,msg])};
%=======================================================================
case 'reset_cb'
%=======================================================================
% ui_get_contrasts(D, 'Reset_CB')
hConList = findobj(gcbf,'Tag','ConList');
STAT     = get(findobj(gcbf,'Tag','TFA','Value',1),'UserData');
ui_get_contrasts(D,'ListCon',hConList,STAT,[])
%=======================================================================
case 'd_setup_cb'
%=======================================================================
% ui_get_contrasts(D, 'D_Setup_CB')
F        = gcbf;
STAT     = get(findobj(F,'Tag','TFA','Value',1),'UserData');
STATmode = get(findobj(F,'Tag','STATmode'),'UserData');
set(F,'UIContextMenu',[])                %-Disable Fig ContextMenu
H = get(findobj(F,'Tag','DefineNew'),'UserData');    %-Get define UI handles
set(findobj(H,'flat','Tag','D_name'),'String','')    %-Clear name
%set(findobj(H,'flat','Tag','D_ConMtx'),'UserData',[])    %-Clear con definition
set(H,'Visible','on')                    %-Show UI
ui_get_contrasts(D, 'D_TF',F,STAT,STATmode);            %-Setup rest of define UI
%=======================================================================
case {'d_conmtx_cb','d_x1cols_cb'}
%=======================================================================
% ui_get_contrasts(D, 'D_ConMtx_CB')
% ui_get_contrasts(D, 'D_X1cols_CB')
fcn = find(strcmp(lower(varargin{1}),{'d_conmtx_cb','d_x1cols_cb'}));
F   = gcbf;
h   = gcbo;
str = get(h,'String');
hD_ConMtx  = findobj(F,'Tag','D_ConMtx');
hD_X1cols  = findobj(F,'Tag','D_X1cols');
%-Extract info from holding objects
%-----------------------------------------------------------------------
xX   = get(findobj(F,'Tag','DesMtxAx'),'UserData');
STAT = get(findobj(F,'Tag','D_TF','Value',1),'UserData');
if fcn==1                              %-Parse string from ConMtx widget
%-----------------------------------------------------------------------
    set(hD_X1cols,'String','')
    [c,I,emsg,imsg] = ui_get_contrasts(D, 'ParseCon',str,xX.xKXs,STAT);
    if all(I)
        DxCon = spm_FcUtil('Set','',STAT,'c',c,xX.xKXs);
    else
        DxCon = [];
    end
elseif fcn==2               %-Process column indicies from X1cols widget
%-----------------------------------------------------------------------
    set(hD_ConMtx,'String','')
    nPar              = spm_SpUtil('size',xX.xKXs,2);
    [iX0,I,emsg,imsg] = ui_get_contrasts(D, 'ParseIStr',str,nPar);
    if I
        try    %-try-catch block for any errors in spm_FcUtil!
            DxCon = spm_FcUtil('Set','',STAT,'iX0',iX0,xX.xKXs);
            if STAT=='T' & size(DxCon.c,2)>1
                I = 0; emsg = {'! t-contrasts must be vectors'};
            end
        catch
            I    = 0;
            emsg = lasterr;
        end
    end
end
%-Define the contrast or report errors...
%-----------------------------------------------------------------------
set(findobj(F,'Tag','D_ConErrs'),'String',emsg,'Value',[])
set(findobj(F,'Tag','D_ConInfo'),'String',imsg,'Value',[])
if all(I)
    set(hD_ConMtx,'UserData',DxCon);        %-Store contrast
    ui_get_contrasts(D, 'GraphCons',DxCon,-1,F)        %-Depict contrast
else
    set(hD_ConMtx,'UserData',[]);            %-Clear contrast store
    ui_get_contrasts(D, 'GraphCons',[],[],F)            %-Clear contrast plot
end
ui_get_contrasts(D, 'D_Status',F)                %-Set StatusLine
%=======================================================================
case 'd_reset_cb'
%=======================================================================
% ui_get_contrasts(D, 'D_Reset_CB')
STAT = get(findobj(gcbf,'Tag','TFA','Value',1),'UserData');
set(findobj(gcbf,'Tag','D_name'),'String','')        %-Clear name
set(findobj(gcbf,'Tag','D_ConMtx'),'UserData',[])    %-Contrast definition
ui_get_contrasts(D, 'D_TF',gcbf,STAT);                %-Setup rest of define UI
1000 %=======================================================================
1001 case 'd_cancel_cb'
1002 %=======================================================================
1003 % ui_get_contrasts(D, 'D_Cancel_CB')
1004
1005 set(get(findobj(gcbf,'Tag','DefineNew'),'UserData'),'Visible','off')
1006 set(gcbf,'UIContextMenu',findobj(gcbf,'Tag','mConMan_ConMen'))
1007 ui_get_contrasts(D, 'StatusLine')
1008
1009
1010 %=======================================================================
1011 case 'd_ok_cb'
1012 %=======================================================================
1013 % ui_get_contrasts(D, 'D_OK_CB')
1014
1015 F = gcbf;
1016
1017 name  = get(findobj(F,'Tag','D_name'),'String');
1018 DxCon = get(findobj(F,'Tag','D_ConMtx'),'UserData');
1019 STAT  = get(findobj(F,'Tag','D_TF','Value',1),'UserData');
1020
1021 dNam = ~isempty(name);
1022 dCon = ~isempty(DxCon);
1023
1024 if ~(dNam & dCon)
1025     spm('Beep')
1026     str = {    'contrast name not defined!','',...
1027         'no valid contrast defined!',''};
1028     msgbox(str([dNam+1,dCon+3]),...
1029         sprintf('%s%s: %s...',spm('ver'),...
1030         spm('GetUser',' (%s)'),mfilename),'error','modal')
1031     return
1032 end
1033
1034
1035 %-Append new contrast to xCon structure of mConMan figure 'UserData'
1036 %-----------------------------------------------------------------------
1037 DxCon.name = name;
1038 if ~strcmp(DxCon.STAT,STAT), error('STAT & DxCon.STAT mismatch!'), end
1039 if isempty(xCon)
1040     xCon = DxCon;
1041 else
1042     xCon = [xCon, DxCon];
1043 end
1044 D = set_contrasts(D, xCon, 0);
1045 sf_SetD(D, 1, F);
1046
1047
1048 %-Redisplay the new list of contrasts, with the new one selected
1049 %-----------------------------------------------------------------------
1050 hConList = findobj(F,'Tag','ConList');
1051 I = length(xCon);
1052
1053 %-Use this code to add the new contrast to a multiple selection, if allowed
1054 % Q        = get(hConList,'UserData');
1055 % I        = Q(get(hConList,'Value'));
1056 % n        = get(findobj(F,'Tag','Prompt'),'UserData');
1057 % if abs(n)>1, I=[I,length(xCon)]; else, I=length(xCon); end
1058
1059 ui_get_contrasts(D, 'TFA',F,xCon(end).STAT);            %-Set STAT
1060 ui_get_contrasts(D, 'ListCon',hConList,xCon(end).STAT,I)    %-ListCon
1061
1062 %-Hide the DefineNew UI
1063 %-----------------------------------------------------------------------
1064 set(get(findobj(gcbf,'Tag','DefineNew'),'UserData'),'Visible','off')
1065 set(gcbf,'UIContextMenu',findobj(gcbf,'Tag','mConMan_ConMen'))
1066
1067
1068 %=======================================================================
1069 case 'd_status'
1070 %=======================================================================
1071 % ui_get_contrasts(D, 'D_Status',F)
1072
1073 if nargin<3, F=gcbf; else, F=varargin{2}; end
1074 str  = {' not',''};
1075 dNam = ~isempty(get(findobj(F,'Tag','D_name'),'String'));
1076 dCon = ~isempty(get(findobj(F,'Tag','D_ConMtx'),'UserData'));
1077 if dNam & dCon, ok='on'; col='g'; else, ok='off'; col='w'; end
1078 ui_get_contrasts(D, 'StatusLine',F,...
1079     sprintf('name%s defined, contrast%s defined',str{dNam+1},str{dCon+1}),...
1080     col)
1081 %set(findobj(F,'Tag','D_OK'),'Enable',ok)        %-Enable "OK" button?
1082
1083
1084 %=======================================================================
1085 case 'createfig'
1086 %=======================================================================
1087 % [F,H] = ui_get_contrasts(D, 'CreateFig')
1088 % Handle Structure - H.{hConList,hDesMtxAx,hPrompt,hSTATmode,hStatLin,hNew}
1089
1090 cF = get(0,'CurrentFigure');        %-Save current figure
1091
1092 %-Generic callBack code.  Fetches object for method calls in callbacks
1093 %-----------------------------------------------------------------------
1094 cb = 'conD = get(findobj(''Tag'', ''mConMan''),''UserData''); ';
1095
1096 %-Create window, compute scaling for screen size
1097 %-----------------------------------------------------------------------
1098 WS = spm('WinScale');                %-Window scaling factors
1099 FS = spm('FontSizes');                %-Scaled font sizes
1100 PF = spm_platform('fonts');            %-Font names (for this platform)
1101 S0 = get(0,'ScreenSize');            %-Screen size
1102
1103 F = figure('IntegerHandle','off',...
1104         'Tag','mConMan',...
1105         'Name','SPM contrast manager','NumberTitle','off',...
1106         'Position',[S0(3)/2,S0(4)/2,0,0] + [-250,-200,500,400].*WS,...
1107         'Resize','off',...
1108         'Color',[1 1 1]*.7,...
1109         'MenuBar','none',...
1110         'DefaultTextColor','k',...
1111         'DefaultTextFontName',PF.helvetica,...
1112         'DefaultTextFontSize',FS(10),...
1113         'DefaultAxesFontName',PF.helvetica,...
1114         'DefaultUicontrolBackgroundColor',[1 1 1]*.7,...
1115         'DefaultUicontrolFontName',PF.helvetica,...
1116         'DefaultUicontrolFontSize',FS(10),...
1117         'DefaultUicontrolInterruptible','on',...
1118         'Colormap',gray(64),...
1119         'Renderer','painters',...
1120         'Visible','off');
1121
1122 %-Draw GUI objects
1123 %-----------------------------------------------------------------------
1124 hPrompt = uicontrol(F,'Style','Text','Tag','Prompt','UserData',[],...
1125         'String','<Prompt not set yet>',...
1126         'FontName',PF.times,...
1127         'FontWeight','Bold',...
1128         'FontAngle','Italic',...
1129         'FontSize',FS(16),...
1130         'ForegroundColor','k',...
1131         'BackgroundColor',[1,1,1]*.7,...
1132         'HorizontalAlignment','Center',...
1133         'Position',[020 370 280 025].*WS);
1134
1135 %                           ----------------
1136 %-T/F/all buttons...
1137
1138 hSTATmode = uicontrol(F,'Style','Frame','Tag','STATmode',...
1139         'Position',[040 340 260 028].*WS);
1140 uicontrol(F,'Style','Text','String','show',...
1141         'FontName',PF.times,'FontAngle','Italic','FontSize',FS(8),...
1142         'ForegroundColor','w',...
1143         'Position',[045 365 030 010].*WS);
1144 hT = uicontrol(F,'Style','RadioButton','String','t-contrasts','Tag','TFA',...
1145         'ToolTipString','...to show only contrasts for SPM{t}',...
1146         'FontSize',FS(9),...
1147         'ForegroundColor','k',...
1148         'UserData','T',...
1149         'Position',[044 343 105 020].*WS);
1150 hF = uicontrol(F,'Style','RadioButton','String','F-contrasts','Tag','TFA',...
1151         'ToolTipString','...to show only contrasts for SPM{F}',...
1152         'FontSize',FS(9),...
1153         'ForegroundColor','k',...
1154         'UserData','F',...
1155         'Position',[149 343 105 020].*WS);
1156 hA = uicontrol(F,'Style','RadioButton','String','all','Tag','TFA',...
1157         'ToolTipString','...to show all defined contrasts',...
1158         'FontSize',FS(9),...
1159         'ForegroundColor','k',...
1160         'UserData','',...
1161         'Position',[254 343 041 020].*WS);
1162 set([hT,hF,hA],'CallBack',[cb 'ui_get_contrasts(conD, ''TFA'');'],...
1163         'Interruptible','off','BusyAction','Queue')
1164
1165
1166 %                           ----------------
1167 %-Contrast list...
1168
1169 uicontrol(F,'Style','Text','Tag','ConListHdr',...
1170         'String','### {type} : name',...
1171         'FontSize',FS(8),'FontAngle','Italic',...
1172         'HorizontalAlignment','Left',...
1173         'BackgroundColor','w',...
1174         'Position',[042 320 256 016].*WS);
1175
1176 hConList = uicontrol(F,'Style','ListBox','Tag','ConList',...
1177         'ToolTipString',['Select contrast(s) - drag/shift-click',...
1178             '/ctrl-click to select multiple contrasts'],...
1179         'String',{'list','not','set','yet'},...
1180         'Max',2,...
1181         'CallBack',[cb 'ui_get_contrasts(conD, ''ConList_CB'')'],...
1182         'Interruptible','off','BusyAction','Queue',...
1183         'BackgroundColor','w',...
1184         'Position',[040 080 260 240].*WS);
1185
1186 %                           ----------------
1187 %-Control buttons & status area...
1188
1189 hNew = uicontrol(F,'Style','Pushbutton','String','Define new contrast...',...
1190         'Tag','New',...
1191         'ToolTipString','define new contrast',...
1192         'ForegroundColor','b',...
1193         'Callback',[cb 'ui_get_contrasts(conD, ''D_Setup_CB'')'],...
1194         'Enable','on',...
1195         'Position',[040 050 150 022].*WS);
1196
1197 uicontrol(F,'Style','Pushbutton','String','Reset',...
1198         'ToolTipString','reset selection',...
1199         'ForegroundColor','r',...
1200         'Callback',[cb 'ui_get_contrasts(conD, ''Reset_CB'')'],...
1201         'Position',[195 050 050 022].*WS);
1202
1203 uicontrol(F,'Style','Pushbutton','String','Done',...
1204         'ToolTipString','done - press when selected contrast(s)',...
1205         'ForegroundColor','m',...
1206         'Tag','Done','UserData',1,...
1207         'Callback',[cb 'ui_get_contrasts(conD, ''Done_CB'')'],...
1208         'Interruptible','off','BusyAction','Cancel',...
1209         'Position',[250 050 050 022].*WS);
1210
1211 uicontrol(F,'Style','Frame','Tag','StatusArea',...
1212     'Position',[010 010 480 030].*WS);
1213
1214 if exist('spm_help.m')==2
1215     uicontrol(F,'Style','Pushbutton','String','?',...
1216         'ToolTipString','help on contrasts and the contrast manager',...
1217         'ForegroundColor','g',...
1218         'Callback','spm_help(''spm_conman.m'')',...
1219         'Position',[460 015 020 020].*WS);
1220 end
1221
1222 hStatLin = uicontrol(F,'Style','Text','Tag','StatusLine',...
1223     'String','<Not set yet>',...
1224     'FontAngle','Italic',...
1225     'HorizontalAlignment','Center',...
1226     'ForegroundColor','w',...
1227     'Position',[020 015 430 020].*WS);
1228
1229 %                           ----------------
1230 %-Axes for design matrix and parameter estimability...
1231
1232 hDesMtxAx = axes('Parent',F,'Tag','DesMtxAx',...
1233         'Position',[0.65 0.30 0.30 0.40],...
1234         'Color','w',...
1235         'Box','on','XTick',[],'YTick',[]);
1236
1237 hParEstAx = axes('Parent',F,'Tag','ParEstAx',...
1238         'Position',[0.65 0.18 0.30 0.05],...
1239         'Color','w',...
1240         'Box','on','XTick',[],'YTick',[]);
1241
1242 %                           ----------------
1243 %-Figure UICOntextMenu
1244
1245 h = uicontextmenu('Tag','mConMan_ConMen');
1246 set(F,'UIContextMenu',h)
1247 uimenu(h,'Label','Define new contrast...',...
1248     'Tag','CM_New',...
1249     'CallBack',[cb 'ui_get_contrasts(conD, ''D_Setup_CB'')'],...
1250     'Interruptible','off','BusyAction','Cancel');
1251 uimenu(h,'Label','Rename selected contrast...',...
1252     'Tag','CM_Ren',...
1253     'CallBack',[cb 'ui_get_contrasts(conD, ''Rename_CB'')'],...
1254     'Interruptible','off','BusyAction','Cancel');
1255 uimenu(h,'Label','Reset','Separator','on',...
1256     'CallBack',[cb 'ui_get_contrasts(conD, ''Reset_CB'')'],...
1257     'Interruptible','off','BusyAction','Cancel');
1258 uimenu(h,'Label','Done',...
1259     'CallBack',[cb 'ui_get_contrasts(conD, ''Done_CB'')'],...
1260     'Interruptible','off','BusyAction','Cancel');
1261 uimenu(h,'Label','help','Separator','on',...
1262     'CallBack','spm_help(''spm_conman'')',...
1263     'Interruptible','off','BusyAction','Cancel');
1264 uimenu(h,'Label','crash out','Separator','on',...
1265     'CallBack',[cb 'ui_get_contrasts(conD, ''Initialise'',''reset'');'],...
1266     'Interruptible','off','BusyAction','Cancel');
1267 set(h,'CallBack',[cb 'ui_get_contrasts(conD, ''FConMenu_CB'')'],...
1268     'Interruptible','off','BusyAction','Cancel');
1269
1270
1271 %-Draw contrast definition GUI
1272 %-----------------------------------------------------------------------
1273 H = [];                %-Save handles for visibility switching
1274
1275 h = uicontrol(F,'Style','Frame','Tag','DefineNew',...
1276     'Position',[010 045 300 350].*WS);
1277 H = [H,h];
1278 h = uicontrol(F,'Style','Text','Tag','D_Prompt','UserData',[],...
1279         'String','define contrast...',...
1280         'FontName',PF.times,...
1281         'FontWeight','Bold',...
1282         'FontAngle','Italic',...
1283         'FontSize',FS(14),...
1284         'ForegroundColor','b',...
1285         'HorizontalAlignment','Center',...
1286         'Position',[020 360 280 030].*WS);
1287 H = [H,h];
1288
1289 %                           ----------------
1290 %-name
1291 h = uicontrol(F,'Style','Frame','Position',[020 335 280 033].*WS);
1292 H = [H,h];
1293 h = uicontrol(F,'Style','Text','String','name',...
1294         'FontSize',FS(10),...
1295         'FontAngle','Italic',...
1296         'ForegroundColor','w',...
1297         'HorizontalAlignment','Center',...
1298         'Position',[025 355 045 020].*WS);
1299 H = [H,h];
1300 h = uicontrol(F,'Style','Edit','Tag','D_name',...
1301         'ToolTipString','enter name for contrast',...
1302         'HorizontalAlignment','Left',...
1303         'BackgroundColor',COLOUR,...
1304             'Callback',[cb 'ui_get_contrasts(conD, ''D_Status'')'],...
1305             'Interruptible','off',...
1306         'Position',[080 340 215 022].*WS);
1307 H = [H,h];
1308
1309 %                           ----------------
1310 %-type
1311 h = uicontrol(F,'Style','Frame','Position',[020 295 280 033].*WS);
1312 H = [H,h];
1313 h = uicontrol(F,'Style','Text','String','type',...
1314         'FontSize',FS(10),...
1315         'FontAngle','Italic',...
1316         'ForegroundColor','w',...
1317         'HorizontalAlignment','Center',...
1318         'Position',[025 315 040 020].*WS);
1319 H = [H,h];
1320
1321 hDT = uicontrol(F,'Style','RadioButton','String','t-contrast','Tag','D_TF',...
1322         'ToolTipString','...to define contrast for SPM{t}',...
1323         'FontSize',FS(9),...
1324         'ForegroundColor','k',...
1325         'UserData','T',...
1326         'Position',[080 300 105 022].*WS);
1327 hDF = uicontrol(F,'Style','RadioButton','String','F-contrast','Tag','D_TF',...
1328         'ToolTipString','...to define contrast for SPM{F}',...
1329         'FontSize',FS(9),...
1330         'ForegroundColor','k',...
1331         'UserData','F',...
1332         'Position',[190 300 105 022].*WS);
1333 set([hDT,hDF],'CallBack',[cb 'ui_get_contrasts(conD, ''D_TF'');'],...
1334         'Interruptible','off','BusyAction','Queue')
1335 H = [H,hDT,hDF];
1336
1337 %                           ----------------
1338 %-contrast
1339 h = uicontrol(F,'Style','Frame','Position',[020 080 280 208].*WS);
1340 H = [H,h];
1341 h = uicontrol(F,'Style','Text','String','contrast',...
1342         'FontSize',FS(10),...
1343         'FontAngle','Italic',...
1344         'ForegroundColor','w',...
1345         'HorizontalAlignment','Center',...
1346         'Position',[025 275 055 020].*WS);
1347 H = [H,h];
1348 h = uicontrol(F,'Style','Text','String','contrast',...
1349         'FontSize',FS(6),...
1350         'HorizontalAlignment','Right',...
1351         'Position',[030 255 045 008].*WS);
1352 H = [H,h];
1353 h = uicontrol(F,'Style','Text','String','weights',...
1354         'FontSize',FS(6),...
1355         'HorizontalAlignment','Right',...
1356         'Position',[030 245 045 008].*WS);
1357 H = [H,h];
1358 h = uicontrol(F,'Style','Text','String','vector','Tag','D_Ttxt',...
1359         'FontSize',FS(6),...
1360         'HorizontalAlignment','Right',...
1361         'Position',[030 235 045 008].*WS);
1362 H = [H,h];
1363 h = uicontrol(F,'Style','Text','String','matrix','Tag','D_Ftxt',...
1364         'FontSize',FS(6),...
1365         'HorizontalAlignment','Right',...
1366         'Position',[030 235 045 008].*WS);
1367 H = [H,h];
1368 h = uicontrol(F,'Style','Edit','Tag','D_ConMtx',...
1369         'ToolTipString','enter contrast',...
1370         'HorizontalAlignment','Left',...
1371         'BackgroundColor',COLOUR,...
1372         'Max',2,...
1373         'CallBack',[cb 'ui_get_contrasts(conD, ''D_ConMtx_CB'')'],...
1374         'Interruptible','off','BusyAction','Queue',...
1375         'UserData',[],...
1376         'Position',[080 200 215 082].*WS);
1377 H = [H,h];
1378 h = uicontrol(F,'Style','Text','String','or','Tag','D_Ftxt',...
1379         'FontAngle','Italic',...
1380         'FontSize',FS(6),...
1381         'HorizontalAlignment','Left',...
1382         'Position',[025 205 030 008].*WS);
1383 H = [H,h];
1384 h = uicontrol(F,'Style','Text','String','columns for','Tag','D_Ftxt',...
1385         'FontSize',FS(6),...
1386         'HorizontalAlignment','Right',...
1387         'Position',[022 190 070 008].*WS);
1388 H = [H,h];
1389 h = uicontrol(F,'Style','Text','String','reduced design','Tag','D_Ftxt',...
1390         'FontSize',FS(6),...
1391         'HorizontalAlignment','Right',...
1392         'Position',[022 180 070 008].*WS);
1393 H = [H,h];
1394 h = uicontrol(F,'Style','Edit','Tag','D_X1cols',...
1395         'ToolTipString',...
1396             'enter column indicies of reduced design matrix X0',...
1397         'HorizontalAlignment','Left',...
1398         'BackgroundColor',COLOUR,...
1399         'CallBack',[cb 'ui_get_contrasts(conD, ''D_X1cols_CB'')'],...
1400         'Interruptible','off','BusyAction','Queue',...
1401         'Position',[090 180 155 020].*WS);
1402 H = [H,h];
1403 h = uicontrol(F,'Style','Pushbutton','String','...submit',...
1404         'FontSize',FS(8),...
1405         'ForegroundColor','c',...
1406         'Position',[245 180 050 020].*WS);
1407 H = [H,h];
1408
1409 %-Errors & info boxes...
1410 h = uicontrol(F,'Style','ListBox','Tag','D_ConErrs',...
1411         'ToolTipString','contrast parsing errors',...
1412         'FontName',PF.courier,'FontSize',FS(7),...
1413         'ForegroundColor','r',...
1414         'BackgroundColor',[1 1 1]*.7,...
1415         'Enable','on','Max',2,'Value',[],...
1416         'Position',[027 127 268 042].*WS);
1417 H = [H,h];
1418 h = uicontrol(F,'Style','ListBox','Tag','D_ConInfo',...
1419         'ToolTipString','contrast parsing info',...
1420         'FontName',PF.courier,'FontSize',FS(7),...
1421         'ForegroundColor','g',...
1422         'BackgroundColor',[1 1 1]*.7,...
1423         'Enable','on','Max',2,'Value',[],...
1424         'Position',[027 085 268 042].*WS);
1425 H = [H,h];
1426
1427 %                           ----------------
1428 %-Control buttons & status area...
1429 h = uicontrol(F,'Style','Pushbutton','String','Reset',...
1430         'Tag','D_Reset',...
1431         'ToolTipString','reset definition interface',...
1432         'ForegroundColor','b',...
1433         'Callback',[cb 'ui_get_contrasts(conD, ''D_Reset_CB'')'],...
1434         'Interruptible','off','BusyAction','Cancel',...
1435         'Position',[140 053 050 022].*WS);
1436 H = [H,h];
1437 h = uicontrol(F,'Style','Pushbutton','String','Cancel',...
1438         'Tag','D_Cancel',...
1439         'ToolTipString','cancel contrast definition',...
1440         'ForegroundColor','r',...
1441         'Callback',[cb 'ui_get_contrasts(conD, ''D_Cancel_CB'')'],...
1442         'Interruptible','off','BusyAction','Cancel',...
1443         'Position',[195 053 050 022].*WS);
1444 H = [H,h];
1445 h = uicontrol(F,'Style','Pushbutton','String','OK',...
1446         'Tag','D_OK',...
1447         'ToolTipString','OK - press to accept newly defined contrast',...
1448         'ForegroundColor','m',...
1449         'Callback',[cb 'ui_get_contrasts(conD, ''D_OK_CB'')'],...
1450         'Interruptible','off','BusyAction','Cancel',...
1451         'Position',[250 053 050 022].*WS);
1452 H = [H,h];
1453 set(findobj(H,'flat','Tag','DefineNew'),'UserData',H)
1454
1455
1456 %-Finish up
1457 %-----------------------------------------------------------------------
1458 set(0,'CurrentFigure',cF)
1459 varargout = {F,struct('hConList',    hConList,...
1460             'hDesMtxAx',    hDesMtxAx,...
1461             'hParEstAx',    hParEstAx,...
1462             'hPrompt',    hPrompt,...
1463             'hSTATmode',    hSTATmode,...
1464             'hStatLin',    hStatLin,...
1465             'hNew',        hNew)};
1466
1467
1468 %=======================================================================
1469 otherwise                                               %-unknown action
1470 %=======================================================================
1471 error(['Illegal Action string: ',varargin{1}])
1472
1473
1474 %=======================================================================
1475 end                                                            % - E N D
1476 return
1477 %=======================================================================
1478
1479
1480 %=======================================================================
1481 % Subfunctions
1482 %=======================================================================
1483 function sf_ImDesMtx(xX, h)
1484 %-Picture design matrix
1485
1486 axes(h)
1487 if isfield(xX,'nKX') & ~isempty(xX.nKX)
1488     hDesMtxIm = image((xX.nKX+1)*32);
1489 else
1490     hDesMtxIm = image(...
1491         (spm_DesMtx('sca',xX.xKXs.X,xX.name)+1)*32);
1492 end
1493 set(h,'YTick',[],'XTick',[])            %-No Tick marks
1494 set(h,'Tag','DesMtxAx','UserData',xX)    %-Reset axis UserData after image
1495 xlabel('Design matrix')
1496 set(hDesMtxIm,'UserData',...
1497     struct('X',xX.xKXs.X,'Xnames',{xX.name}))
1498 set(hDesMtxIm,'ButtonDownFcn','spm_DesRep(''SurfDesMtx_CB'')')
1499 return
1500
1501 function sf_ImParEst(xX, h)
1502 %-Picture design parameter estimability
1503
1504 axes(h)
1505 est  = spm_SpUtil('IsCon',xX.xKXs);
1506 nPar = length(est);
1507
1508 hParEstIm = image((est+1)*32);
1509 set(h,    'XLim',[0,nPar]+.5,'XTick',[1:nPar-1]+.5,'XTickLabel','',...
1510     'YLim',[0,1]+.5,'YDir','reverse','YTick',[],...
1511     'Box','on','TickDir','in','XGrid','on','GridLineStyle','-');
1512 xlabel('parameter estimability')
1513 set(h,'Tag','ParEstAx')            %-Reset 'Tag' after image cleared it
1514 set(hParEstIm,'UserData',struct('est',est,'Xnames',{xX.name}))
1515 set(hParEstIm,'ButtonDownFcn','spm_DesRep(''SurfEstIm_CB'')')
1516 return
1517
1518 function sf_SetD(D, changef, F)
1519 % Sets new data into figure
1520 if nargin < 2, changef = 0; end
1521 if nargin < 3, F = get(findobj('Tag', 'mConMan'),'UserData'); end
1522
1523 hD_Reset = findobj(F,'Tag','D_Reset');
1524 set(F, 'UserData', D);
1525 set(hD_Reset, 'UserData', changef);
1526 return
1527