Description of unfiltered_efficiency
Home > marsbar > @mardo > unfiltered_efficiency.m
unfiltered_efficiency
PURPOSE
Calculate unfiltered efficiency for given SPM design and contrast
SYNOPSIS
function e = unfiltered_efficiency(D, Ic)
DESCRIPTION
 Calculate unfiltered efficiency for given SPM design and contrast
CROSS-REFERENCE INFORMATION
This function calls:
design_matrix method returns design matrix from design
get_contrasts method to get contrasts from design object
has_contrasts method returns 1 if design has contrasts
This function is called by:
SOURCE CODE
function e = unfiltered_efficiency(D, Ic)
% Calculate unfiltered efficiency for given SPM design and contrast
if nargin < 2
  error('Need design and contrast number');
end
if ~has_contrasts(D)
  error('Need design with contrasts');
end
% Get contrast matrix to test for
xCon = get_contrasts(D);
con = xCon(Ic).c;
X = design_matrix(D);
e = 1 / trace(con' * pinv(X' * X) * con);
return