Description of do_write_image
Home > marsbar > @maroi_matrix > do_write_image.m
do_write_image
PURPOSE
method saves matrix as image and returns spm_vol
SYNOPSIS
function v = do_write_image(o, fname)
DESCRIPTION
 method saves matrix as image and returns spm_vol
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
binarize binarize - returns / sets binarize value for object
mars_vol_utils collection of useful utility functions for vol structs
spm_create_vol Wrapper for spm_create_image, for compatibility with SPM2
spm_write_vol Write an image volume to disk, setting scales and offsets as appropriate
This function is called by:
save_as_image method save_as_image - saves ROI as image
SOURCE CODE
function v = do_write_image(o, fname)
% method saves matrix as image and returns spm_vol
%
% $Id$
v = mars_vol_utils('def_vol');
v.fname = fname;
v.mat = o.mat;
v.dim = size(o.dat);
if binarize(o)
  v = mars_vol_utils('set_type', v, 'uint8');
else
  v = mars_vol_utils('set_type', v, 'float');
end
v = spm_create_vol(v);
v = spm_write_vol(v, o.dat);