Description of is_empty_roi
Home > marsbar > @maroi_matrix > is_empty_roi.m
is_empty_roi
PURPOSE
is_empty_roi - returns true if ROI contains no volume
SYNOPSIS
function tf = is_empty_roi(o)
DESCRIPTION
 is_empty_roi - returns true if ROI contains no volume
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mars_display_roi utility routines for display of ROIs in graphic window
mars_rois2img creates cluster or number labelled ROI image from ROIs
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function tf = is_empty_roi(o)
% is_empty_roi - returns true if ROI contains no volume
%
% $Id$
tf = ~any(o.dat(:));