Description of matrixdata
Home > marsbar > @maroi_matrix > matrixdata.m
matrixdata
PURPOSE
matrixdata method - gets matrix from ROI object
SYNOPSIS
function dat = matrixdata(o, dat)
DESCRIPTION
 matrixdata method - gets matrix from ROI object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
binarize binarize - returns / sets binarize value for object
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
roithresh roithresh - returns / sets roithresh value for object
maroi_matrix maroi_matrix method - converts maroi_image to maroi_matrix
maroi_matrix maroi_matrix - class constructor
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
maroi_matrix method to convert shape objects to maroi_matrix objects
This function is called by:
are_same returns 1 if rois are the same
loadobj loadobj method - reloads matrix from img file
saveobj saveobj method - removes matrix information from parent to save space
vol vol - returns / sets image vol for object
maroi_matrix maroi_matrix - class constructor
mars_display_roi utility routines for display of ROIs in graphic window
mars_rois2img creates cluster or number labelled ROI image from ROIs
SOURCE CODE
function dat = matrixdata(o, dat)
% matrixdata method - gets matrix from ROI object
%
% $Id$
% a warning here about empty matrices
if nargin > 1 % call to set matrix data
  % change to maroi_matrix type before setting data
  o = maroi_matrix(o);
  % apply implied thresholding
  tmp = find(isnan(dat) | abs(dat) < roithresh(o));
  if binarize(o), dat(:) = 1; end
  dat(tmp) = 0;
  o.dat = dat;
  dat = o;
else
  dat = o.dat;
end