Description of native_space
Home > marsbar > @maroi_matrix > native_space.m
native_space
PURPOSE
native_space method - returns native space of object
SYNOPSIS
function sp = native_space(obj)
DESCRIPTION
 native_space method - returns native space of object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
mars_space mars_space - class constructor for space defining object
This function is called by:
are_same returns 1 if rois are the same
c_o_m c_o_m method - calculates unweighted centre of mass
rle run length encoding method
save_mricro saves in MRIcro format
volume volume method - returns volume of ROI in mm
maroi_matrix maroi_matrix - class constructor
maroi_matrix method to convert shape objects to maroi_matrix objects
mars_display_roi utility routines for display of ROIs in graphic window
SOURCE CODE
function sp = native_space(obj)
% native_space method - returns native space of object
%
% $Id$
sp = mars_space(size(obj.dat), obj.mat);