Description of rebase
Home > marsbar > @maroi_matrix > rebase.m
rebase
PURPOSE
rebase method - returns data from maroi_matrix in new space
SYNOPSIS
function [pts, vals] = rebase(obj, sp, flags)
DESCRIPTION
 rebase method - returns data from maroi_matrix in new space
 Unless flags contains 'i', returns [pts, vals]
 otherwise returns matrix in new space
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
binarize binarize - returns / sets binarize value for object
roithresh roithresh - returns / sets roithresh value for object
spm_hold hold - returns / sets hold value for object
vol vol - returns / sets image vol for object
spm_mat spm_mat method - returns mat file defining orientation etc
mars_space mars_space - class constructor for space defining object
This function is called by:
maroi_matrix maroi_matrix - class constructor
voxpts voxpts method - returns 3xN ijk matrix in voxels
SOURCE CODE
function [pts, vals] = rebase(obj, sp, flags)
% rebase method - returns data from maroi_matrix in new space
% Unless flags contains 'i', returns [pts, vals]
% otherwise returns matrix in new space
%
% $Id$
if nargin < 2
  error('Need space to give voxel points');
end
if nargin < 3
  flags = '';
end
if isempty(flags), flags = ' ';end
sp = mars_space(sp);
vol = obj.dat;
mat = spm_mat(obj);
Hold = spm_hold(obj);
th = roithresh(obj);
binf = binarize(obj);
if any(flags == 'i')
  pts = zeros(sp.dim(1:3));
  vals = [];
else % points call
  pts = cell(1, sp.dim(3));
  multvc = cell(1, sp.dim(3));
end
for z=1:sp.dim(3),
  M = inv(mat) * sp.mat * spm_matrix([0 0 z]);
  img = spm_slice_vol(vol,M,sp.dim(1:2),Hold);
  tmp = abs(img) >= th;
  img(~tmp) = 0;
  if any(tmp(:))
    if binf, img(tmp) = 1; end
    if any(flags == 'i') % image to return
      pts(:,:,z) = img;
    else % point list
      tmp = find(tmp);
      multvc(z) = {img(tmp)'};
      tmp = tmp-1;
      y = floor(tmp/sp.dim(1));
      x = tmp - (y*sp.dim(1));
      o = ones(1, length(x));
      pts(z) = {[[x y]'+1; o*z]};
    end
  end
end
if ~any(flags == 'i')
  pts =  [pts{:}];
  vals = [multvc{:}];
end