Description of spm_create_vol
Home > marsbar > spm99 > spm_create_vol.m
spm_create_vol
PURPOSE
Wrapper for spm_create_image, for compatibility with SPM2
SYNOPSIS
function V = spm_create_vol(V)
DESCRIPTION
 Wrapper for spm_create_image, for compatibility with SPM2
 FORMAT V = spm_create_vol(V)
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
spm_create_image Wrapper for spm_create_vol, for compatibility with SPM99
spm_create_image Wrapper for spm_create_vol, for compatibility with SPM99
This function is called by:
do_write_image method saves matrix as image and returns spm_vol
mars_rois2img creates cluster or number labelled ROI image from ROIs
spm_create_image Wrapper for spm_create_vol, for compatibility with SPM99
spm_create_image Wrapper for spm_create_vol, for compatibility with SPM99
spm_write_vol Write an image volume to disk, setting scales and offsets as appropriate
SOURCE CODE
function V = spm_create_vol(V)
% Wrapper for spm_create_image, for compatibility with SPM2
% FORMAT V = spm_create_vol(V)
%
% $Id$
V = spm_create_image(V);