Description of spm_close_vol
Home > marsbar > spm99 > spm_close_vol.m
spm_close_vol
PURPOSE
Close image volume - for SPM2 / SPM99 compatibility
SYNOPSIS
function Vo = spm_close_vol(Vi)
DESCRIPTION
 Close image volume - for SPM2 / SPM99 compatibility
 See: spm_create_vol and spm_write_plane.
 SPM99 seems to use spm_create_image to close volumes
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
spm_create_image Wrapper for spm_create_vol, for compatibility with SPM99
spm_create_image Wrapper for spm_create_vol, for compatibility with SPM99
This function is called by:
spm_write_vol Write an image volume to disk, setting scales and offsets as appropriate
SOURCE CODE
function Vo = spm_close_vol(Vi)
% Close image volume - for SPM2 / SPM99 compatibility
% See: spm_create_vol and spm_write_plane.
%
% SPM99 seems to use spm_create_image to close volumes
%
% $Id$
for i=1:prod(size(Vi)),
  Vo(i) = spm_create_image(Vi(i));
end