Description of type
Home > marsbar > @mardo_5 > type.m
type
PURPOSE
returns SPM version string corresponding to design type
SYNOPSIS
function str = type(o)
DESCRIPTION
 returns SPM version string corresponding to design type
 $Id: type.m 76 2003-12-25 08:19:13Z matthewbrett $
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mardo mardo - class constructor for MarsBaR design object
summary method returns cell array of strings describing design
pr_spm_ui MarsBaR: setting up the general linear model for independent data
pr_spm_ui MarsBaR: Setting up the general linear model for independent data
pr_spm_ui MarsBaR: setting up the general linear model for independent data
maroi_pointlist maroi_pointlist - class constructor
do_bch_wrapper ---------------------------------------------------------------
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function str = type(o)
% returns SPM version string corresponding to design type
%
% $Id: type.m 76 2003-12-25 08:19:13Z matthewbrett $
str = 'SPM5';