Description of pr_spm_orth
Home > marsbar > @mardo_2 > private > pr_spm_orth.m
pr_spm_orth
PURPOSE
recursive orthogonalization of basis functions
SYNOPSIS
function x = spm_orth(X)
DESCRIPTION
 recursive orthogonalization of basis functions
 FORMAT x = spm_orth(X)
 serial orthogionalization starting with the first column
_______________________________________________________________________
 @(#)spm_orth.m    2.1 Karl Friston 02/02/07
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
pr_spm_get_bf fills in basis function structure
pr_spm_get_ons returns input [designed effects] structures
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_spm_get_bf fills in basis function structure
pr_spm_get_ons returns input [designed effects] structures
event_x_fir method to return FIR design matrix columns for session
pr_spm_get_bf creates basis functions for each trial type {i} in struct BF{i}
SOURCE CODE
function x = spm_orth(X)
% recursive orthogonalization of basis functions
% FORMAT x = spm_orth(X)
%
% serial orthogionalization starting with the first column
%_______________________________________________________________________
% @(#)spm_orth.m    2.1 Karl Friston 02/02/07
x     = X(:,1);
for i = 2:size(X,2)
        D     = X(:,i);
        D     = D - x*(pinv(x)*D);
        if any(D)
                x = [x D];
        end
end