Description of pr_refresh_et
Home > marsbar > @mardo > private > pr_refresh_et.m
pr_refresh_et
PURPOSE
Refreshes data and display of event type window after edit
SYNOPSIS
function F = pr_refresh_et(D, ic, F, hList, hEdit)
DESCRIPTION
 Refreshes data and display of event type window after edit
 FORMAT F = pr_refresh_et(D, ic, F, hList)
 D              - design object
 ic             - indices to events to select
 F              - (optional) figure handle
 hList          - (optional) handle to list uicontrol
 hEdit          - (optional) handle to Edit uicontrol
 Returns
 F              - figure handle (in case you didn't have it)
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
event_types method to get / set event types for design
isfield method to overload isfield for mardo objects
This function is called by:
ui_event_types_cb method to handle callbacks from ui_event_types
SOURCE CODE
function F = pr_refresh_et(D, ic, F, hList, hEdit)
% Refreshes data and display of event type window after edit
% FORMAT F = pr_refresh_et(D, ic, F, hList)
%
% D              - design object
% ic             - indices to events to select
% F              - (optional) figure handle
% hList          - (optional) handle to list uicontrol
% hEdit          - (optional) handle to Edit uicontrol
%
% Returns
% F              - figure handle (in case you didn't have it)
%
% $Id$
if nargin < 1
  error('Need object');
end
if nargin < 2
  ic = [];
end
if nargin < 3
  F = findobj(get(0, 'Children'), 'Flat', 'Tag', 'ui_event_types');
end
if nargin < 4
  hList = findobj(F, 'Tag','eList');
end
if nargin < 5
  hEdit = findobj(F, 'Tag','eEdit');
end
if ~ishandle(F)
  error('Could not find ui_event_types window');
end
et = event_types(D);
% Event type list to put
if isfield(et, 'name')
  eNames = {et(:).name};
else
  eNames = {};
end
set(hList, 'String', eNames);
set(hList, 'Value', ic);
set(F, 'Userdata', D);
set(hEdit, 'UserData', 1);