Description of mars_blob_ui
Home > marsbar > spm2 > mars_blob_ui.m
mars_blob_ui
PURPOSE
Displays SPM results, and ROI menu in SPM input window
SYNOPSIS
function mars_blob_ui(action)
DESCRIPTION
 Displays SPM results, and ROI menu in SPM input window
 FORMAT mars_blob_ui(action)
 This is the SPM2 version
 action     - action string; can be
                'init'      - initialise results interface
                'save_one'  - UI to save current cluster
                'save_many' - UI to save all clusters
 This routine does SPM version specific stuff, the main
 work is in mars_blob2roi.m and mars_blobs2rois.m
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
mars_blob2roi saves ROI for cluster in xSPM structure, containing point pt
mars_blob_menu puts up ROI menu to add to SPM results interface
mars_blobs2rois creates ROIs from spm_results_ui SPM
mars_blob_ui Displays SPM results, and ROI menu in SPM input window
mars_blob_ui Displays SPM results, and ROI menu in SPM input window
mars_blob_ui Displays SPM results, and ROI menu in SPM input window
This function is called by:
mars_blob_ui Displays SPM results, and ROI menu in SPM input window
mars_blob_ui Displays SPM results, and ROI menu in SPM input window
mars_blob_ui Displays SPM results, and ROI menu in SPM input window
SOURCE CODE
function mars_blob_ui(action)
% Displays SPM results, and ROI menu in SPM input window
% FORMAT mars_blob_ui(action)
%
% This is the SPM2 version
%
% action     - action string; can be
%                'init'      - initialise results interface
%                'save_one'  - UI to save current cluster
%                'save_many' - UI to save all clusters
%
% This routine does SPM version specific stuff, the main
% work is in mars_blob2roi.m and mars_blobs2rois.m
%
% $Id$
if nargin < 1
  action = 'init';
end
errstr = sprintf(['''Cannot find xSPM struct in the workspace; '...
          'Please (re)run SPM results GUI''']);
switch lower(action)
 case 'init'
  try % and find valid SPM results stuff
    evalin('base', 'xSPM;');
    hReg = evalin('base', 'hReg;');
    spm_XYZreg('CleanReg',hReg);
    mars_blob_menu;
  catch % give up and get a new one
    mars_blob_ui('reinit');
  end
 case 'reinit'
  % Display SPM results
  evalin('base', '[hReg,xSPM,SPM] = spm_results_ui;');
  % Menu
  mars_blob_menu;
 case 'save_one'
  xSPM = evalin('base', 'xSPM', ['error(' errstr ')']);
  %-Get current location
  pt   = spm_results_ui('GetCoords');
  mars_blob2roi(xSPM, pt);
 case 'save_many'
  xSPM = evalin('base', 'xSPM', ['error(' errstr ')']);
  mars_blobs2rois(xSPM);
 otherwise
  error(['Worried by request for ' action]);
end