Description of spm_create_image
Home > marsbar > spm2 > spm_create_image.m
spm_create_image
PURPOSE
Wrapper for spm_create_vol, for compatibility with SPM99
SYNOPSIS
function V = spm_create_image(V)
DESCRIPTION
 Wrapper for spm_create_vol, for compatibility with SPM99
 FORMAT V = spm_create_image(V)
 Actually, MarsBaR itself does not use this function; it's included here
 for compatibility with Phiwave (phiwave.sourceforge.net), that depends
 on MarsBaR for its design interface and such.
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
spm_create_vol Wrapper for spm_create_image, for compatibility with SPM2
This function is called by:
spm_close_vol Close image volume - for SPM2 / SPM99 compatibility
spm_create_vol Wrapper for spm_create_image, for compatibility with SPM2
SOURCE CODE
function V = spm_create_image(V)
% Wrapper for spm_create_vol, for compatibility with SPM99
% FORMAT V = spm_create_image(V)
%
% Actually, MarsBaR itself does not use this function; it's included here
% for compatibility with Phiwave (phiwave.sourceforge.net), that depends
% on MarsBaR for its design interface and such.
%
% $Id$
V = spm_create_vol(V);