Description of flip_lr
Home > marsbar > @maroi_image > flip_lr.m
flip_lr
PURPOSE
flips ROI left / right
SYNOPSIS
function o = flip_lr(o)
DESCRIPTION
 flips ROI left / right
 $Id
CROSS-REFERENCE INFORMATION
This function calls:
flip_lr flips ROI left / right
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
flip_lr flips ROI left / right
flip_lr flips ROI left / right
maroi_matrix maroi_matrix method - converts maroi_image to maroi_matrix
flip_lr flips ROI left / right
maroi_matrix maroi_matrix - class constructor
flip_lr flips ROI left / right
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
maroi_matrix method to convert shape objects to maroi_matrix objects
flip_lr flips ROI left / right
This function is called by:
flip_lr flips ROI left / right
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function o = flip_lr(o)
% flips ROI left / right
%
% $Id
% Requires change to ROI data -> return as maroi_matrix
o = flip_lr(maroi_matrix(o));