Description of loadobj
Home > marsbar > @maroi_image > loadobj.m
loadobj
PURPOSE
loadobj method - reloads matrix from img file
SYNOPSIS
function o = loadobj(o)
DESCRIPTION
 loadobj method - reloads matrix from img file
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
my_vol_func checks vol and func, returns processed image matrix or error
matrixdata matrixdata method - gets matrix from ROI object
This function is called by:
SOURCE CODE
function o = loadobj(o)
% loadobj method - reloads matrix from img file
%
% $Id$
% Note that the image needs full processing before
% setting into the matrix.  After this, the processed
% natrix data becomes an image snapshot for the memory
% lifetime of the object
[img errstr] = my_vol_func(o);
if isempty(img)
  if strcmp(errstr, 'Cant open image file.')
    errstr = sprintf('%s\nHas ROI image %s been moved?\n%s\n', ...
             errstr, o.vol.fname,...
             'Try to reattach with marsbar(''attach_image'')');
  end
  error(errstr);
end
% set using maroi_matrix object to avoid object conversion
o.maroi_matrix = matrixdata(o.maroi_matrix,img);