Description of vol
Home > marsbar > @maroi_image > vol.m
vol
PURPOSE
vol - returns / sets image vol for object
SYNOPSIS
function h = vol(obj, val)
DESCRIPTION
 vol - returns / sets image vol for object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
my_vol_func checks vol and func, returns processed image matrix or error
matrixdata matrixdata method - gets matrix from ROI object
This function is called by:
my_vol_func checks vol and func, returns processed image matrix or error
rebase rebase method - returns data from maroi_matrix in new space
mars_orthviews Display Orthogonal Views of a Normalized Image
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function h = vol(obj, val)
% vol - returns / sets image vol for object
%
% $Id$
if nargin > 1
  img = my_vol_func(val, obj.func);
  obj.vol = val;
  obj = matrixdata(obj, img);
  h = obj;
else
  h = obj.vol;
end