Description of are_same
Home > marsbar > @maroi > are_same.m
are_same
PURPOSE
returns 1 if rois are the same
SYNOPSIS
function tf = are_same(roi1, roi2, sp)
DESCRIPTION
 returns 1 if rois are the same
 FORMAT tf = are_same(roi1, roi2)
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
native_space native_space method - returns native space of object
maroi_matrix maroi_matrix method - converts maroi_image to maroi_matrix
maroi_matrix maroi_matrix - class constructor
matrixdata matrixdata method - gets matrix from ROI object
native_space native_space method - returns native space of object
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
native_space native_space method - returns native space of object
maroi_matrix method to convert shape objects to maroi_matrix objects
This function is called by:
SOURCE CODE
function tf = are_same(roi1, roi2, sp)
% returns 1 if rois are the same
% FORMAT tf = are_same(roi1, roi2)
%
% $Id$
if nargin < 2
  error('Need two ROIs');
end
if nargin < 3
  sp  = native_space(roi1);
  if isempty(sp)
    sp = native_space(roi2);
  end
  if isempty(sp)
    error('Need space for comparison');
  end
end
mat1 = matrixdata(maroi_matrix(roi1, sp));
mat2 = matrixdata(maroi_matrix(roi2, sp));
tf = all(mat1(:)==mat2(:));