Description of back2base
Home > marsbar > @maroi > back2base.m
back2base
PURPOSE
back2base method - check for spacebase, transform thereto
SYNOPSIS
function o = back2base(o)
DESCRIPTION
 back2base method - check for spacebase, transform thereto
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
my_classdata my_classdata method - sets/gets class data
maroi_matrix maroi_matrix method - converts maroi_image to maroi_matrix
maroi_matrix maroi_matrix - class constructor
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
maroi_matrix method to convert shape objects to maroi_matrix objects
This function is called by:
and overloaded add function
eq overloaded eq function
ge overloaded ge function
gt overloaded gt (greater than) function
le overloaded le (less than or equal to) function
lt overloaded lt (less than) function
minus overloaded minus function
mrdivide overloaded mrdivide (matrix right divide) function
mtimes overloaded mtimes function
ne overloaded ne function
not overloaded not function
or overloaded or function
plus overloaded plus function
rdivide overloaded rdivide function
times overloaded times function
xor overloaded xor function
SOURCE CODE
function o = back2base(o)
% back2base method - check for spacebase, transform thereto
%
% $Id$
spb = my_classdata('spacebase');
if isempty(spb)
  error('Cannot do arithmetic without defined base space');
end
o = maroi_matrix(o, spb);