Description of binarize
Home > marsbar > @maroi > binarize.m
binarize
PURPOSE
binarize - returns / sets binarize value for object
SYNOPSIS
function h = binarize(obj, val)
DESCRIPTION
 binarize - returns / sets binarize value for object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
display display - method
do_write_image method saves matrix as image and returns spm_vol
domaths helper function to do maths on matrix object
matrixdata matrixdata method - gets matrix from ROI object
rebase rebase method - returns data from maroi_matrix in new space
maroi_pointlist maroi_pointlist - class constructor
SOURCE CODE
function h = binarize(obj, val)
% binarize - returns / sets binarize value for object
%
% $Id$
if nargin > 1
  if ~(val == 0 | val == 1)
    error('binarize is 0 or 1 flag');
  end
  obj.binarize = val;
  h = obj;
else
  h = obj.binarize;
end