Description of get_marsy
Home > marsbar > @maroi > get_marsy.m
get_marsy
PURPOSE
gets data in ROIs from images
SYNOPSIS
function marsY = get_marsy(varargin)
DESCRIPTION
 gets data in ROIs from images
 FORMAT marsY = get_marsy(roi1 [, roi2 [, roi3...]], VY, sumfunc, flags)
 roi1, roi2... - ROI objects
                   This rather arcane call is needed because matlab
                   does not allow different object types in an array
 VY            - array of SPM vol structs, or image names, or SPM design
 sumfunc       - one of 'mean', 'median', 'eigen1', 'wtmean'  to summarize
                   data in the ROIs
 flags         - none or more of
                   'v' - selects verbose output to matlab console
 Returns
 marsY      - MarsBaR data object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
descrip method gets cell string description of design
has_images returns 1 if design contains images, NaN if not known
isempty overloaded isempty method for mardo object
summary method returns cell array of strings describing design
block_rows returns cell array of rows for each (subject/session) block
get_images method to get image vols from design
has_images returns 1 if design contains images
tr method returns TR in seconds, or empty if not available
block_rows returns cell array of rows for each (subject/session) block
get_images method to get image vols from design
has_images returns 1 if design contains images
tr method returns TR in seconds, or empty if not available
descrip name - returns / sets name value for object
getdata getdata method - fetches time series data for ROI from images
label label - returns / sets label value for object
source source - returns / sets source value for object
block_rows gets/sets cell array of rows for each (subject/session) block
marsy Class constructor for marsy: the MarsBaR data object
sumfunc method to get or set sumfunc
summary method returns cell array of strings describing marsy object
This function is called by:
run_tutorial MarsBaR batch script to show off MarsBaR batching
marsbar Startup, callback and utility routine for Marsbar
test_rig runs tests on MarsBaR using specified designs
SOURCE CODE
function marsY = get_marsy(varargin)
% gets data in ROIs from images
% FORMAT marsY = get_marsy(roi1 [, roi2 [, roi3...]], VY, sumfunc, flags)
%
% roi1, roi2... - ROI objects
%                   This rather arcane call is needed because matlab
%                   does not allow different object types in an array
% VY            - array of SPM vol structs, or image names, or SPM design
% sumfunc       - one of 'mean', 'median', 'eigen1', 'wtmean'  to summarize
%                   data in the ROIs
% flags         - none or more of
%                   'v' - selects verbose output to matlab console
%
% Returns
% marsY      - MarsBaR data object
%
% $Id$
for r = 1:nargin
  if ~isa(varargin{r}, 'maroi')
    break
  end
end
rlen = r - 1;
roi_array = varargin(1:rlen);
narg_left = nargin - rlen;
if narg_left < 1
  VY = [];
else
  VY = varargin{r};
end
if isempty(VY), error('Need images to extract from'); end
if narg_left < 2
  sumfunc = '';
else
  sumfunc = varargin{r+1};
end
if isempty(sumfunc), error('Need summary function'); end
if narg_left < 3
  flags = '';
else
  flags = varargin{r+2};
end
if isempty(flags), flags = ' '; end
vf = any(flags == 'v');
% images can come from a design
des_summary = 'None';
if isa(VY, 'mardo')
  if ~has_images(VY)
    error('This design does not contain images');
  end
  D  = VY;
  VY = get_images(VY);
else
  D  = [];
end
% or be filenames
if ischar(VY)
  if vf, fprintf('%-40s: ','Mapping files');  end
  VY = spm_vol(VY);
  if vf, fprintf('%30s\n','...done'); end
end
if vf, fprintf('%-40s: %30s','Fetching data',' '); end
rlen = length(roi_array);
rno = 0;
for r = 1:rlen
  if vf
    fprintf('%s%30s',...
        repmat(sprintf('\b'),1,30),...
        sprintf('%4d/%-4d',r, rlen));
  end
  o = roi_array{r};
  [y vals vXYZ mat]  = getdata(o, VY);
  [ny nvals] = size(y);
  if isempty(y)
    if vf, fprintf('\n'); end
    warning(sprintf('No valid data for roi %d (%s)', r, label(o)));
    if vf & (r < rlen), fprintf('%-40s: %30s','Fetching data',' '); end
  else
    rno = rno + 1;
    % get data for regions
    if all(vals == 1)
      vals = [];
    end
    r_data{rno} = y;
    r_info{rno} = struct(...
        'name', label(o),...
        'descrip', descrip(o),...
        'weights', vals,...
        'info', struct('file', source(o)),...
        'vXYZ', vXYZ,...
        'mat', mat);
    if rno < 2,  lbl = label(o); else lbl = [lbl ' & ' label(o)]; end
  end
end
if vf, fprintf('%s%30s\n',repmat(sprintf('\b'),1,30),'...done'); end
if rno == 0
  marsY = [];
  return;
end
s_info = struct(...
    'sumfunc', sumfunc, ...
    'descrip', ['Data from ' lbl],...
    'info', struct('VY', VY));
% Fill any available information from design if passed
if ~isempty(D)
  s_info.info.des_summary = summary(D);
  s_info.info.TR          = tr(D);
  s_info.block_rows       = block_rows(D);
end
marsY = marsy(r_data, r_info, s_info);