Description of label
Home > marsbar > @maroi > label.m
label
PURPOSE
label - returns / sets label value for object
SYNOPSIS
function h = label(obj, val)
DESCRIPTION
 label - returns / sets label value for object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
display display - method
get_marsy gets data in ROIs from images
run_tutorial MarsBaR batch script to show off MarsBaR batching
mars_build_roi builds ROIs via the SPM GUI
mars_display_roi utility routines for display of ROIs in graphic window
mars_rois2img creates cluster or number labelled ROI image from ROIs
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function h = label(obj, val)
% label - returns / sets label value for object
%
% $Id$
if nargin > 1
  obj.label = val;
  h = obj;
else
  h = obj.label;
end