Description of realpts
Home > marsbar > @maroi > realpts.m
realpts
PURPOSE
realpts method - returns 3xN XYZ matrix in mm
SYNOPSIS
function [pts, vals] = realpts(o,sp)
DESCRIPTION
 realpts method - returns 3xN XYZ matrix in mm
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
voxpts voxpts method - voxels within a box in given space
voxpts voxpts method - returns 3xN ijk matrix in voxels
voxpts voxpts method - returns 3xN ijk matrix in voxels
voxpts voxpts method - voxels within a sphere in given space
This function is called by:
c_o_m c_o_m method - calculates unweighted centre of mass
getdata getdata method - fetches time series data for ROI from images
mars_display_roi utility routines for display of ROIs in graphic window
SOURCE CODE
function [pts, vals] = realpts(o,sp)
% realpts method - returns 3xN XYZ matrix in mm
%
% $Id$
if nargin < 2
  error('Need space definition to find voxels');
end
[pts vals] = voxpts(o, sp);
if ~isempty(pts)
  pts = sp.mat * [pts; ones(1, size(pts,2))];
  pts = pts(1:3,:);
end