Description of rle
Home > marsbar > @maroi > rle.m
rle
PURPOSE
run length encoding method
SYNOPSIS
function rlem = rle(o, sp)
DESCRIPTION
 run length encoding method
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
native_space native_space method - returns native space of object
maroi_matrix maroi_matrix method - converts maroi_image to maroi_matrix
maroi_matrix maroi_matrix - class constructor
native_space native_space method - returns native space of object
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
native_space native_space method - returns native space of object
maroi_matrix method to convert shape objects to maroi_matrix objects
This function is called by:
save_mricro saves in MRIcro format
SOURCE CODE
function rlem = rle(o, sp)
% run length encoding method
%
% $Id$
if nargin < 1
  sp = native_space(o);
end
if isempty(sp)
  error('Need defined, or passed native space for run length encoding')
end
o = maroi_matrix(o, sp);
rlem = do_rle(o);