Description of save_mricro
Home > marsbar > @maroi > save_mricro.m
save_mricro
PURPOSE
saves in MRIcro format
SYNOPSIS
function save_mricro(o, fname, sp)
DESCRIPTION
 saves in MRIcro format
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
native_space native_space method - returns native space of object
rle run length encoding method
native_space native_space method - returns native space of object
native_space native_space method - returns native space of object
This function is called by:
SOURCE CODE
function save_mricro(o, fname, sp)
% saves in MRIcro format
%
% $Id$
if nargin < 2
  error('Need filename for MRIcro save');
end
if nargin < 3
  sp = native_space(o);
end
rlem = rle(o, sp);
fid = fopen(fname, 'wb');
if fid == -1
  error(['Could not open file ' fname]);
end
fclose(fid);
error('Come to think of it, I don''t understand the format anyhow');