Description of save_as_image
Home > marsbar > @maroi > save_as_image.m
save_as_image
PURPOSE
method save_as_image - saves ROI as image
SYNOPSIS
function v = save_as_image(o, fname, sp)
DESCRIPTION
 method save_as_image - saves ROI as image
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
maroi_matrix maroi_matrix method - converts maroi_image to maroi_matrix
do_write_image method saves matrix as image and returns spm_vol
maroi_matrix maroi_matrix - class constructor
maroi_matrix maroi_matrix method - converts roi to maroi matrix type
maroi_matrix method to convert shape objects to maroi_matrix objects
This function is called by:
run_tutorial MarsBaR batch script to show off MarsBaR batching
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function v = save_as_image(o, fname, sp)
% method save_as_image - saves ROI as image
%
% $Id$
if nargin < 2
  error('Need ROI and filename');
end
if nargin < 3
  sp = [];
end
o = maroi_matrix(o, sp);
v = do_write_image(o, fname);