Description of saveroi
Home > marsbar > @maroi > saveroi.m
saveroi
PURPOSE
saveroi method - checks fname, sets source field, saves object
SYNOPSIS
function roi = saveroi(roi, fname)
DESCRIPTION
 saveroi method - checks fname, sets source field, saves object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
isempty overloaded isempty method for mardo object
source source - returns / sets source value for object
This function is called by:
run_tutorial MarsBaR batch script to show off MarsBaR batching
mars_blobs2rois creates ROIs from spm_results_ui SPM
mars_img2rois creates ROIs from cluster image or image containing ROIs defined by unique nos
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function roi = saveroi(roi, fname)
% saveroi method - checks fname, sets source field, saves object
%
% $Id$
if nargin < 2
  fname = source(roi);
end
if isempty(fname)
  error('Need filename for save');
end
roi.source = fname;
save(roi.source, 'roi');