Description of source
Home > marsbar > @maroi > source.m
source
PURPOSE
source - returns / sets source value for object
SYNOPSIS
function h = source(obj, val)
DESCRIPTION
 source - returns / sets source value for object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
display display - method
get_marsy gets data in ROIs from images
my_loadroi my_loadroi function - loads ROI from file, sets source field
saveroi saveroi method - checks fname, sets source field, saves object
domaths helper function to do maths on matrix object
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function h = source(obj, val)
% source - returns / sets source value for object
%
% $Id$
if nargin > 1
  obj.source = val;
  h = obj;
else
  h = obj.source;
end