Description of spm_hold
Home > marsbar > @maroi > spm_hold.m
spm_hold
PURPOSE
hold - returns / sets hold value for object
SYNOPSIS
function h = spm_hold(obj, val)
DESCRIPTION
 hold - returns / sets hold value for object
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
display display - method
getdata getdata method - fetches time series data for ROI from images
rebase rebase method - returns data from maroi_matrix in new space
SOURCE CODE
function h = spm_hold(obj, val)
% hold - returns / sets hold value for object
%
% $Id$
if nargin > 1
  obj.spm_hold = val;
  h = obj;
else
  h = obj.spm_hold;
end