Description of compute_contrasts
Home > marsbar > @mardo_99 > compute_contrasts.m
compute_contrasts
PURPOSE
compute and return stats
SYNOPSIS
function [marsS] = compute_contrasts(marsDe, Ic)
DESCRIPTION
 compute and return stats
 FORMAT marsS = compute_contrasts(marsDe, Ic)
 marsDe     - design object
 Ic         - indices into contrast structure
 Output
 marsS      - statistic result structure
 For the 'con', 'stat' 'P' 'Pc' fields below, the results are matrices
 with one row per contrast, one column per ROI estimated
 The statistics results structure has fields
 'con'      - contrast value (numerator of t statistic, or ESS for F)
 'stat'     - t or F statistic value
 'P'        - uncorrected P value
 'Pc'       - P values corrected for number of ROIs
 'MVres'    - multivariate results structure with fields
              'y_pre'    - predicted temporal response
              'y_obs'    - observerd temporal response
              'Pf'       - probabability for last (rank of subspace)
                           eigenvalues
              'u'        - principle components
              'ds'       - component weights (diag(S))
              'df'       - degrees of freedom for Pf
 'columns'  - names of regions
 'rows'     - cell array of structs, one per contrast calculated,
              with fields:
              'name'  - contrast name
              'stat'  - statistic type (T|F)
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
pr_stat_compute private function to compute statistics for SPM2 design
pr_stat_compute_mv private function to compute mutlivariate statistics across ROIs
pr_stat_compute private function to compute statistics for SPM2 design
pr_stat_compute_mv private function to compute mutlivariate statistics across ROIs
pr_stat_compute calculates contrast value, stats and p values for contrasts
pr_stat_compute_mv compute multivariate statistics across ROIs
region_name method gets or sets data for region name
summary_data method to get summary data, maybe set sumfunc
This function is called by:
stat_table gets Mars statistics and creates statistic table as cell array
run_tutorial MarsBaR batch script to show off MarsBaR batching
test_rig runs tests on MarsBaR using specified designs
SOURCE CODE
function [marsS] = compute_contrasts(marsDe, Ic)
% compute and return stats
% FORMAT marsS = compute_contrasts(marsDe, Ic)
%
% marsDe     - design object
% Ic         - indices into contrast structure
%
% Output
% marsS      - statistic result structure
%
% For the 'con', 'stat' 'P' 'Pc' fields below, the results are matrices
% with one row per contrast, one column per ROI estimated
%
% The statistics results structure has fields
% 'con'      - contrast value (numerator of t statistic, or ESS for F)
% 'stat'     - t or F statistic value
% 'P'        - uncorrected P value
% 'Pc'       - P values corrected for number of ROIs
% 'MVres'    - multivariate results structure with fields
%              'y_pre'    - predicted temporal response
%              'y_obs'    - observerd temporal response
%              'Pf'       - probabability for last (rank of subspace)
%                           eigenvalues
%              'u'        - principle components
%              'ds'       - component weights (diag(S))
%              'df'       - degrees of freedom for Pf
% 'columns'  - names of regions
% 'rows'     - cell array of structs, one per contrast calculated,
%              with fields:
%              'name'  - contrast name
%              'stat'  - statistic type (T|F)
%
% $Id$
SPM = des_struct(marsDe);
xCon = SPM.xCon;
if nargin < 2
  Ic = 1:length(xCon);
end
%- results
[marsS.con marsS.stat, marsS.P, marsS.Pc] = ...
    pr_stat_compute(xCon(Ic), SPM.xX.xKXs, SPM.xX.V, ...
              SPM.betas, SPM.ResidualMS);
marsS.MVres = pr_stat_compute_mv(xCon(Ic), SPM.xX.xKXs, SPM.xX.V, ...
                 SPM.betas, SPM.ResidualMS, ...
                 summary_data(SPM.marsY));
marsS.columns = region_name(SPM.marsY);
for i = 1:length(Ic)
  marsS.rows{i}.name = xCon(Ic(i)).name;
  marsS.rows{i}.stat = xCon(Ic(i)).STAT;
end