Description of convert_vols
Home > marsbar > @mardo_99 > convert_vols.m
convert_vols
PURPOSE
method that converts vol structs in design and converts to format 'ver'
SYNOPSIS
function o = convert_vols(o, ver)
DESCRIPTION
 method that converts vol structs in design and converts to format 'ver'
 FORMAT o = convert_fo(o, ver)
 Input
 o        - design object
 ver      - optional version for vols from '99' or '5'
            Defaults to version for current SPM version
 Output
 o        - object with converted vols
 Example
 % Convert vols to current format
 o = convert_vols(o);
 % Convert to native format for SPM99 designs
 o = convert_vols(o, native_vol_ver(o));
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
isempty overloaded isempty method for mardo object
mars_struct multifunction function for manipulating structures
mars_vol_utils collection of useful utility functions for vol structs
This function is called by:
savestruct saves data in def_struct as variables in .mat file
mardo_2 class constructor for SPM2 MarsBaR design object
save_spm method to save design as SPM format design structure
savestruct saves data in def_struct into .mat file with variable name SPM
mardo_5 class constructor for SPM5 MarsBaR design object
mardo_99 class constructor for SPM99 MarsBaR design object
save_spm method to save design as SPM format design structure
SUBFUNCTIONS
function S = sf_conv(S, ver, varargin)
SOURCE CODE
function o = convert_vols(o, ver)
% method that converts vol structs in design and converts to format 'ver'
% FORMAT o = convert_fo(o, ver)
%
% Input
% o        - design object
% ver      - optional version for vols from '99' or '5'
%            Defaults to version for current SPM version
%
% Output
% o        - object with converted vols
%
% Example
% % Convert vols to current format
% o = convert_vols(o);
%
% % Convert to native format for SPM99 designs
% o = convert_vols(o, native_vol_ver(o));
%
% $Id$
if nargin < 2
  ver = mars_vol_utils('current_ver');
end
SPM = des_struct(o);
SPM = sf_conv(SPM, ver, 'VY');
SPM = sf_conv(SPM, ver, 'xM', 'VM');
o = des_struct(o, SPM);
return
function S = sf_conv(S, ver, varargin)
V = mars_struct('getifthere', S, varargin{:});
if ~isempty(V)
  V = mars_vol_utils('convert', V, ver);
  S = setfield(S, varargin{:}, V);
end
return