Description of event_cols
Home > marsbar > @mardo_99 > event_cols.m
event_cols
PURPOSE
method gets design columns for single event
SYNOPSIS
function I = event_cols(D, e_spec)
DESCRIPTION
 method gets design columns for single event
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
is_fmri method returns 1 if this is an fmri design
This function is called by:
event_fitted method to compute fitted event time course
event_fitted_fir method to compute fitted event time courses using FIR
ui_ft_design_data method plots FT of design and data to graphics window
SOURCE CODE
function I = event_cols(D, e_spec)
% method gets design columns for single event
%
% $Id$
if nargin < 2
  error('Need design and event spec');
end
if ~is_fmri(D)
  error('Needs FMRI design');
end
SPM   = des_struct(D);
Sess  = SPM.Sess;
ss    = e_spec(1);
en    = e_spec(2);
j    = 1:size(Sess{ss}.sf{en},2):length(Sess{ss}.ind{en});
I    = Sess{ss}.col(Sess{ss}.ind{en}(j));