Description of fwhm
Home > marsbar > @mardo_99 > fwhm.m
fwhm
PURPOSE
method returns FWHM, or empty if not available
SYNOPSIS
function f = fwhm(o)
DESCRIPTION
 method returns FWHM, or empty if not available
 $Id: tr.m,v 1.1 2004/01/26 22:08:55 matthewbrett Exp $
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
er_smooth smooth images prior to analysis
SOURCE CODE
function f = fwhm(o)
% method returns FWHM, or empty if not available
%
% $Id: tr.m,v 1.1 2004/01/26 22:08:55 matthewbrett Exp $
f = [];
SPM = des_struct(o);
if mars_struct('isthere', SPM, 'FWHM')
  f = SPM.FWHM;
end