Description of has_filter
Home > marsbar > @mardo_99 > has_filter.m
has_filter
PURPOSE
returns 1 if object contains filter
SYNOPSIS
function tf = has_filter(o)
DESCRIPTION
 returns 1 if object contains filter
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
isfield method to overload isfield for mardo objects
This function is called by:
residuals method returns residuals from model
summary method returns cell array of strings describing design
apply_filter applies filter in design to data
can_mars_estimate method returns 1 if design can be estimated in MarsBaR
fill fills missing entries from SPM FMRI design matrix
fill fills missing entries from SPM FMRI design matrix
apply_filter applies filter in design to data
can_mars_estimate method returns 1 if design can be estimated in MarsBaR
fill fills missing entries from SPM FMRI design matrix
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function tf = has_filter(o)
% returns 1 if object contains filter
%
% $Id$
tf = 0;
des = des_struct(o);
if isfield(des, 'xX')
  tf = isfield(des.xX, 'K');
end