Description of has_autocorr
Home > marsbar > @mardo_99 > has_autocorr.m
has_autocorr
PURPOSE
returns 1 if object contains autocorrelation specification
SYNOPSIS
function tf = has_autocorr(o)
DESCRIPTION
 returns 1 if object contains autocorrelation specification
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
can_mars_estimate method returns 1 if design can be estimated in MarsBaR
fill fills missing entries from SPM FMRI design matrix
fill fills missing entries from SPM FMRI design matrix
SOURCE CODE
function tf = has_autocorr(o)
% returns 1 if object contains autocorrelation specification
%
% $Id$
tf = 0;