Description of save_spm
Home > marsbar > @mardo_99 > save_spm.m
save_spm
PURPOSE
method to save design as SPM format design structure
SYNOPSIS
function tf = save_spm(D, fname);
DESCRIPTION
 method to save design as SPM format design structure
 FORMAT tf = save_spm(D, fname);
 Inputs
 D      - design object
 fname  - filename
 Outputs
 tf     - flag ==1 if successful
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
has_images returns 1 if design contains images, NaN if not known
is_fmri method returns 1 if this is an fmri design
is_spm_estimated returns 1 if design has been estimated in SPM
isempty overloaded isempty method for mardo object
native_vol_ver return string specifying native vol type
savestruct saves data in def_struct as variables in .mat file
verbose get/set method for verbose field
convert_vols method that converts vol structs in design and converts to format 'ver'
has_images returns 1 if design contains images
savestruct saves data in def_struct into .mat file with variable name SPM
convert_vols method that converts vol structs in design and converts to format 'ver'
native_vol_ver return string specifying native vol type
convert_vols method that converts vol structs in design and converts to format 'ver'
has_images returns 1 if design contains images
savestruct saves data in y_struct as variables in .mat file
verbose get/set method for verbose field
mars_struct multifunction function for manipulating structures
mars_utils collection of useful utility functions for MarsBaR etc
savestruct saves data in structure as variables in .mat file
This function is called by:
SOURCE CODE
function tf = save_spm(D, fname);
% method to save design as SPM format design structure
% FORMAT tf = save_spm(D, fname);
%
% Inputs
% D      - design object
% fname  - filename
%
% Outputs
% tf     - flag ==1 if successful
%
% $Id$
if nargin < 2
  if is_spm_estimated(D)
    fname = 'SPM.mat';
  elseif has_images(D)
    fname = 'SPMcfg.mat';
  elseif is_fmri(D)
    fname = 'SPM_fMRIDesMtx.mat';
  else
    error('Cannot work out design type for default filename');
  end
end
% Convert vols to native format
D = convert_vols(D, native_vol_ver(D));
SPM = des_struct(D);
if ~mars_utils('isabspath', fname)
  Swd = mars_struct('getifthere', SPM, 'swd');
  if isempty(Swd)
    error('No path passed, and none in design');
  end
  fname = fullfile(Swd, fname);
else
  SPM.swd = fileparts(fname);
end
try
  if verbose(D)
    fprintf('Saving design to file %s\n', fname);
  end
  savestruct(SPM, fname);
  tf = 1;
catch
  warning(lasterr);
  tf = 0;
end