Description of tr
Home > marsbar > @mardo_99 > tr.m
tr
PURPOSE
method returns TR in seconds, or empty if not available
SYNOPSIS
function t = tr(o)
DESCRIPTION
 method returns TR in seconds, or empty if not available
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
event_fitted_fir method to compute fitted event time courses using FIR
ui_ft_design_data method plots FT of design and data to graphics window
event_onsets method gets onsets and durations for event/session
event_x_fir method to return FIR design matrix columns for session
event_onsets method gets (estimated) onsets and durations for event/session
event_x_fir method to return FIR design matrix columns for session
mars_spm_graph Graphical display of adjusted data
get_marsy gets data in ROIs from images
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function t = tr(o)
% method returns TR in seconds, or empty if not available
%
% $Id$
t = [];
SPM = des_struct(o);
if mars_struct('isthere', SPM, 'xX', 'RT')
  t = SPM.xX.RT;
end