Description of ui_get_filter
Home > marsbar > @mardo_99 > ui_get_filter.m
ui_get_filter
PURPOSE
method to get filter via GUI
SYNOPSIS
function [D,descrip] = ui_get_filter(D)
DESCRIPTION
 method to get filter via GUI
 FORMAT [D,descrip] = ui_get_filter(D)
 Input
 D       - design
 Returns
 D       - design with modified filter
 descrip - cell array of strings describing filter
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
descrip method gets cell string description of design
isfield method to overload isfield for mardo objects
pr_get_filter gets filter using spm_fmri_spm_ui routines
pr_get_filter gets filter using spm_fmri_spm_ui routines
pr_get_filter gets filter using spm_fmri_spm_ui routines
descrip name - returns / sets name value for object
This function is called by:
SOURCE CODE
function [D,descrip] = ui_get_filter(D)
% method to get filter via GUI
% FORMAT [D,descrip] = ui_get_filter(D)
%
% Input
% D       - design
%
% Returns
% D       - design with modified filter
% descrip - cell array of strings describing filter
%
% $Id$
SPM = des_struct(D);
[K Hf Lf] = pr_get_filter(SPM.xX.RT, SPM.Sess);
SPM.xX.K = K;
if ~isfield(SPM, 'xsDes')
  SPM.xsDes = [];
end
SPM.xsDes.High_pass_Filter = Lf;
SPM.xsDes.Low_pass_Filter  = Hf;
% return args
D = des_struct(D, SPM);
descrip = {['High_pass_Filter:\t%s', Lf],...
       ['Low_pass_Filter: \t%s', Hf]};