Description of bf_dt
Home > marsbar > @mardo_2 > bf_dt.m
bf_dt
PURPOSE
method returns length of time bin for basis functions
SYNOPSIS
function d = bf_dt(D)
DESCRIPTION
 method returns length of time bin for basis functions
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
mars_struct multifunction function for manipulating structures
This function is called by:
event_fitted_fir method to compute fitted event time courses using FIR
event_onsets method gets (estimated) onsets and durations for event/session
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function d = bf_dt(D)
% method returns length of time bin for basis functions
%
% $Id$
SPM = des_struct(D);
d   = mars_struct('getifthere', SPM, 'xBF', 'dt');