Description of can_mars_estimate
Home > marsbar > @mardo_2 > can_mars_estimate.m
can_mars_estimate
PURPOSE
method returns 1 if design can be estimated in MarsBaR
SYNOPSIS
function tf = can_mars_estimate(D)
DESCRIPTION
 method returns 1 if design can be estimated in MarsBaR
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
has_filter returns 1 if object contains filter
is_fmri method returns 1 if this is an fmri design
has_autocorr returns 1 if object contains autocorrelation specification
has_filter returns 1 if object contains filter
has_autocorr returns 1 if object contains autocorrelation specification
has_filter returns 1 if object contains filter
This function is called by:
estimate estimate method - estimates GLM for SPM2 model
estimate estimate method - estimates GLM for SPM2 model
estimate estimate method - estimates GLM for SPM99 model
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function tf = can_mars_estimate(D)
% method returns 1 if design can be estimated in MarsBaR
%
% $Id$
tf = ~is_fmri(D) | (has_filter(D) & has_autocorr(D));