Description of event_specs
Home > marsbar > @mardo_2 > event_specs.m
event_specs
PURPOSE
method to return event specifications for all event in model
SYNOPSIS
function [e_specs, e_names] = event_specs(D)
DESCRIPTION
 method to return event specifications for all event in model
 FORMAT [e_specs, e_names] = event_specs(D)
 D          - design object
 Returns
 e_specs    - event specification 2 by N matrix where row 1 is the
              session number of the event, row 2 is the event number in
              the session
 e_names    - names of each event
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
is_fmri method returns 1 if this is an fmri design
This function is called by:
event_types_named method returns event types structures for events with same names
ui_et_edit method to edit invidual event types in design
SOURCE CODE
function [e_specs, e_names] = event_specs(D)
% method to return event specifications for all event in model
% FORMAT [e_specs, e_names] = event_specs(D)
%
% D          - design object
%
% Returns
% e_specs    - event specification 2 by N matrix where row 1 is the
%              session number of the event, row 2 is the event number in
%              the session
%
% e_names    - names of each event
%
% $Id$
if ~is_fmri(D)
  error('Needs FMRI design');
end
SPM   = des_struct(D);
Sess  = SPM.Sess;
nsess = length(Sess);
e_specs = [];
e_names = {};
e_ctr = 1;
for ss = 1:nsess
  nevs = length(Sess(ss).U);
  e_specs = [e_specs [ones(1, nevs) * ss; 1:nevs]];
  e_names = [e_names {Sess(ss).Fc(:).name}];
end