Description of get_images
Home > marsbar > @mardo_2 > get_images.m
get_images
PURPOSE
method to get image vols from design
SYNOPSIS
function VY = get_images(marsD)
DESCRIPTION
 method to get image vols from design
 FORMAT VY = get_images(marsD)
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
This function is called by:
cd_images method for changing path to image files in design
flip_images flips images in design
image_names method returning image file names for design
images method to get or set images
prefix_images method for adding or removing prefix from file names in design
mardo_2 method to convert SPM2 design to SPM99 design
get_marsy gets data in ROIs from images
mars_image_scaling get image scaling data for images, maybe via SPM design
SOURCE CODE
function VY = get_images(marsD)
% method to get image vols from design
% FORMAT VY = get_images(marsD)
%
% $Id$
D = des_struct(marsD);
VY = D.xY.VY;