Description of has_whitener
Home > marsbar > @mardo_2 > has_whitener.m
has_whitener
PURPOSE
returns 1 if design has whitening filter
SYNOPSIS
function tf = has_whitener(D)
DESCRIPTION
 returns 1 if design has whitening filter
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
isfield method to overload isfield for mardo objects
This function is called by:
apply_filter applies filter in design to data
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function tf = has_whitener(D)
% returns 1 if design has whitening filter
%
% $Id$
tf = 0;
SPM = des_struct(D);
if isfield(SPM, 'xX')
  tf = isfield(SPM.xX, 'W');
end