Description of set_images
Home > marsbar > @mardo_2 > set_images.m
set_images
PURPOSE
method to set image vols to design
SYNOPSIS
function marsD = set_images(marsD, VY)
DESCRIPTION
 method to set image vols to design
 $Id%
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
This function is called by:
cd_images method for changing path to image files in design
flip_images flips images in design
images method to get or set images
prefix_images method for adding or removing prefix from file names in design
SOURCE CODE
function marsD = set_images(marsD, VY)
% method to set image vols to design
%
% $Id%
if nargin < 2
  error('Need image volumes');
end
D = des_struct(marsD);
D.xY.VY = VY;
D.xY.P = strvcat(VY(:).fname);
marsD = des_struct(marsD, D);