Description of ui_build
Home > marsbar > @mardo_2 > ui_build.m
ui_build
PURPOSE
method to create / fill design via GUI
SYNOPSIS
function D = ui_build(D, dtype)
DESCRIPTION
 method to create / fill design via GUI
 FORMAT D = ui_build(D, dtype)
 D      - design object
 dtype  - one of 'PET', 'FMRI', 'Basic')
 Returns
 D      - design object with new design
 $Id$
CROSS-REFERENCE INFORMATION
This function calls:
des_struct get/set method for des_struct field
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_spm_ui MarsBaR: setting up the general linear model for independent data
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_spm_ui MarsBaR: Setting up the general linear model for independent data
pr_fmri_design MarsBaR version of spm_fMRI design - asssembles a design for fMRI studies
pr_spm_ui MarsBaR: setting up the general linear model for independent data
This function is called by:
marsbar Startup, callback and utility routine for Marsbar
SOURCE CODE
function D = ui_build(D, dtype)
% method to create / fill design via GUI
% FORMAT D = ui_build(D, dtype)
%
% D      - design object
% dtype  - one of 'PET', 'FMRI', 'Basic')
%
% Returns
% D      - design object with new design
%
% $Id$
if nargin < 2
  error('Need design type');
end
switch lower(dtype)
 case 'pet'
  SPM = pr_spm_ui('cfg',spm_spm_ui('DesDefs_PET'));
 case 'basic'
  SPM = pr_spm_ui('cfg',spm_spm_ui('DesDefs_Stats'));
 case 'fmri'
  SPM = pr_fmri_design;
 otherwise
  error(['Did not recognize design type: ' dtype]);
end
D = des_struct(D, SPM);